var hierarchy =
[
    [ "accelSettings", "_l_s_m9_d_s1___types_8h.html#structaccel_settings", null ],
    [ "Adafruit_Sensor", "class_adafruit___sensor.html", [
      [ "Adafruit_ADXL345_Unified", "class_adafruit___a_d_x_l345___unified.html", null ],
      [ "Adafruit_TSL2561_Unified", "class_adafruit___t_s_l2561___unified.html", null ]
    ] ],
    [ "Adafruit_SHT31", "class_adafruit___s_h_t31.html", null ],
    [ "Adafruit_SI1145", "class_adafruit___s_i1145.html", null ],
    [ "BLEPeripheral", null, [
      [ "BLEStream", "class_b_l_e_stream.html", null ]
    ] ],
    [ "cid_t", "_sd_info_8h.html#structcid__t", null ],
    [ "csd1_t", "_sd_info_8h.html#structcsd1__t", null ],
    [ "csd2_t", "_sd_info_8h.html#structcsd2__t", null ],
    [ "csd_t", "_sd_info_8h.html#unioncsd__t", null ],
    [ "DallasTemperature", "class_dallas_temperature.html", null ],
    [ "data_struct", "_weather___balloon_8cpp.html#structdata__struct", null ],
    [ "data_struct.accel", "_weather___balloon_8cpp.html#structdata__struct_8accel", null ],
    [ "data_struct.battery", "_weather___balloon_8cpp.html#structdata__struct_8battery", null ],
    [ "data_struct.enabled", "_weather___balloon_8cpp.html#structdata__struct_8enabled", null ],
    [ "data_struct.found", "_weather___balloon_8cpp.html#structdata__struct_8found", null ],
    [ "data_struct.geiger", "_weather___balloon_8cpp.html#structdata__struct_8geiger", null ],
    [ "data_struct.gps", "_weather___balloon_8cpp.html#structdata__struct_8gps", null ],
    [ "data_struct.gyro", "_weather___balloon_8cpp.html#structdata__struct_8gyro", null ],
    [ "data_struct.mag", "_weather___balloon_8cpp.html#structdata__struct_8mag", null ],
    [ "data_struct.ms5607", "_weather___balloon_8cpp.html#structdata__struct_8ms5607", null ],
    [ "data_struct.pwm", "_weather___balloon_8cpp.html#structdata__struct_8pwm", null ],
    [ "data_struct.sht31", "_weather___balloon_8cpp.html#structdata__struct_8sht31", null ],
    [ "data_struct.temp", "_weather___balloon_8cpp.html#structdata__struct_8temp", null ],
    [ "data_struct.tsl", "_weather___balloon_8cpp.html#structdata__struct_8tsl", null ],
    [ "DateTime", "class_date_time.html", null ],
    [ "deviceSettings", "_l_s_m9_d_s1___types_8h.html#structdevice_settings", null ],
    [ "DS3231", "class_d_s3231.html", null ],
    [ "eeprom_struct", "_weather___balloon_8cpp.html#structeeprom__struct", null ],
    [ "FilterDerivative", "struct_filter_derivative.html", null ],
    [ "FilterOnePole", "struct_filter_one_pole.html", null ],
    [ "FilterOnePoleCascade", "struct_filter_one_pole_cascade.html", null ],
    [ "FilterTwoPole", "struct_filter_two_pole.html", null ],
    [ "FirmataClass", "class_firmata_class.html", null ],
    [ "FirmataFeature", "class_firmata_feature.html", [
      [ "SerialFirmata", "class_serial_firmata.html", null ]
    ] ],
    [ "gyroSettings", "_l_s_m9_d_s1___types_8h.html#structgyro_settings", null ],
    [ "IMUSettings", "_l_s_m9_d_s1___types_8h.html#struct_i_m_u_settings", null ],
    [ "LedControl", "class_led_control.html", null ],
    [ "LSM9DS1", "class_l_s_m9_d_s1.html", null ],
    [ "MAG3110", "class_m_a_g3110.html", null ],
    [ "magSettings", "_l_s_m9_d_s1___types_8h.html#structmag_settings", null ],
    [ "MAX17043", "class_m_a_x17043.html", null ],
    [ "MS5xxx", "class_m_s5xxx.html", [
      [ "MS5611", "class_m_s5611.html", null ]
    ] ],
    [ "OneWire", "class_one_wire.html", null ],
    [ "PID", "class_p_i_d.html", null ],
    [ "Port_Pin", "_zero_regs_8cpp.html#struct_port___pin", null ],
    [ "RawDegrees", "struct_raw_degrees.html", null ],
    [ "RTC_DS1307", "class_r_t_c___d_s1307.html", null ],
    [ "RTC_DS3231", "class_r_t_c___d_s3231.html", null ],
    [ "RTC_DS3234", "class_r_t_c___d_s3234.html", null ],
    [ "RTC_Millis", "class_r_t_c___millis.html", null ],
    [ "RTCAlarmTime", "_d_s3231_8h.html#struct_r_t_c_alarm_time", null ],
    [ "RTCDateTime", "_d_s3231_8h.html#struct_r_t_c_date_time", null ],
    [ "RTCZero", "class_r_t_c_zero.html", null ],
    [ "RunningStatistics", "struct_running_statistics.html", null ],
    [ "Sd2Card", "class_sd2_card.html", null ],
    [ "sd_data", "_weather___balloon_8cpp.html#structsd__data", null ],
    [ "sensor_t", "_adafruit___sensor_8h.html#structsensor__t", null ],
    [ "sensors_color_t", "_adafruit___sensor_8h.html#structsensors__color__t", null ],
    [ "sensors_color_t.__unnamed__", "_adafruit___sensor_8h.html#unionsensors__color__t_8____unnamed____", null ],
    [ "sensors_color_t.__unnamed__.__unnamed__", "_adafruit___sensor_8h.html#structsensors__color__t_8____unnamed_____8____unnamed____", null ],
    [ "sensors_event_t", "_adafruit___sensor_8h.html#structsensors__event__t", null ],
    [ "sensors_event_t.__unnamed__", "_adafruit___sensor_8h.html#unionsensors__event__t_8____unnamed____", null ],
    [ "sensors_vec_t", "_adafruit___sensor_8h.html#structsensors__vec__t", null ],
    [ "sensors_vec_t.__unnamed__", "_adafruit___sensor_8h.html#unionsensors__vec__t_8____unnamed____", null ],
    [ "sensors_vec_t.__unnamed__.__unnamed__", "_adafruit___sensor_8h.html#structsensors__vec__t_8____unnamed_____8____unnamed____", null ],
    [ "sensors_vec_t.__unnamed__.__unnamed__", "_adafruit___sensor_8h.html#structsensors__vec__t_8____unnamed_____8____unnamed____", null ],
    [ "Stream", null, [
      [ "BLEStream", "class_b_l_e_stream.html", null ],
      [ "EthernetClientStream", "class_ethernet_client_stream.html", null ],
      [ "WiFiStream", "class_wi_fi_stream.html", [
        [ "WiFiClientStream", "class_wi_fi_client_stream.html", null ],
        [ "WiFiServerStream", "class_wi_fi_server_stream.html", null ]
      ] ]
    ] ],
    [ "temperatureSettings", "_l_s_m9_d_s1___types_8h.html#structtemperature_settings", null ],
    [ "TinyGPSCustom", "class_tiny_g_p_s_custom.html", null ],
    [ "TinyGPSDate", "struct_tiny_g_p_s_date.html", null ],
    [ "TinyGPSDecimal", "struct_tiny_g_p_s_decimal.html", [
      [ "TinyGPSAltitude", "struct_tiny_g_p_s_altitude.html", null ],
      [ "TinyGPSCourse", "struct_tiny_g_p_s_course.html", null ],
      [ "TinyGPSSpeed", "struct_tiny_g_p_s_speed.html", null ]
    ] ],
    [ "TinyGPSInteger", "struct_tiny_g_p_s_integer.html", null ],
    [ "TinyGPSLocation", "struct_tiny_g_p_s_location.html", null ],
    [ "TinyGPSPlus", "class_tiny_g_p_s_plus.html", null ],
    [ "TinyGPSTime", "struct_tiny_g_p_s_time.html", null ],
    [ "ZeroRegOptions", "_zero_regs_8h.html#struct_zero_reg_options", null ]
];