Weather_Balloon/library/SparkFun_MAX17043/examples/MAX17043_Simple.cpp File Reference
#include `SparkFunMAX17043/SparkFunMAX17043.h`
*
Functions
void setup ()
void loop ()
Variables
double voltage = 0
double soc = 0
bool alert
Function Documentation
void loop ()
Definition at line 59 of file MAX17043_Simple.cpp.
References alert, MAX17043::getAlert(), MAX17043::getSOC(), MAX17043::getVoltage(), lipo, soc, and voltage.
void setup ()
Definition at line 36 of file MAX17043_Simple.cpp.
References alert, MAX17043::begin(), lipo, MAX17043::quickStart(), MAX17043::setThreshold(), soc, and voltage.
Variable Documentation
bool alert
Definition at line 34 of file MAX17043_Simple.cpp.
Referenced by loop(), and setup().
double soc = 0
Definition at line 33 of file MAX17043_Simple.cpp.
Referenced by MAX17043::getSOC(), loop(), and setup().
double voltage = 0
Definition at line 32 of file MAX17043_Simple.cpp.
Referenced by loop(), and setup().