Weather_Balloon/library/RTClib-master/RTClib.h File Reference
Classes
class DateTime
class RTC_Millis
Functions
uint8_t bcd2bin (uint8_t val)
uint8_t bin2bcd (uint8_t val)
Function Documentation
uint8_t bcd2bin (uint8_t val)
Definition at line 180 of file RTClib.cpp.
Referenced by RTC_DS3231::enable32kHz(), RTC_DS1307::now(), RTC_DS3234::now(), and RTC_DS3231::now().
uint8_t bin2bcd (uint8_t val)
Definition at line 184 of file RTClib.cpp.
Referenced by RTC_DS1307::adjust(), RTC_DS3234::adjust(), and RTC_DS3231::adjust().