Weather_Balloon/library/Filters/RunningStatistics.cpp File Reference
#include `RunningStatistics.h`
*
#include `FloatDefine.h`
*
Functions
void testRunningStatistics ()
Function Documentation
void testRunningStatistics ()
Definition at line 58 of file RunningStatistics.cpp.
References RunningStatistics::input(), RunningStatistics::mean(), RunningStatistics::setInitialValue(), and RunningStatistics::sigma().