Weather_Balloon/library/Filters/RunningStatistics.h File Reference
#include `FilterOnePole.h`
*
Classes
struct RunningStatistics
Functions
void testRunningStatistics ()
Function Documentation
void testRunningStatistics ()
Definition at line 58 of file RunningStatistics.cpp.
References RunningStatistics::input(), RunningStatistics::mean(), RunningStatistics::setInitialValue(), and RunningStatistics::sigma().