Weather_Balloon/library/Time-master/Time.cpp File Reference
#include <WProgram.h>
*
#include `TimeLib.h`
*
Macros
#define LEAP_YEAR(Y) (((1970+Y)>0) && !((1970+Y)%4) && (((1970+Y)%100) || !((1970+Y)%400)))
Functions
void refreshCache (time_t t)
int hour ()
int hour (time_t t)
int hourFormat12 ()
int hourFormat12 (time_t t)
uint8_t isAM ()
uint8_t isAM (time_t t)
uint8_t isPM ()
uint8_t isPM (time_t t)
int minute ()
int minute (time_t t)
int second ()
int second (time_t t)
int day ()
int day (time_t t)
int weekday ()
int weekday (time_t t)
int month ()
int month (time_t t)
int year ()
int year (time_t t)
void breakTime (time_t timeInput, tmElements_t &tm)
time_t makeTime (tmElements_t &tm)
time_t now ()
void setTime (time_t t)
void setTime (int hr, int min, int sec, int dy, int mnth, int yr)
void adjustTime (long adjustment)
timeStatus_t timeStatus ()
void setSyncProvider (getExternalTime getTimeFunction)
void setSyncInterval (time_t interval)
Variables
getExternalTime getTimePtr
Macro Definition Documentation
#define LEAP_YEAR(Y) (((1970+Y)>0) && !((1970+Y)%4) && (((1970+Y)%100) || !((1970+Y)%400)))
Definition at line 147 of file Time.cpp.
Referenced by breakTime(), and makeTime().
Function Documentation
void adjustTime (long adjustment)
Definition at line 302 of file Time.cpp.
void breakTime (time_t timeInput, tmElements_t & tm)
Definition at line 151 of file Time.cpp.
References LEAP_YEAR, month(), and year().
Referenced by refreshCache().
int day ()
Definition at line 106 of file Time.cpp.
References now().
Referenced by DS3231::isAlarm2(), RTCZero::setAlarmDay(), DS3231::setDateTime(), RTCZero::setDay(), and TinyGPSDate::value().
int day (time_t t)
Definition at line 110 of file Time.cpp.
References refreshCache().
int hour ()
Definition at line 49 of file Time.cpp.
References now().
Referenced by DS3231::isAlarm2(), isPM(), DS3231::setDateTime(), and TinyGPSTime::value().
int hour (time_t t)
Definition at line 53 of file Time.cpp.
References refreshCache().
int hourFormat12 ()
Definition at line 58 of file Time.cpp.
References now().
int hourFormat12 (time_t t)
Definition at line 62 of file Time.cpp.
References refreshCache().
uint8_t isAM ()
Definition at line 72 of file Time.cpp.
References isPM(), and now().
uint8_t isAM (time_t t)
Definition at line 76 of file Time.cpp.
References isPM().
uint8_t isPM ()
Definition at line 80 of file Time.cpp.
References now().
Referenced by isAM().
uint8_t isPM (time_t t)
Definition at line 84 of file Time.cpp.
References hour().
time_t makeTime (tmElements_t & tm)
Definition at line 204 of file Time.cpp.
References i, and LEAP_YEAR.
Referenced by setTime().
int minute ()
Definition at line 88 of file Time.cpp.
References now().
Referenced by DS3231::setDateTime(), and TinyGPSTime::value().
int minute (time_t t)
Definition at line 92 of file Time.cpp.
References refreshCache().
int month ()
Definition at line 124 of file Time.cpp.
References now().
Referenced by breakTime(), DS3231::isAlarm2(), RTCZero::setAlarmMonth(), DS3231::setDateTime(), RTCZero::setMonth(), and TinyGPSDate::value().
int month (time_t t)
Definition at line 128 of file Time.cpp.
References refreshCache().
time_t now ()
Definition at line 250 of file Time.cpp.
References getTimePtr, and setTime().
Referenced by RTC_Millis::begin(), PID::Compute(), day(), hour(), hourFormat12(), FilterTwoPole::input(), isAM(), isPM(), minute(), month(), DallasTemperature::requestTemperaturesByAddress(), second(), setSyncProvider(), FilterOnePole::test(), FilterTwoPole::test(), FilterOnePoleCascade::test(), timeStatus(), weekday(), and year().
void refreshCache (time_t t)
Definition at line 42 of file Time.cpp.
References breakTime().
Referenced by day(), hour(), hourFormat12(), minute(), month(), second(), weekday(), and year().
int second ()
Definition at line 97 of file Time.cpp.
References now().
Referenced by DS3231::setDateTime(), and TinyGPSTime::value().
int second (time_t t)
Definition at line 101 of file Time.cpp.
References refreshCache().
void setSyncInterval (time_t interval)
Definition at line 318 of file Time.cpp.
void setSyncProvider (getExternalTime getTimeFunction)
Definition at line 312 of file Time.cpp.
References getTimePtr, and now().
void setTime (time_t t)
Definition at line 274 of file Time.cpp.
Referenced by now(), setTime(), and TinyGPSTime::TinyGPSTime().
void setTime (int hr, int min, int sec, int dy, int mnth, int yr)
Definition at line 286 of file Time.cpp.
References makeTime(), and setTime().
timeStatus_t timeStatus ()
Definition at line 307 of file Time.cpp.
References now().
int weekday ()
Definition at line 115 of file Time.cpp.
References now().
int weekday (time_t t)
Definition at line 119 of file Time.cpp.
References refreshCache().
int year ()
Definition at line 133 of file Time.cpp.
References now().
Referenced by breakTime(), DS3231::isAlarm2(), RTCZero::setAlarmYear(), DS3231::setDateTime(), RTCZero::setYear(), TinyGPSDate::value(), and TinyGPSDate::year().
int year (time_t t)
Definition at line 137 of file Time.cpp.
References refreshCache().
Variable Documentation
getExternalTime getTimePtr
Definition at line 242 of file Time.cpp.
Referenced by now(), and setSyncProvider().