Weather_Balloon/Weather_Balloon.cpp File Reference
#include <stdint.h>
*
#include <Wire.h>
*
#include <util/atomic.h>
*
#include <avr/cpufunc.h>
*
#include <avr/interrupt.h>
*
#include <avr/sleep.h>
*
#include <avr/power.h>
*
#include <avr/wdt.h>
*
#include `Adafruit_SI1145.h`
*
#include `OneWire.h`
*
#include `DallasTemperature.h`
*
#include `MAG3110.h`
*
#include <Adafruit_Sensor.h>
*
#include <Adafruit_ADXL345_U.h>
*
#include <MS5xxx.h>
*
#include `Adafruit_SHT31.h`
*
#include `Sd2Card.h`
*
#include `Adafruit_TSL2561_U.h`
*
#include `SparkFunMAX17043.h`
*
#include `SparkFunLSM9DS1.h`
*
#include `TinyGPS++.h`
*
#include `DS3231.h`
*
#include `PID_v1.h`
*
#include <EEPROM.h>
*
#include `EEPROM_anything.h`
*
Classes
struct data_struct
struct sd_data
struct eeprom_struct
struct data_struct.found
struct data_struct.temp
struct data_struct.pwm
struct data_struct.sht31
struct data_struct.battery
struct data_struct.ms5607
struct data_struct.tsl
struct data_struct.accel
struct data_struct.mag
struct data_struct.gyro
struct data_struct.geiger
struct data_struct.gps
struct data_struct.enabled
Macros
#define ONE_WIRE_BUS 4
#define UV_PIN A0
#define CO2_PIN A3
#define PIEZO_PIN A2
#define GREEN_LED 22
#define YELLOW_LED 23
#define RED_LED 24
#define MAIN_HEATER_PIN 45
#define GPS_HEATER_PIN 44
#define UV_HEATER_PIN 11
#define TSL2561_HEATER_PIN 46
#define CUSTOM_HEATER_PIN 12
#define SHT31_HEATER_PIN 5
#define GEIGER_PWR_PIN 39
#define SAMPLE_TIME 1000
#define DS18B20_RESOLUTION 11
#define ADXL345_CORRECTION 0.911265
#define LSM9DS1_M 0x1E
#define LSM9DS1_AG 0x6B
#define DECLINATION -8.58
#define PRINT_RAW
#define GPS_SBYTE_1 0xA0
#define GPS_SBYTE_2 0xA1
#define GPS_END_1 0x0D
#define GPS_END_2 0x0A
#define GPS_RESTART 0x01
#define GPS_CONFIG_NMEA 0x08
#define GPS_CONFIG_OUT 0x09
#define GPS_CONFIG_PWR 0x12
#define GPS_CONFIG_WAAS 0x37
#define GPS_ACK 0x83
#define GPS_NACK 0x84
#define GPS_PRECISION 2.5
Functions
void beep_piezo (unsigned long, unsigned long, unsigned int)
void configure_GPS_NMEA ()
void configure_GPS_WAAS ()
uint32_t find_sdcard_tail (const uint32_t, const uint32_t)
void flash_landing (uint16_t)
template<typename T , size_t N>
size_t countof (T(&array)[N])
int16_t sd_calc_crc (const uint8_t *src, const uint8_t block_size)
void configure_TSL2561 (void)
ISR (PCINT1_vect)
ISR (PCINT2_vect)
ISR (INT4_vect)
ISR (WDT_vect)
void configure_button ()
void configure_geiger ()
bool compare_buffers (uint8_t *first, uint8_t *second, uint16_t bytes)
void configure_ds18b20 ()
void configure_ms5607 ()
void configure_LSM9DS1 ()
void configure_sht31 ()
void print_found ()
void configure_sdcard ()
void configure_PID ()
void piezo_power (bool power)
void tsl2561_power (bool power)
void ms5607_power (bool power)
void sht31_power (bool power)
void geiger_power (bool power)
void sd_power (bool power)
void gps_power (bool power)
void ds18b20_power (bool power)
void dof_power (bool power)
void led_power (bool power)
void power_sensors (bool power)
void watchdog_sleep ()
void watchdog_reset_only ()
void disable_peripherals ()
void enter_sleep (void)
void location_alarm ()
void count_down_led ()
void setup ()
void read_GPS ()
void printAttitude (float ax, float ay, float az, float mx, float my, float mz)
void readSensors ()
uint8_t GPS_CRC (uint8_t *payload, uint16_t length)
void adjust_heaters ()
void check_battery ()
void heater_control ()
void print_sensors ()
void power_control ()
void reset_sdcard ()
uint8_t EEPROM_read (uint16_t uiAddress)
void EEPROM_update (uint16_t uiAddress, uint8_t ucData)
void read_configuration ()
void test_logging ()
void log_data ()
void read_sdcard ()
void queue_altitude (float altitude)
void queue_pressure (float pressure)
void check_launch ()
void check_decent ()
void check_landing ()
void configure_write ()
void check_alarms ()
void print_serial_help ()
void Atmosphere (const double alt, double &sigma, double &delta, double &theta)
void set_alt_threshold (float altitude, String entered)
void set_pressure_threshold (float pressure)
void set_launch_timeout (uint32_t timeout)
void set_location_timeout (uint32_t timeout)
void read_serial ()
void pet_watchdog ()
void loop ()
Variables
bool DEBUG = false
bool DEBUG_MORE = false
volatile uint16_t watchdog = 10
const double FT2METERS = 0.3048
const double KELVIN2RANKINE = 1.8
const double PSF2NSM = 47.880258
const double SCF2KCM = 515.379
const double TZERO = 288.15
const double PZERO = 101325.0
const double RHOZERO = 1.225
const double AZERO = 340.294
float hyster = 0.5
float over_ambient = 2
data_struct dataLog
xx xx xx xx xx xx xx xx xx
struct {
volatile uint16_t x_count
volatile uint16_t y_count
volatile uint16_t z_count = 0
} geiger
xx xx xx xx xx xx xx xx xx
struct {
uint8_t INTERNAL_ADDR [8] = {0x28, 0x70, 0x95, 0x22, 0x05, 0x00, 0x00, 0xA1}
uint8_t TSL2561_ADDR [8] = {0x28, 0x57, 0x8C, 0x22, 0x05, 0x00, 0x00, 0x1D}
uint8_t UV_ADDR [8] = {0x28, 0xFF, 0xB6, 0x50, 0x6A, 0x14, 0x03, 0xB9}
uint8_t GPS_ADDR [8] = {0x28, 0xFF, 0x4D, 0x7F, 0x6F, 0x14, 0x04, 0x33}
uint8_t MAIN_ADDR [8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
uint8_t EXTERNAL_ADDR [8] = {0x28, 0xFF, 0x8C, 0x54, 0x6F, 0x14, 0x04, 0x38}
uint8_t CUSTOM_ADDR [8] = {0x28, 0x1B, 0x46, 0x6E, 0x00, 0x00, 0x00, 0x4D}
bool main = false
bool internal = false
bool external = false
bool gps = false
bool tsl2561 = false
bool uv = false
bool custom = false
uint8_t num_found = 0
} temp_sensors
xx xx xx xx xx xx xx xx xx
struct {
float pressure_alarm = 82553
float altitude_alarm = 1800
bool launched = false
bool alarm = false
bool decent = false
uint16_t altitude_time = 120
uint32_t launch_time = 120
uint32_t location_time = 240
bool DEBUG = false
bool DEBUG_MORE = false
} configuration
xx xx xx xx xx xx xx xx xx
struct {
float pressure_alarm = 82553
float altitude_alarm = 1800
bool launched = false
bool alarm = false
bool decent = false
uint16_t altitude_time = 120
uint32_t launch_time = 120
uint32_t location_time = 240
bool DEBUG = false
bool DEBUG_MORE = false
} default_config
uint16_t count_at_altitude = 0
float pressure_hist [120]
float altitude_hist [120]
int16_t pressure_hist_head = 0
int16_t pressure_hist_tail = -1
int16_t altitude_hist_head = 0
int16_t altitude_hist_tail = -1
OneWire oneWire (ONE_WIRE_BUS)
MS5xxx ms5607 & Wire
Adafruit_SHT31 sht31 = Adafruit_SHT31()
Adafruit_TSL2561_Unified tsl = Adafruit_TSL2561_Unified(TSL2561_ADDR_FLOAT, 12345)
MAX17043 fuel_gauge
LSM9DS1 DOF
Sd2Card sdcard
DS3231 clock
RTCDateTime date_time
sd_data sdcard_data
eeprom_struct eeprom
TinyGPSPlus gps
TinyGPSCustom vdop (gps,`GPGSA`, 17)
xx xx xx xx xx xx xx xx xx
struct {
double temp
double pwm
double setpoint
double Kp = 176.47
double Ki = 7
double Kd = 1.75
} gps_vPID
xx xx xx xx xx xx xx xx xx
struct {
double temp
double pwm
double setpoint
double Kp = 176.47
double Ki = 7
double Kd = 1.75
} uv_vPID
xx xx xx xx xx xx xx xx xx
struct {
double temp
double pwm
double setpoint
double Kp = 176.47
double Ki = 7
double Kd = 1.75
} tsl_vPID
xx xx xx xx xx xx xx xx xx
struct {
double temp
double pwm
double setpoint
double Kp = 176.47
double Ki = 7
double Kd = 1.75
} sht_vPID
xx xx xx xx xx xx xx xx xx
struct {
double temp
double pwm
double setpoint
double Kp = 176.47
double Ki = 7
double Kd = 1.75
} custom_vPID
xx xx xx xx xx xx xx xx xx
struct {
double temp
double pwm
double setpoint
double Kp = 352.94
double Ki = 30
double Kd = 9
} main_vPID
bool Heat_Enable = false
bool set_clock = false
volatile bool reset_flag = false
Class Documentation
struct data_struct
Definition at line 158 of file Weather_Balloon.cpp.
Class Members
struct data_struct
accel
bool
alarm
struct data_struct
battery
struct data_struct
enabled
struct data_struct
found
struct data_struct
geiger
struct data_struct
gps
struct data_struct
gyro
uint8_t
heater_max
bool
launched
struct data_struct
mag
struct data_struct
ms5607
struct data_struct
pwm
struct data_struct
sht31
struct data_struct
temp
struct data_struct
tsl
uint32_t
unix_time
float
uv
struct sd_data
Definition at line 416 of file Weather_Balloon.cpp.
Class Members
uint32_t
blocks
uint8_t
buffer[512]
int16_t
crc
uint32_t
crc_errors
uint32_t
current_block
uint8_t
hold_buffer[512]
uint8_t
num_packed
uint32_t
write_errors
struct eeprom_struct
Definition at line 443 of file Weather_Balloon.cpp.
Class Members
uint16_t
address
uint8_t
queue_loc
struct data_struct.found
Definition at line 159 of file Weather_Balloon.cpp.
Class Members
bool
DS18B20
bool
GPS
bool
LSM9DS1
bool
MS5607
bool
SHT31
bool
TSL2561
bool
UV
struct data_struct.temp
Definition at line 182 of file Weather_Balloon.cpp.
Class Members
float
clock
float
custom
float
external
float
gps
float
internal
float
main
float
ms5607
float
sht31
float
tsl2561
float
uv
struct data_struct.pwm
Definition at line 196 of file Weather_Balloon.cpp.
Class Members
uint8_t
gps
uint8_t
main
uint8_t
sht31
uint8_t
tsl2561
uint8_t
uv
struct data_struct.sht31
Definition at line 200 of file Weather_Balloon.cpp.
Class Members
float
humidity
struct data_struct.battery
Definition at line 209 of file Weather_Balloon.cpp.
Class Members
float
soc
float
voltage
struct data_struct.ms5607
Definition at line 214 of file Weather_Balloon.cpp.
Class Members
double
pressure
struct data_struct.tsl
Definition at line 219 of file Weather_Balloon.cpp.
Class Members
uint16_t
broadband
uint16_t
ir
uint32_t
lux
struct data_struct.accel
Definition at line 225 of file Weather_Balloon.cpp.
Class Members
float
x
float
y
float
z
struct data_struct.mag
Definition at line 229 of file Weather_Balloon.cpp.
Class Members
float
x
float
y
float
z
struct data_struct.gyro
Definition at line 233 of file Weather_Balloon.cpp.
Class Members
float
x
float
y
float
z
struct data_struct.geiger
Definition at line 238 of file Weather_Balloon.cpp.
Class Members
uint16_t
x
uint16_t
y
uint16_t
z
struct data_struct.gps
Definition at line 247 of file Weather_Balloon.cpp.
Class Members
double
altitude
double
course
uint32_t
date
uint16_t
hdop
double
lat
double
lng
uint8_t
sats
double
speed
uint32_t
time
uint16_t
vdop
struct data_struct.enabled
Definition at line 272 of file Weather_Balloon.cpp.
Class Members
bool
DS18B20
bool
GPS
bool
LSM9DS1
bool
MS5607
bool
SHT31
bool
TSL2561
bool
UV
Macro Definition Documentation
#define ADXL345_CORRECTION 0.911265
Definition at line 143 of file Weather_Balloon.cpp.
#define CO2_PIN A3
Definition at line 87 of file Weather_Balloon.cpp.
#define CUSTOM_HEATER_PIN 12
Definition at line 112 of file Weather_Balloon.cpp.
Referenced by heater_control().
#define DECLINATION -8.58
Definition at line 153 of file Weather_Balloon.cpp.
Referenced by printAttitude().
#define DS18B20_RESOLUTION 11
Definition at line 140 of file Weather_Balloon.cpp.
Referenced by configure_ds18b20().
#define GEIGER_PWR_PIN 39
Definition at line 115 of file Weather_Balloon.cpp.
Referenced by geiger_power(), and power_sensors().
#define GPS_ACK 0x83
Definition at line 505 of file Weather_Balloon.cpp.
#define GPS_CONFIG_NMEA 0x08
Definition at line 500 of file Weather_Balloon.cpp.
Referenced by configure_GPS_NMEA().
#define GPS_CONFIG_OUT 0x09
Definition at line 501 of file Weather_Balloon.cpp.
#define GPS_CONFIG_PWR 0x12
Definition at line 502 of file Weather_Balloon.cpp.
#define GPS_CONFIG_WAAS 0x37
Definition at line 503 of file Weather_Balloon.cpp.
Referenced by configure_GPS_WAAS().
#define GPS_END_1 0x0D
Definition at line 495 of file Weather_Balloon.cpp.
Referenced by configure_GPS_NMEA(), and configure_GPS_WAAS().
#define GPS_END_2 0x0A
Definition at line 496 of file Weather_Balloon.cpp.
Referenced by configure_GPS_NMEA(), and configure_GPS_WAAS().
#define GPS_HEATER_PIN 44
Definition at line 109 of file Weather_Balloon.cpp.
Referenced by heater_control(), and power_sensors().
#define GPS_NACK 0x84
Definition at line 506 of file Weather_Balloon.cpp.
#define GPS_PRECISION 2.5
Definition at line 509 of file Weather_Balloon.cpp.
#define GPS_RESTART 0x01
Definition at line 499 of file Weather_Balloon.cpp.
#define GPS_SBYTE_1 0xA0
Definition at line 493 of file Weather_Balloon.cpp.
Referenced by configure_GPS_NMEA(), and configure_GPS_WAAS().
#define GPS_SBYTE_2 0xA1
Definition at line 494 of file Weather_Balloon.cpp.
Referenced by configure_GPS_NMEA(), and configure_GPS_WAAS().
#define GREEN_LED 22
Definition at line 92 of file Weather_Balloon.cpp.
Referenced by configure_sdcard(), count_down_led(), and led_power().
#define LSM9DS1_AG 0x6B
Definition at line 147 of file Weather_Balloon.cpp.
Referenced by configure_LSM9DS1().
#define LSM9DS1_M 0x1E
Definition at line 146 of file Weather_Balloon.cpp.
Referenced by configure_LSM9DS1().
#define MAIN_HEATER_PIN 45
Definition at line 108 of file Weather_Balloon.cpp.
Referenced by heater_control(), and power_sensors().
#define ONE_WIRE_BUS 4
Definition at line 81 of file Weather_Balloon.cpp.
#define PIEZO_PIN A2
Definition at line 90 of file Weather_Balloon.cpp.
Referenced by check_alarms(), location_alarm(), loop(), and setup().
#define PRINT_RAW
Definition at line 156 of file Weather_Balloon.cpp.
#define RED_LED 24
Definition at line 94 of file Weather_Balloon.cpp.
Referenced by configure_sdcard(), count_down_led(), and led_power().
#define SAMPLE_TIME 1000
Definition at line 124 of file Weather_Balloon.cpp.
Referenced by configure_PID().
#define SHT31_HEATER_PIN 5
Definition at line 113 of file Weather_Balloon.cpp.
Referenced by heater_control(), and power_sensors().
#define TSL2561_HEATER_PIN 46
Definition at line 111 of file Weather_Balloon.cpp.
Referenced by heater_control(), and power_sensors().
#define UV_HEATER_PIN 11
Definition at line 110 of file Weather_Balloon.cpp.
Referenced by heater_control(), and power_sensors().
#define UV_PIN A0
Definition at line 84 of file Weather_Balloon.cpp.
Referenced by readSensors(), and setup().
#define YELLOW_LED 23
Definition at line 93 of file Weather_Balloon.cpp.
Referenced by count_down_led(), led_power(), and read_GPS().
Function Documentation
void adjust_heaters ()
Definition at line 1846 of file Weather_Balloon.cpp.
void Atmosphere (const double alt, double & sigma, double & delta, double & theta)
Definition at line 3163 of file Weather_Balloon.cpp.
References i.
Referenced by set_alt_threshold().
void beep_piezo (unsigned long freq, unsigned long millisecs, unsigned int pin)
Definition at line 1432 of file Weather_Balloon.cpp.
References i.
Referenced by check_alarms(), location_alarm(), loop(), and setup().
void check_alarms ()
Definition at line 3103 of file Weather_Balloon.cpp.
References beep_piezo(), configuration, flash_landing(), led_power(), location_alarm(), PIEZO_PIN, piezo_power(), power_sensors(), watchdog, and watchdog_sleep().
Referenced by loop().
void check_battery ()
Definition at line 1852 of file Weather_Balloon.cpp.
References data_struct::battery, Heat_Enable, and watchdog.
Referenced by loop().
void check_decent ()
Definition at line 3043 of file Weather_Balloon.cpp.
References altitude_hist, altitude_hist_head, altitude_hist_tail, configuration, pressure_hist, pressure_hist_head, and pressure_hist_tail.
void check_landing ()
Definition at line 3063 of file Weather_Balloon.cpp.
References altitude_hist, configuration, i, pressure_hist, and watchdog.
Referenced by loop().
void check_launch ()
Definition at line 3000 of file Weather_Balloon.cpp.
References altitude_hist, configuration, i, pressure_hist, and watchdog.
Referenced by loop().
bool compare_buffers (uint8_t * first, uint8_t * second, uint16_t bytes)
Definition at line 748 of file Weather_Balloon.cpp.
References configuration, and i.
Referenced by configure_ds18b20().
void configure_button ()
Definition at line 688 of file Weather_Balloon.cpp.
Referenced by setup().
void configure_ds18b20 ()
Definition at line 770 of file Weather_Balloon.cpp.
References compare_buffers(), configuration, DS18B20_RESOLUTION, data_struct::enabled, data_struct::found, i, and temp_sensors.
Referenced by setup().
void configure_geiger ()
Definition at line 708 of file Weather_Balloon.cpp.
Referenced by setup().
void configure_GPS_NMEA ()
Definition at line 1772 of file Weather_Balloon.cpp.
References GPS_CONFIG_NMEA, GPS_CRC(), GPS_END_1, GPS_END_2, GPS_SBYTE_1, GPS_SBYTE_2, and i.
Referenced by setup().
void configure_GPS_WAAS ()
Definition at line 1822 of file Weather_Balloon.cpp.
References GPS_CONFIG_WAAS, GPS_CRC(), GPS_END_1, GPS_END_2, GPS_SBYTE_1, and GPS_SBYTE_2.
Referenced by setup().
void configure_LSM9DS1 ()
Definition at line 884 of file Weather_Balloon.cpp.
References deviceSettings::agAddress, LSM9DS1::begin(), LSM9DS1::calibrate(), LSM9DS1::calibrateMag(), deviceSettings::commInterface, IMUSettings::device, data_struct::enabled, data_struct::found, IMU_MODE_I2C, LSM9DS1_AG, LSM9DS1_M, deviceSettings::mAddress, and LSM9DS1::settings.
Referenced by setup().
void configure_ms5607 ()
Definition at line 868 of file Weather_Balloon.cpp.
References data_struct::enabled, and data_struct::found.
Referenced by setup().
void configure_PID ()
Definition at line 981 of file Weather_Balloon.cpp.
References MANUAL, and SAMPLE_TIME.
Referenced by setup().
void configure_sdcard ()
Definition at line 946 of file Weather_Balloon.cpp.
References sd_data::blocks, Sd2Card::cardSize(), configuration, sd_data::current_block, Sd2Card::errorCode(), find_sdcard_tail(), GREEN_LED, Sd2Card::init(), RED_LED, and SPI_HALF_SPEED.
Referenced by setup().
void configure_sht31 ()
Definition at line 909 of file Weather_Balloon.cpp.
References Adafruit_SHT31::begin(), data_struct::enabled, and data_struct::found.
Referenced by setup().
void configure_TSL2561 (void)
Definition at line 556 of file Weather_Balloon.cpp.
References Adafruit_TSL2561_Unified::begin(), Adafruit_TSL2561_Unified::enableAutoRange(), data_struct::enabled, data_struct::found, Adafruit_TSL2561_Unified::setIntegrationTime(), and TSL2561_INTEGRATIONTIME_101MS.
Referenced by setup().
void configure_write ()
Definition at line 3099 of file Weather_Balloon.cpp.
void count_down_led ()
Definition at line 1252 of file Weather_Balloon.cpp.
References GREEN_LED, led_power(), RED_LED, and YELLOW_LED.
Referenced by setup().
template<typename T , size_t N> size_t countof (T(&) array[N])
Definition at line 528 of file Weather_Balloon.cpp.
void disable_peripherals ()
Definition at line 1206 of file Weather_Balloon.cpp.
Referenced by location_alarm().
void dof_power (bool power)
Definition at line 1098 of file Weather_Balloon.cpp.
Referenced by power_sensors().
void ds18b20_power (bool power)
Definition at line 1086 of file Weather_Balloon.cpp.
Referenced by power_sensors().
uint8_t EEPROM_read (uint16_t uiAddress)
Definition at line 2233 of file Weather_Balloon.cpp.
Referenced by EEPROM_update().
void EEPROM_update (uint16_t uiAddress, uint8_t ucData)
Definition at line 2247 of file Weather_Balloon.cpp.
References EEPROM_read().
void enter_sleep (void)
Definition at line 1219 of file Weather_Balloon.cpp.
Referenced by location_alarm().
uint32_t find_sdcard_tail (const uint32_t first = 1, const uint32_t last = sdcard_data.blocks)
Definition at line 2278 of file Weather_Balloon.cpp.
References sd_data::buffer, configuration, sd_data::current_block, dataLog, i, and Sd2Card::readData().
Referenced by configure_sdcard().
void flash_landing (uint16_t time)
Definition at line 1422 of file Weather_Balloon.cpp.
Referenced by check_alarms(), location_alarm(), loop(), and setup().
void geiger_power (bool power)
Definition at line 1052 of file Weather_Balloon.cpp.
References GEIGER_PWR_PIN.
Referenced by power_sensors().
uint8_t GPS_CRC (uint8_t * payload, uint16_t length)
Definition at line 1754 of file Weather_Balloon.cpp.
References i.
Referenced by configure_GPS_NMEA(), and configure_GPS_WAAS().
void gps_power (bool power)
Definition at line 1074 of file Weather_Balloon.cpp.
Referenced by power_sensors().
void heater_control ()
Definition at line 1872 of file Weather_Balloon.cpp.
References AUTOMATIC, configuration, CUSTOM_HEATER_PIN, custom_vPID, data_struct::found, data_struct::gps, GPS_HEATER_PIN, gps_vPID, Heat_Enable, hyster, MAIN_HEATER_PIN, main_vPID, MANUAL, over_ambient, data_struct::sht31, SHT31_HEATER_PIN, sht_vPID, data_struct::temp, temp_sensors, TSL2561_HEATER_PIN, tsl_vPID, data_struct::uv, UV_HEATER_PIN, uv_vPID, and watchdog.
Referenced by loop().
ISR (PCINT1_vect)
Definition at line 582 of file Weather_Balloon.cpp.
References geiger.
ISR (PCINT2_vect)
Definition at line 612 of file Weather_Balloon.cpp.
References geiger.
ISR (INT4_vect)
Definition at line 637 of file Weather_Balloon.cpp.
References reset_flag.
ISR (WDT_vect)
Definition at line 683 of file Weather_Balloon.cpp.
void led_power (bool power)
Definition at line 1110 of file Weather_Balloon.cpp.
References GREEN_LED, RED_LED, and YELLOW_LED.
Referenced by check_alarms(), count_down_led(), power_sensors(), and setup().
void location_alarm ()
Definition at line 1235 of file Weather_Balloon.cpp.
References beep_piezo(), disable_peripherals(), enter_sleep(), flash_landing(), PIEZO_PIN, piezo_power(), and watchdog_sleep().
Referenced by check_alarms(), and setup().
void log_data ()
Definition at line 2413 of file Weather_Balloon.cpp.
References sd_data::blocks, sd_data::buffer, configuration, sd_data::crc_errors, sd_data::current_block, dataLog, Sd2Card::errorCode(), Sd2Card::errorData(), data_struct::geiger, geiger, sd_data::hold_buffer, i, sd_data::num_packed, Sd2Card::readBlock(), reset_sdcard(), sd_calc_crc(), test_logging(), watchdog, sd_data::write_errors, and Sd2Card::writeBlock().
Referenced by loop().
void loop ()
Definition at line 3330 of file Weather_Balloon.cpp.
References data_struct::alarm, beep_piezo(), check_alarms(), check_battery(), check_landing(), check_launch(), configuration, default_config, flash_landing(), data_struct::gps, gps_vPID, heater_control(), data_struct::launched, log_data(), main_vPID, data_struct::ms5607, pet_watchdog(), PIEZO_PIN, print_sensors(), data_struct::pwm, queue_altitude(), queue_pressure(), read_sdcard(), read_serial(), readSensors(), reset_flag, data_struct::sht31, sht_vPID, tsl_vPID, data_struct::uv, uv_vPID, and watchdog.
void ms5607_power (bool power)
Definition at line 1025 of file Weather_Balloon.cpp.
Referenced by power_sensors().
void pet_watchdog ()
Definition at line 3317 of file Weather_Balloon.cpp.
References watchdog.
Referenced by loop().
void piezo_power (bool power)
Definition at line 1000 of file Weather_Balloon.cpp.
Referenced by check_alarms(), location_alarm(), power_sensors(), and setup().
void power_control ()
Definition at line 2223 of file Weather_Balloon.cpp.
void power_sensors (bool power)
Definition at line 1126 of file Weather_Balloon.cpp.
References dof_power(), ds18b20_power(), geiger_power(), GEIGER_PWR_PIN, GPS_HEATER_PIN, gps_power(), led_power(), MAIN_HEATER_PIN, ms5607_power(), piezo_power(), sd_power(), SHT31_HEATER_PIN, sht31_power(), TSL2561_HEATER_PIN, tsl2561_power(), and UV_HEATER_PIN.
Referenced by check_alarms(), and setup().
void print_found ()
Definition at line 928 of file Weather_Balloon.cpp.
References data_struct::found, and temp_sensors.
Referenced by setup().
void print_sensors ()
Definition at line 2091 of file Weather_Balloon.cpp.
References data_struct::accel, data_struct::battery, RTCDateTime::day, TinyGPSPlus::failedChecksum(), data_struct::geiger, data_struct::gps, data_struct::gyro, RTCDateTime::hour, data_struct::mag, RTCDateTime::minute, RTCDateTime::month, data_struct::ms5607, RTCDateTime::second, data_struct::sht31, data_struct::temp, data_struct::tsl, RTCDateTime::unixtime, data_struct::uv, and RTCDateTime::year.
Referenced by loop(), and test_logging().
void print_serial_help ()
Definition at line 3140 of file Weather_Balloon.cpp.
Referenced by read_serial().
void printAttitude (float ax, float ay, float az, float mx, float my, float mz)
Definition at line 1566 of file Weather_Balloon.cpp.
References DECLINATION.
void queue_altitude (float altitude)
Definition at line 2840 of file Weather_Balloon.cpp.
References altitude_hist, altitude_hist_head, altitude_hist_tail, and watchdog.
Referenced by loop().
void queue_pressure (float pressure)
Definition at line 2920 of file Weather_Balloon.cpp.
References pressure_hist, pressure_hist_head, pressure_hist_tail, and watchdog.
Referenced by loop().
void read_configuration ()
Definition at line 2270 of file Weather_Balloon.cpp.
References configuration.
void read_GPS ()
Definition at line 1458 of file Weather_Balloon.cpp.
References TinyGPSDate::age(), TinyGPSTime::age(), TinyGPSDecimal::age(), TinyGPSPlus::altitude, configuration, TinyGPSPlus::course, TinyGPSPlus::date, TinyGPSDate::day(), TinyGPSCourse::deg(), TinyGPSPlus::encode(), data_struct::gps, TinyGPSPlus::hdop, TinyGPSTime::hour(), TinyGPSLocation::isValid(), TinyGPSDate::isValid(), TinyGPSTime::isValid(), TinyGPSDecimal::isValid(), TinyGPSInteger::isValid(), TinyGPSCustom::isValid(), TinyGPSLocation::lat(), TinyGPSLocation::lng(), TinyGPSPlus::location, TinyGPSAltitude::meters(), TinyGPSTime::minute(), TinyGPSDate::month(), TinyGPSSpeed::mps(), TinyGPSPlus::satellites, TinyGPSTime::second(), set_clock, DS3231::setDateTime(), TinyGPSPlus::speed, TinyGPSPlus::time, TinyGPSDate::value(), TinyGPSTime::value(), TinyGPSDecimal::value(), TinyGPSInteger::value(), TinyGPSCustom::value(), vdop, TinyGPSDate::year(), and YELLOW_LED.
Referenced by readSensors().
void read_sdcard ()
Definition at line 2653 of file Weather_Balloon.cpp.
References data_struct::accel, data_struct::alarm, data_struct::battery, sd_data::blocks, sd_data::buffer, sd_data::current_block, dataLog, data_struct::found, data_struct::geiger, data_struct::gps, data_struct::gyro, data_struct::heater_max, i, data_struct::launched, data_struct::mag, data_struct::ms5607, sd_data::num_packed, data_struct::pwm, Sd2Card::readBlock(), sd_calc_crc(), data_struct::sht31, data_struct::temp, data_struct::tsl, data_struct::unix_time, and data_struct::uv.
Referenced by loop(), and read_serial().
void read_serial ()
Definition at line 3242 of file Weather_Balloon.cpp.
References configuration, DEBUG, print_serial_help(), read_sdcard(), and set_alt_threshold().
Referenced by loop().
void readSensors ()
Definition at line 1596 of file Weather_Balloon.cpp.
References data_struct::accel, LSM9DS1::ax, LSM9DS1::ay, LSM9DS1::az, data_struct::battery, LSM9DS1::calcAccel(), LSM9DS1::calcGyro(), LSM9DS1::calcMag(), Adafruit_TSL2561_Unified::calculateLux(), configuration, DS3231::forceConversion(), data_struct::found, DS3231::getDateTime(), Adafruit_TSL2561_Unified::getLuminosity(), MAX17043::getSOC(), MAX17043::getVoltage(), data_struct::gps, LSM9DS1::gx, LSM9DS1::gy, data_struct::gyro, LSM9DS1::gz, data_struct::mag, data_struct::ms5607, LSM9DS1::mx, LSM9DS1::my, LSM9DS1::mz, read_GPS(), LSM9DS1::readAccel(), LSM9DS1::readGyro(), Adafruit_SHT31::readHumidity(), LSM9DS1::readMag(), Adafruit_SHT31::readTemperature(), DS3231::readTemperature(), data_struct::sht31, data_struct::temp, temp_sensors, data_struct::tsl, data_struct::unix_time, RTCDateTime::unixtime, data_struct::uv, UV_PIN, and watchdog.
Referenced by loop().
void reset_sdcard ()
Definition at line 2228 of file Weather_Balloon.cpp.
Referenced by log_data().
int16_t sd_calc_crc (const uint8_t * src, const uint8_t block_size)
Definition at line 536 of file Weather_Balloon.cpp.
References i.
Referenced by log_data(), and read_sdcard().
void sd_power (bool power)
Definition at line 1062 of file Weather_Balloon.cpp.
Referenced by power_sensors().
void set_alt_threshold (float altitude, String entered)
Definition at line 3207 of file Weather_Balloon.cpp.
References Atmosphere(), configuration, and PZERO.
Referenced by read_serial().
void set_launch_timeout (uint32_t timeout)
Definition at line 3235 of file Weather_Balloon.cpp.
void set_location_timeout (uint32_t timeout)
Definition at line 3238 of file Weather_Balloon.cpp.
void set_pressure_threshold (float pressure)
Definition at line 3231 of file Weather_Balloon.cpp.
void setup ()
Definition at line 1274 of file Weather_Balloon.cpp.
References beep_piezo(), MAX17043::begin(), DS3231::begin(), configuration, configure_button(), configure_ds18b20(), configure_geiger(), configure_GPS_NMEA(), configure_GPS_WAAS(), configure_LSM9DS1(), configure_ms5607(), configure_PID(), configure_sdcard(), configure_sht31(), configure_TSL2561(), count_down_led(), default_config, flash_landing(), Heat_Enable, led_power(), location_alarm(), PIEZO_PIN, piezo_power(), power_sensors(), print_found(), MAX17043::quickStart(), reset_flag, UV_PIN, watchdog, watchdog_reset_only(), and watchdog_sleep().
void sht31_power (bool power)
Definition at line 1038 of file Weather_Balloon.cpp.
Referenced by power_sensors().
void test_logging ()
Definition at line 2397 of file Weather_Balloon.cpp.
References sd_data::buffer, dataLog, i, and print_sensors().
Referenced by log_data().
void tsl2561_power (bool power)
Definition at line 1012 of file Weather_Balloon.cpp.
Referenced by power_sensors().
void watchdog_reset_only ()
Definition at line 1183 of file Weather_Balloon.cpp.
Referenced by setup().
void watchdog_sleep ()
Definition at line 1161 of file Weather_Balloon.cpp.
Referenced by check_alarms(), location_alarm(), and setup().
Variable Documentation
float altitude_hist[120]
Definition at line 375 of file Weather_Balloon.cpp.
Referenced by check_decent(), check_landing(), check_launch(), and queue_altitude().
int16_t altitude_hist_head = 0
Definition at line 380 of file Weather_Balloon.cpp.
Referenced by check_decent(), and queue_altitude().
int16_t altitude_hist_tail = -1
Definition at line 381 of file Weather_Balloon.cpp.
Referenced by check_decent(), and queue_altitude().
const double AZERO = 340.294
Definition at line 66 of file Weather_Balloon.cpp.
DS3231 clock
Definition at line 413 of file Weather_Balloon.cpp.
Referenced by Adafruit_ADXL345_Unified::Adafruit_ADXL345_Unified().
struct { ... } configuration
Referenced by check_alarms(), check_decent(), check_landing(), check_launch(), compare_buffers(), configure_ds18b20(), configure_sdcard(), find_sdcard_tail(), heater_control(), log_data(), loop(), read_configuration(), read_GPS(), read_serial(), readSensors(), set_alt_threshold(), and setup().
uint16_t count_at_altitude = 0
Definition at line 371 of file Weather_Balloon.cpp.
PID PID_custom & custom_vPID
Definition at line 490 of file Weather_Balloon.cpp.
Referenced by heater_control().
data_struct dataLog
Definition at line 290 of file Weather_Balloon.cpp.
Referenced by find_sdcard_tail(), log_data(), read_sdcard(), and test_logging().
RTCDateTime date_time
Definition at line 414 of file Weather_Balloon.cpp.
bool DEBUG = false
Definition at line 11 of file Weather_Balloon.cpp.
Referenced by read_serial().
bool DEBUG_MORE = false
Definition at line 12 of file Weather_Balloon.cpp.
struct { ... } default_config
Referenced by loop(), and setup().
LSM9DS1 DOF
Definition at line 409 of file Weather_Balloon.cpp.
eeprom_struct eeprom
Definition at line 451 of file Weather_Balloon.cpp.
const double FT2METERS = 0.3048
Definition at line 59 of file Weather_Balloon.cpp.
MAX17043 fuel_gauge
Definition at line 407 of file Weather_Balloon.cpp.
struct { ... } geiger
Referenced by ISR(), and log_data().
TinyGPSPlus gps
Definition at line 456 of file Weather_Balloon.cpp.
Referenced by TinyGPSCustom::TinyGPSCustom().
PID PID_gps & gps_vPID
Definition at line 486 of file Weather_Balloon.cpp.
Referenced by heater_control(), and loop().
bool Heat_Enable = false
Definition at line 519 of file Weather_Balloon.cpp.
Referenced by check_battery(), heater_control(), and setup().
float hyster = 0.5
Definition at line 119 of file Weather_Balloon.cpp.
Referenced by heater_control().
const double KELVIN2RANKINE = 1.8
Definition at line 60 of file Weather_Balloon.cpp.
PID PID_main & main_vPID
Definition at line 485 of file Weather_Balloon.cpp.
Referenced by heater_control(), and loop().
DallasTemperature DS18B20 & oneWire
Definition at line 394 of file Weather_Balloon.cpp.
float over_ambient = 2
Definition at line 122 of file Weather_Balloon.cpp.
Referenced by heater_control().
float pressure_hist[120]
Definition at line 374 of file Weather_Balloon.cpp.
Referenced by check_decent(), check_landing(), check_launch(), and queue_pressure().
int16_t pressure_hist_head = 0
Definition at line 378 of file Weather_Balloon.cpp.
Referenced by check_decent(), and queue_pressure().
int16_t pressure_hist_tail = -1
Definition at line 379 of file Weather_Balloon.cpp.
Referenced by check_decent(), and queue_pressure().
const double PSF2NSM = 47.880258
Definition at line 61 of file Weather_Balloon.cpp.
const double PZERO = 101325.0
Definition at line 64 of file Weather_Balloon.cpp.
Referenced by set_alt_threshold().
volatile bool reset_flag = false
Definition at line 524 of file Weather_Balloon.cpp.
Referenced by ISR(), loop(), and setup().
const double RHOZERO = 1.225
Definition at line 65 of file Weather_Balloon.cpp.
const double SCF2KCM = 515.379
Definition at line 62 of file Weather_Balloon.cpp.
Sd2Card sdcard
Definition at line 411 of file Weather_Balloon.cpp.
sd_data sdcard_data
Definition at line 441 of file Weather_Balloon.cpp.
bool set_clock = false
Definition at line 522 of file Weather_Balloon.cpp.
Referenced by read_GPS().
Adafruit_SHT31 sht31 = Adafruit_SHT31()
Definition at line 403 of file Weather_Balloon.cpp.
PID PID_sht & sht_vPID
Definition at line 489 of file Weather_Balloon.cpp.
Referenced by heater_control(), and loop().
struct { ... } temp_sensors
Referenced by configure_ds18b20(), heater_control(), print_found(), and readSensors().
Adafruit_TSL2561_Unified tsl = Adafruit_TSL2561_Unified(TSL2561_ADDR_FLOAT, 12345)
Definition at line 405 of file Weather_Balloon.cpp.
PID PID_tsl & tsl_vPID
Definition at line 488 of file Weather_Balloon.cpp.
Referenced by heater_control(), and loop().
const double TZERO = 288.15
Definition at line 63 of file Weather_Balloon.cpp.
PID PID_uv & uv_vPID
Definition at line 487 of file Weather_Balloon.cpp.
Referenced by heater_control(), and loop().
TinyGPSCustom vdop(gps,`GPGSA`, 17)
Referenced by read_GPS().
volatile uint16_t watchdog = 10
Definition at line 13 of file Weather_Balloon.cpp.
Referenced by check_alarms(), check_battery(), check_landing(), check_launch(), heater_control(), log_data(), loop(), pet_watchdog(), queue_altitude(), queue_pressure(), readSensors(), and setup().
MS5xxx ms5607& Wire
Definition at line 400 of file Weather_Balloon.cpp.
Referenced by RTC_DS1307::adjust(), RTC_DS3231::adjust(), RTC_DS3231::BBSQWEnable(), MAX17043::begin(), Adafruit_SHT31::begin(), DS3231::begin(), Adafruit_ADXL345_Unified::begin(), Adafruit_SI1145::begin(), Adafruit_TSL2561_Unified::begin(), MAG3110::config(), RTC_DS3231::enable32kHz(), RTC_DS3231::forceTempConv(), DS3231::getAlarm1(), DS3231::getAlarm2(), DS3231::getAlarmType1(), DS3231::getAlarmType2(), RTC_DS3231::getControlRegisterData(), DS3231::getDateTime(), RTC_DS3231::getTempAsFloat(), RTC_DS3231::getTempAsWord(), LSM9DS1::I2CreadByte(), LSM9DS1::I2CreadBytes(), LSM9DS1::I2CwriteByte(), LSM9DS1::initI2C(), DS3231::isAlarm2(), RTC_DS1307::isrunning(), RTC_DS3231::isrunning(), RTC_DS1307::now(), RTC_DS3231::now(), Adafruit_ADXL345_Unified::read16(), MAG3110::read_x(), MAG3110::read_y(), MAG3110::read_z(), Adafruit_SHT31::readHumidity(), Adafruit_SI1145::readProx(), Adafruit_ADXL345_Unified::readRegister(), Adafruit_SHT31::readStatus(), DS3231::readTemperature(), DS3231::setAlarm1(), DS3231::setAlarm2(), MAX17043::setCompensation(), DS3231::setDateTime(), RTC_DS3231::SQWEnable(), RTC_DS3231::SQWFrequency(), and Adafruit_ADXL345_Unified::writeRegister().