Weather_Balloon/library/arduino-ZeroRegs/src/ZeroRegs.h File Reference
#include <Arduino.h>
*
Classes
struct ZeroRegOptions
Functions
void printZeroRegAC (ZeroRegOptions &opts)
void printZeroRegADC (ZeroRegOptions &opts)
void printZeroRegDAC (ZeroRegOptions &opts)
void printZeroRegDMAC (ZeroRegOptions &opts)
void printZeroRegDSU (ZeroRegOptions &opts)
void printZeroRegEIC (ZeroRegOptions &opts)
void printZeroRegEVSYS (ZeroRegOptions &opts)
void printZeroRegGCLK (ZeroRegOptions &opts)
void printZeroRegI2S (ZeroRegOptions &opts)
void printZeroRegMTB (ZeroRegOptions &opts)
void printZeroRegNVMCTRL (ZeroRegOptions &opts)
void printZeroRegPAC (ZeroRegOptions &opts)
void printZeroRegPM (ZeroRegOptions &opts)
void printZeroRegPORT (ZeroRegOptions &opts)
void printZeroRegRTC (ZeroRegOptions &opts)
void printZeroRegSBMATRIX (ZeroRegOptions &opts)
void printZeroRegSERCOM (ZeroRegOptions &opts, Sercom *sercom, uint8_t idx)
void printZeroRegSYSCTRL (ZeroRegOptions &opts)
void printZeroRegTC (ZeroRegOptions &opts, Tc *tc, uint8_t idx)
void printZeroRegTCC (ZeroRegOptions &opts, Tcc *tcc, uint8_t idx)
void printZeroRegUSB (ZeroRegOptions &opts)
void printZeroRegWDT (ZeroRegOptions &opts)
void printZeroRegs (ZeroRegOptions &opts)
Class Documentation
struct ZeroRegOptions
Definition at line 36 of file ZeroRegs.h.
Class Members
Stream &
ser
bool
showDisabled
Function Documentation
void printZeroRegAC (ZeroRegOptions & opts)
Definition at line 44 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegADC (ZeroRegOptions & opts)
Definition at line 49 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegDAC (ZeroRegOptions & opts)
Definition at line 54 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegDMAC (ZeroRegOptions & opts)
Definition at line 59 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegDSU (ZeroRegOptions & opts)
Definition at line 64 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegEIC (ZeroRegOptions & opts)
Definition at line 79 of file ZeroRegs.cpp.
References PRINTPAD2, printZeroRegEIC_SENSE(), ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegEVSYS (ZeroRegOptions & opts)
Definition at line 132 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTPAD2, ZeroRegOptions::ser, ZeroRegOptions::showDisabled, and WRITE8.
Referenced by printZeroRegs().
void printZeroRegGCLK (ZeroRegOptions & opts)
Definition at line 360 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTPAD2, PRINTSCALE, ZeroRegOptions::ser, ZeroRegOptions::showDisabled, and WRITE8.
Referenced by printZeroRegs().
void printZeroRegI2S (ZeroRegOptions & opts)
Definition at line 443 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegMTB (ZeroRegOptions & opts)
Definition at line 448 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegNVMCTRL (ZeroRegOptions & opts)
Definition at line 453 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, READADDR32, READFUSE, and ZeroRegOptions::ser.
Referenced by printZeroRegs().
void printZeroRegPAC (ZeroRegOptions & opts)
Definition at line 549 of file ZeroRegs.cpp.
References ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegPM (ZeroRegOptions & opts)
Definition at line 612 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTSCALE, and ZeroRegOptions::ser.
Referenced by printZeroRegs().
void printZeroRegPORT (ZeroRegOptions & opts)
Definition at line 774 of file ZeroRegs.cpp.
References Port_Pin::grp, Port_Pin::idx, Port_Pin::name, Port_Pin::pmux, port_pin_count, PRINTFLAG, PRINTHEX, PRINTPAD2, and ZeroRegOptions::ser.
Referenced by printZeroRegs().
void printZeroRegRTC (ZeroRegOptions & opts)
Definition at line 987 of file ZeroRegs.cpp.
References printZeroRegRTC_MODE0(), printZeroRegRTC_MODE1(), and printZeroRegRTC_MODE2().
Referenced by printZeroRegs().
void printZeroRegs (ZeroRegOptions & opts)
Definition at line 1589 of file ZeroRegs.cpp.
References printZeroRegAC(), printZeroRegADC(), printZeroRegDAC(), printZeroRegDMAC(), printZeroRegDSU(), printZeroRegEIC(), printZeroRegEVSYS(), printZeroRegGCLK(), printZeroRegI2S(), printZeroRegMTB(), printZeroRegNVMCTRL(), printZeroRegPAC(), printZeroRegPM(), printZeroRegPORT(), printZeroRegRTC(), printZeroRegSERCOM(), printZeroRegSYSCTRL(), printZeroRegTC(), printZeroRegTCC(), printZeroRegUSB(), and printZeroRegWDT().
void printZeroRegSBMATRIX (ZeroRegOptions & opts)
Definition at line 997 of file ZeroRegs.cpp.
References i, PRINTHEX, and ZeroRegOptions::ser.
void printZeroRegSERCOM (ZeroRegOptions & opts, Sercom * sercom, uint8_t idx)
Definition at line 1285 of file ZeroRegs.cpp.
References printZeroRegSERCOM_I2CM(), printZeroRegSERCOM_I2CS(), printZeroRegSERCOM_SPI(), printZeroRegSERCOM_USART(), ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegSYSCTRL (ZeroRegOptions & opts)
Definition at line 1308 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, PRINTSCALE, ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegTC (ZeroRegOptions & opts, Tc * tc, uint8_t idx)
Definition at line 1528 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegTCC (ZeroRegOptions & opts, Tcc * tcc, uint8_t idx)
Definition at line 1533 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegUSB (ZeroRegOptions & opts)
Definition at line 1538 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegWDT (ZeroRegOptions & opts)
Definition at line 1543 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTSCALE, READ2FUSES, READFUSE, ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().