Weather_Balloon/library/arduino-ZeroRegs/src/ZeroRegs.cpp File Reference
#include `ZeroRegs.h`
*
#include <samd.h>
*
Classes
struct Port_Pin
Macros
#define PRINTFLAG(x, y) do { if (x.bit.y) { opts.ser.print(` ` #y); } } while(0)
#define PRINTHEX(x) do { opts.ser.print(`0x`); opts.ser.print(x, HEX); } while(0)
#define PRINTSCALE(x) (opts.ser.print(1 << (x)))
#define PRINTPAD2(x) do { if (x < 10) { opts.ser.print(`0`); } opts.ser.print(x, DEC); } while(0)
#define WRITE8(x, y) *((uint8_t*)&(x)) = uint8_t(y)
#define READFUSE(x, y) ((*((uint32_t *) x##_FUSES_##y##_ADDR) & x##_FUSES_##y##_Msk) >> x##_FUSES_##y##_Pos)
#define READ2FUSES(x, y, o) (((*((uint32_t *) x##_FUSES_##y##_0_ADDR) & x##_FUSES_##y##_0_Msk) >> x##_FUSES_##y##_0_Pos) | (((*((uint32_t *) x##_FUSES_##y##_1_ADDR) & x##_FUSES_##y##_1_Msk) >> x##_FUSES_##y##_1_Pos) << o))
#define READADDR32(x) (*((uint32_t*)(x)))
Functions
void printZeroRegAC (ZeroRegOptions &opts)
void printZeroRegADC (ZeroRegOptions &opts)
void printZeroRegDAC (ZeroRegOptions &opts)
void printZeroRegDMAC (ZeroRegOptions &opts)
void printZeroRegDSU (ZeroRegOptions &opts)
void printZeroRegEIC_SENSE (ZeroRegOptions &opts, uint8_t sense)
void printZeroRegEIC (ZeroRegOptions &opts)
void printZeroRegEVSYS (ZeroRegOptions &opts)
void printZeroRegGCLK (ZeroRegOptions &opts)
void printZeroRegI2S (ZeroRegOptions &opts)
void printZeroRegMTB (ZeroRegOptions &opts)
void printZeroRegNVMCTRL (ZeroRegOptions &opts)
void printZeroRegPAC (ZeroRegOptions &opts)
void printZeroRegPM (ZeroRegOptions &opts)
void printZeroRegPORT (ZeroRegOptions &opts)
void printZeroRegRTC_MODE0 (ZeroRegOptions &opts, RtcMode0 &mode)
void printZeroRegRTC_MODE1 (ZeroRegOptions &opts, RtcMode1 &mode)
void printZeroRegRTC_MODE2 (ZeroRegOptions &opts, RtcMode2 &mode)
void printZeroRegRTC (ZeroRegOptions &opts)
void printZeroRegSBMATRIX (ZeroRegOptions &opts)
void printZeroRegSERCOM_I2CM (ZeroRegOptions &opts, SercomI2cm &i2cm)
void printZeroRegSERCOM_I2CS (ZeroRegOptions &opts, SercomI2cs &i2cs)
void printZeroRegSERCOM_SPI (ZeroRegOptions &opts, SercomSpi &spi, bool master)
void printZeroRegSERCOM_USART (ZeroRegOptions &opts, SercomUsart &usart)
void printZeroRegSERCOM (ZeroRegOptions &opts, Sercom *sercom, uint8_t idx)
void printZeroRegSYSCTRL (ZeroRegOptions &opts)
void printZeroRegTC (ZeroRegOptions &opts, Tc *tc, uint8_t idx)
void printZeroRegTCC (ZeroRegOptions &opts, Tcc *tcc, uint8_t idx)
void printZeroRegUSB (ZeroRegOptions &opts)
void printZeroRegWDT (ZeroRegOptions &opts)
void printZeroRegs (ZeroRegOptions &opts)
Variables
const Port_Pin port_pins []
const uint8_t port_pin_count = 43
Class Documentation
struct Port_Pin
Definition at line 713 of file ZeroRegs.cpp.
Class Members
uint8_t
grp
uint8_t
idx
const char *
name
const char *
pmux[8]
Macro Definition Documentation
#define PRINTFLAG(x, y) do { if (x.bit.y) { opts.ser.print(` ` #y); } } while(0)
Definition at line 34 of file ZeroRegs.cpp.
Referenced by printZeroRegEVSYS(), printZeroRegGCLK(), printZeroRegNVMCTRL(), printZeroRegPM(), printZeroRegPORT(), printZeroRegRTC_MODE0(), printZeroRegRTC_MODE1(), printZeroRegRTC_MODE2(), printZeroRegSERCOM_I2CM(), printZeroRegSERCOM_I2CS(), printZeroRegSERCOM_SPI(), printZeroRegSERCOM_USART(), printZeroRegSYSCTRL(), and printZeroRegWDT().
#define PRINTHEX(x) do { opts.ser.print(`0x`); opts.ser.print(x, HEX); } while(0)
Definition at line 35 of file ZeroRegs.cpp.
Referenced by printZeroRegNVMCTRL(), printZeroRegPORT(), printZeroRegRTC_MODE0(), printZeroRegRTC_MODE1(), printZeroRegRTC_MODE2(), printZeroRegSBMATRIX(), printZeroRegSERCOM_I2CM(), printZeroRegSERCOM_I2CS(), printZeroRegSERCOM_SPI(), printZeroRegSERCOM_USART(), and printZeroRegSYSCTRL().
#define PRINTPAD2(x) do { if (x < 10) { opts.ser.print(`0`); } opts.ser.print(x, DEC); } while(0)
Definition at line 37 of file ZeroRegs.cpp.
Referenced by printZeroRegEIC(), printZeroRegEVSYS(), printZeroRegGCLK(), printZeroRegPORT(), and printZeroRegRTC_MODE2().
#define PRINTSCALE(x) (opts.ser.print(1 << (x)))
Definition at line 36 of file ZeroRegs.cpp.
Referenced by printZeroRegGCLK(), printZeroRegPM(), printZeroRegRTC_MODE0(), printZeroRegRTC_MODE1(), printZeroRegRTC_MODE2(), printZeroRegSYSCTRL(), and printZeroRegWDT().
#define READ2FUSES(x, y, o) (((*((uint32_t *) x##_FUSES_##y##_0_ADDR) & x##_FUSES_##y##_0_Msk) >> x##_FUSES_##y##_0_Pos) | (((*((uint32_t *) x##_FUSES_##y##_1_ADDR) & x##_FUSES_##y##_1_Msk) >> x##_FUSES_##y##_1_Pos) << o))
Definition at line 40 of file ZeroRegs.cpp.
Referenced by printZeroRegWDT().
#define READADDR32(x) (*((uint32_t*)(x)))
Definition at line 41 of file ZeroRegs.cpp.
Referenced by printZeroRegNVMCTRL().
#define READFUSE(x, y) ((*((uint32_t *) x##_FUSES_##y##_ADDR) & x##_FUSES_##y##_Msk) >> x##_FUSES_##y##_Pos)
Definition at line 39 of file ZeroRegs.cpp.
Referenced by printZeroRegNVMCTRL(), and printZeroRegWDT().
#define WRITE8(x, y) *((uint8_t*)&(x)) = uint8_t(y)
Definition at line 38 of file ZeroRegs.cpp.
Referenced by printZeroRegEVSYS(), and printZeroRegGCLK().
Function Documentation
void printZeroRegAC (ZeroRegOptions & opts)
Definition at line 44 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegADC (ZeroRegOptions & opts)
Definition at line 49 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegDAC (ZeroRegOptions & opts)
Definition at line 54 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegDMAC (ZeroRegOptions & opts)
Definition at line 59 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegDSU (ZeroRegOptions & opts)
Definition at line 64 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegEIC (ZeroRegOptions & opts)
Definition at line 79 of file ZeroRegs.cpp.
References PRINTPAD2, printZeroRegEIC_SENSE(), ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegEIC_SENSE (ZeroRegOptions & opts, uint8_t sense)
Definition at line 69 of file ZeroRegs.cpp.
References ZeroRegOptions::ser.
Referenced by printZeroRegEIC().
void printZeroRegEVSYS (ZeroRegOptions & opts)
Definition at line 132 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTPAD2, ZeroRegOptions::ser, ZeroRegOptions::showDisabled, and WRITE8.
Referenced by printZeroRegs().
void printZeroRegGCLK (ZeroRegOptions & opts)
Definition at line 360 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTPAD2, PRINTSCALE, ZeroRegOptions::ser, ZeroRegOptions::showDisabled, and WRITE8.
Referenced by printZeroRegs().
void printZeroRegI2S (ZeroRegOptions & opts)
Definition at line 443 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegMTB (ZeroRegOptions & opts)
Definition at line 448 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegNVMCTRL (ZeroRegOptions & opts)
Definition at line 453 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, READADDR32, READFUSE, and ZeroRegOptions::ser.
Referenced by printZeroRegs().
void printZeroRegPAC (ZeroRegOptions & opts)
Definition at line 549 of file ZeroRegs.cpp.
References ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegPM (ZeroRegOptions & opts)
Definition at line 612 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTSCALE, and ZeroRegOptions::ser.
Referenced by printZeroRegs().
void printZeroRegPORT (ZeroRegOptions & opts)
Definition at line 774 of file ZeroRegs.cpp.
References Port_Pin::grp, Port_Pin::idx, Port_Pin::name, Port_Pin::pmux, port_pin_count, PRINTFLAG, PRINTHEX, PRINTPAD2, and ZeroRegOptions::ser.
Referenced by printZeroRegs().
void printZeroRegRTC (ZeroRegOptions & opts)
Definition at line 987 of file ZeroRegs.cpp.
References printZeroRegRTC_MODE0(), printZeroRegRTC_MODE1(), and printZeroRegRTC_MODE2().
Referenced by printZeroRegs().
void printZeroRegRTC_MODE0 (ZeroRegOptions & opts, RtcMode0 & mode)
Definition at line 814 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, PRINTSCALE, ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegRTC().
void printZeroRegRTC_MODE1 (ZeroRegOptions & opts, RtcMode1 & mode)
Definition at line 861 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, PRINTSCALE, ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegRTC().
void printZeroRegRTC_MODE2 (ZeroRegOptions & opts, RtcMode2 & mode)
Definition at line 916 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, PRINTPAD2, PRINTSCALE, ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegRTC().
void printZeroRegs (ZeroRegOptions & opts)
Definition at line 1589 of file ZeroRegs.cpp.
References printZeroRegAC(), printZeroRegADC(), printZeroRegDAC(), printZeroRegDMAC(), printZeroRegDSU(), printZeroRegEIC(), printZeroRegEVSYS(), printZeroRegGCLK(), printZeroRegI2S(), printZeroRegMTB(), printZeroRegNVMCTRL(), printZeroRegPAC(), printZeroRegPM(), printZeroRegPORT(), printZeroRegRTC(), printZeroRegSERCOM(), printZeroRegSYSCTRL(), printZeroRegTC(), printZeroRegTCC(), printZeroRegUSB(), and printZeroRegWDT().
void printZeroRegSBMATRIX (ZeroRegOptions & opts)
Definition at line 997 of file ZeroRegs.cpp.
References i, PRINTHEX, and ZeroRegOptions::ser.
void printZeroRegSERCOM (ZeroRegOptions & opts, Sercom * sercom, uint8_t idx)
Definition at line 1285 of file ZeroRegs.cpp.
References printZeroRegSERCOM_I2CM(), printZeroRegSERCOM_I2CS(), printZeroRegSERCOM_SPI(), printZeroRegSERCOM_USART(), ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegSERCOM_I2CM (ZeroRegOptions & opts, SercomI2cm & i2cm)
Definition at line 1020 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, and ZeroRegOptions::ser.
Referenced by printZeroRegSERCOM().
void printZeroRegSERCOM_I2CS (ZeroRegOptions & opts, SercomI2cs & i2cs)
Definition at line 1071 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, and ZeroRegOptions::ser.
Referenced by printZeroRegSERCOM().
void printZeroRegSERCOM_SPI (ZeroRegOptions & opts, SercomSpi & spi, bool master)
Definition at line 1123 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, and ZeroRegOptions::ser.
Referenced by printZeroRegSERCOM().
void printZeroRegSERCOM_USART (ZeroRegOptions & opts, SercomUsart & usart)
Definition at line 1204 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, and ZeroRegOptions::ser.
Referenced by printZeroRegSERCOM().
void printZeroRegSYSCTRL (ZeroRegOptions & opts)
Definition at line 1308 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTHEX, PRINTSCALE, ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
void printZeroRegTC (ZeroRegOptions & opts, Tc * tc, uint8_t idx)
Definition at line 1528 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegTCC (ZeroRegOptions & opts, Tcc * tcc, uint8_t idx)
Definition at line 1533 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegUSB (ZeroRegOptions & opts)
Definition at line 1538 of file ZeroRegs.cpp.
Referenced by printZeroRegs().
void printZeroRegWDT (ZeroRegOptions & opts)
Definition at line 1543 of file ZeroRegs.cpp.
References PRINTFLAG, PRINTSCALE, READ2FUSES, READFUSE, ZeroRegOptions::ser, and ZeroRegOptions::showDisabled.
Referenced by printZeroRegs().
Variable Documentation
const uint8_t port_pin_count = 43
Definition at line 773 of file ZeroRegs.cpp.
Referenced by printZeroRegPORT().
const Port_Pin port_pins[]
Definition at line 719 of file ZeroRegs.cpp.