DateTime Class Reference
#include <RTClib.h>
Public Member Functions
DateTime (uint32_t t=0)
DateTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour=0, uint8_t min=0, uint8_t sec=0)
DateTime (const char *date, const char *time)
uint16_t year () const
uint8_t month () const
uint8_t day () const
uint8_t hour () const
uint8_t minute () const
uint8_t second () const
uint8_t dayOfWeek () const
long secondstime () const
uint32_t unixtime (void) const
char * toString (char *buf, int maxlen) const
void operator+= (uint32_t)
Protected Attributes
uint8_t yOff
uint8_t m
uint8_t d
uint8_t hh
uint8_t mm
uint8_t ss
Detailed Description
Definition at line 8 of file RTClib.h.
Constructor & Destructor Documentation
DateTime::DateTime (uint32_t t = 0)
Definition at line 46 of file RTClib.cpp.
References d, hh, m, mm, pgm_read_byte, SECONDS_FROM_1970_TO_2000, ss, and yOff.
Referenced by operator+=(), and RTC_Millis::RTC_Millis().
DateTime::DateTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour = 0, uint8_t min = 0, uint8_t sec = 0)
Definition at line 76 of file RTClib.cpp.
References d, hh, m, mm, ss, year(), and yOff.
DateTime::DateTime (const char * date, const char * time)
Definition at line 99 of file RTClib.cpp.
References d, hh, m, mm, ss, and yOff.
Member Function Documentation
uint8_t DateTime::day () const [inline]
Definition at line 23 of file RTClib.h.
References d.
Referenced by RTC_DS1307::adjust(), RTC_DS3234::adjust(), RTC_DS3231::adjust(), and dayOfWeek().
uint8_t DateTime::dayOfWeek () const
Definition at line 142 of file RTClib.cpp.
References d, day(), m, and yOff.
Referenced by RTC_DS3234::adjust(), and second().
uint8_t DateTime::hour () const [inline]
Definition at line 27 of file RTClib.h.
References hh.
Referenced by RTC_DS1307::adjust(), RTC_DS3234::adjust(), and RTC_DS3231::adjust().
uint8_t DateTime::minute () const [inline]
Definition at line 31 of file RTClib.h.
References mm.
Referenced by RTC_DS1307::adjust(), RTC_DS3234::adjust(), and RTC_DS3231::adjust().
uint8_t DateTime::month () const [inline]
Definition at line 19 of file RTClib.h.
References m.
Referenced by RTC_DS1307::adjust(), RTC_DS3234::adjust(), and RTC_DS3231::adjust().
void DateTime::operator+= (uint32_t additional)
Definition at line 174 of file RTClib.cpp.
References DateTime(), and unixtime().
Referenced by second().
uint8_t DateTime::second () const [inline]
Definition at line 35 of file RTClib.h.
References dayOfWeek(), operator+=(), secondstime(), ss, toString(), and unixtime().
Referenced by RTC_DS1307::adjust(), RTC_DS3234::adjust(), and RTC_DS3231::adjust().
long DateTime::secondstime () const
Referenced by second().
char * DateTime::toString (char * buf, int maxlen) const
Definition at line 161 of file RTClib.cpp.
References d, hh, m, mm, months, ss, and yOff.
Referenced by second().
uint32_t DateTime::unixtime (void) const
Definition at line 148 of file RTClib.cpp.
References d, hh, m, mm, SECONDS_FROM_1970_TO_2000, ss, and yOff.
Referenced by RTC_Millis::adjust(), operator+=(), and second().
uint16_t DateTime::year () const [inline]
Definition at line 15 of file RTClib.h.
References yOff.
Referenced by RTC_DS1307::adjust(), RTC_DS3234::adjust(), RTC_DS3231::adjust(), and DateTime().
Member Data Documentation
uint8_t DateTime::d [protected]
Definition at line 51 of file RTClib.h.
Referenced by DateTime(), day(), dayOfWeek(), toString(), and unixtime().
uint8_t DateTime::hh [protected]
Definition at line 51 of file RTClib.h.
Referenced by DateTime(), hour(), toString(), and unixtime().
uint8_t DateTime::m [protected]
Definition at line 51 of file RTClib.h.
Referenced by DateTime(), dayOfWeek(), month(), toString(), and unixtime().
uint8_t DateTime::mm [protected]
Definition at line 51 of file RTClib.h.
Referenced by DateTime(), minute(), toString(), and unixtime().
uint8_t DateTime::ss [protected]
Definition at line 51 of file RTClib.h.
Referenced by DateTime(), second(), toString(), and unixtime().
uint8_t DateTime::yOff [protected]
Definition at line 51 of file RTClib.h.
Referenced by DateTime(), dayOfWeek(), toString(), unixtime(), and year().
The documentation for this class was generated from the following files:
Weather_Balloon/library/RTClib-master/RTClib.h
Weather_Balloon/library/RTClib-master/RTClib.cpp