RTCZero Class Reference
#include <RTCZero.h>
Public Types
enum Alarm_Match : uint8_t {
*
MATCH_OFF = RTC_MODE2_MASK_SEL_OFF_Val,
MATCH_SS = RTC_MODE2_MASK_SEL_SS_Val,
MATCH_MMSS = RTC_MODE2_MASK_SEL_MMSS_Val,
MATCH_HHMMSS = RTC_MODE2_MASK_SEL_HHMMSS_Val,
*
MATCH_DHHMMSS = RTC_MODE2_MASK_SEL_DDHHMMSS_Val,
MATCH_MMDDHHMMSS = RTC_MODE2_MASK_SEL_MMDDHHMMSS_Val,
MATCH_YYMMDDHHMMSS = RTC_MODE2_MASK_SEL_YYMMDDHHMMSS_Val
 }
Public Member Functions
RTCZero ()
void begin (bool resetTime=false)
void enableAlarm (Alarm_Match match)
void disableAlarm ()
void attachInterrupt (voidFuncPtr callback)
void detachInterrupt ()
void standbyMode ()
uint8_t getSeconds ()
uint8_t getMinutes ()
uint8_t getHours ()
uint8_t getDay ()
uint8_t getMonth ()
uint8_t getYear ()
uint8_t getAlarmSeconds ()
uint8_t getAlarmMinutes ()
uint8_t getAlarmHours ()
uint8_t getAlarmDay ()
uint8_t getAlarmMonth ()
uint8_t getAlarmYear ()
void setSeconds (uint8_t seconds)
void setMinutes (uint8_t minutes)
void setHours (uint8_t hours)
void setTime (uint8_t hours, uint8_t minutes, uint8_t seconds)
void setDay (uint8_t day)
void setMonth (uint8_t month)
void setYear (uint8_t year)
void setDate (uint8_t day, uint8_t month, uint8_t year)
void setAlarmSeconds (uint8_t seconds)
void setAlarmMinutes (uint8_t minutes)
void setAlarmHours (uint8_t hours)
void setAlarmTime (uint8_t hours, uint8_t minutes, uint8_t seconds)
void setAlarmDay (uint8_t day)
void setAlarmMonth (uint8_t month)
void setAlarmYear (uint8_t year)
void setAlarmDate (uint8_t day, uint8_t month, uint8_t year)
uint32_t getEpoch ()
uint32_t getY2kEpoch ()
void setEpoch (uint32_t ts)
void setY2kEpoch (uint32_t ts)
Detailed Description
Definition at line 27 of file RTCZero.h.
Member Enumeration Documentation
enum RTCZero::Alarm_Match : uint8_t
Enumerator
MATCH_OFF
MATCH_SS
MATCH_MMSS
MATCH_HHMMSS
MATCH_DHHMMSS
MATCH_MMDDHHMMSS
MATCH_YYMMDDHHMMSS
Definition at line 30 of file RTCZero.h.
Constructor & Destructor Documentation
RTCZero::RTCZero ()
Definition at line 29 of file RTCZero.cpp.
Member Function Documentation
void RTCZero::attachInterrupt (voidFuncPtr callback)
Definition at line 131 of file RTCZero.cpp.
References RTC_callBack.
void RTCZero::begin (bool resetTime = false)
Definition at line 34 of file RTCZero.cpp.
References MATCH_OFF.
void RTCZero::detachInterrupt ()
Definition at line 136 of file RTCZero.cpp.
References RTC_callBack.
void RTCZero::disableAlarm ()
Definition at line 122 of file RTCZero.cpp.
void RTCZero::enableAlarm (Alarm_Match match)
Definition at line 113 of file RTCZero.cpp.
uint8_t RTCZero::getAlarmDay ()
Definition at line 204 of file RTCZero.cpp.
uint8_t RTCZero::getAlarmHours ()
Definition at line 199 of file RTCZero.cpp.
uint8_t RTCZero::getAlarmMinutes ()
Definition at line 194 of file RTCZero.cpp.
uint8_t RTCZero::getAlarmMonth ()
Definition at line 209 of file RTCZero.cpp.
uint8_t RTCZero::getAlarmSeconds ()
Definition at line 189 of file RTCZero.cpp.
uint8_t RTCZero::getAlarmYear ()
Definition at line 214 of file RTCZero.cpp.
uint8_t RTCZero::getDay ()
Definition at line 171 of file RTCZero.cpp.
uint32_t RTCZero::getEpoch ()
Definition at line 367 of file RTCZero.cpp.
References EPOCH_TIME_YEAR_OFF.
Referenced by getY2kEpoch().
uint8_t RTCZero::getHours ()
Definition at line 165 of file RTCZero.cpp.
uint8_t RTCZero::getMinutes ()
Definition at line 159 of file RTCZero.cpp.
uint8_t RTCZero::getMonth ()
Definition at line 177 of file RTCZero.cpp.
uint8_t RTCZero::getSeconds ()
Definition at line 153 of file RTCZero.cpp.
uint32_t RTCZero::getY2kEpoch ()
Definition at line 388 of file RTCZero.cpp.
References EPOCH_TIME_OFF, and getEpoch().
uint8_t RTCZero::getYear ()
Definition at line 183 of file RTCZero.cpp.
void RTCZero::setAlarmDate (uint8_t day, uint8_t month, uint8_t year)
Definition at line 358 of file RTCZero.cpp.
References setAlarmDay(), setAlarmMonth(), and setAlarmYear().
void RTCZero::setAlarmDay (uint8_t day)
Definition at line 331 of file RTCZero.cpp.
References day().
Referenced by setAlarmDate().
void RTCZero::setAlarmHours (uint8_t hours)
Definition at line 313 of file RTCZero.cpp.
Referenced by setAlarmTime().
void RTCZero::setAlarmMinutes (uint8_t minutes)
Definition at line 304 of file RTCZero.cpp.
Referenced by setAlarmTime().
void RTCZero::setAlarmMonth (uint8_t month)
Definition at line 340 of file RTCZero.cpp.
References month().
Referenced by setAlarmDate().
void RTCZero::setAlarmSeconds (uint8_t seconds)
Definition at line 295 of file RTCZero.cpp.
Referenced by setAlarmTime().
void RTCZero::setAlarmTime (uint8_t hours, uint8_t minutes, uint8_t seconds)
Definition at line 322 of file RTCZero.cpp.
References setAlarmHours(), setAlarmMinutes(), and setAlarmSeconds().
void RTCZero::setAlarmYear (uint8_t year)
Definition at line 349 of file RTCZero.cpp.
References year().
Referenced by setAlarmDate().
void RTCZero::setDate (uint8_t day, uint8_t month, uint8_t year)
Definition at line 286 of file RTCZero.cpp.
References setDay(), setMonth(), and setYear().
void RTCZero::setDay (uint8_t day)
Definition at line 259 of file RTCZero.cpp.
References day().
Referenced by setDate().
void RTCZero::setEpoch (uint32_t ts)
Definition at line 393 of file RTCZero.cpp.
References EPOCH_TIME_OFF, and EPOCH_TIME_YEAR_OFF.
Referenced by setY2kEpoch().
void RTCZero::setHours (uint8_t hours)
Definition at line 241 of file RTCZero.cpp.
Referenced by setTime().
void RTCZero::setMinutes (uint8_t minutes)
Definition at line 232 of file RTCZero.cpp.
Referenced by setTime().
void RTCZero::setMonth (uint8_t month)
Definition at line 268 of file RTCZero.cpp.
References month().
Referenced by setDate().
void RTCZero::setSeconds (uint8_t seconds)
Definition at line 223 of file RTCZero.cpp.
Referenced by setTime().
void RTCZero::setTime (uint8_t hours, uint8_t minutes, uint8_t seconds)
Definition at line 250 of file RTCZero.cpp.
References setHours(), setMinutes(), and setSeconds().
void RTCZero::setY2kEpoch (uint32_t ts)
Definition at line 415 of file RTCZero.cpp.
References EPOCH_TIME_OFF, and setEpoch().
void RTCZero::setYear (uint8_t year)
Definition at line 277 of file RTCZero.cpp.
References year().
Referenced by setDate().
void RTCZero::standbyMode ()
Definition at line 141 of file RTCZero.cpp.
The documentation for this class was generated from the following files:
Weather_Balloon/library/RTCZero/src/RTCZero.h
Weather_Balloon/library/RTCZero/src/RTCZero.cpp