RTC_DS3234 Class Reference
#include <RTC_DS3234.h>
Public Member Functions
RTC_DS3234 (int _cs_pin)
uint8_t begin (void)
void adjust (const DateTime &dt)
uint8_t isrunning (void)
DateTime now ()
Protected Member Functions
void cs (int _value)
Detailed Description
Definition at line 10 of file RTC_DS3234.h.
Constructor & Destructor Documentation
RTC_DS3234::RTC_DS3234 (int _cs_pin) [inline]
Definition at line 13 of file RTC_DS3234.h.
References adjust(), begin(), cs(), isrunning(), and now().
Member Function Documentation
void RTC_DS3234::adjust (const DateTime & dt)
Definition at line 72 of file RTC_DS3234.cpp.
References bin2bcd(), cs(), DateTime::day(), DateTime::dayOfWeek(), DateTime::hour(), DateTime::minute(), DateTime::month(), DateTime::second(), SECONDS_W, and DateTime::year().
Referenced by RTC_DS3234().
uint8_t RTC_DS3234::begin (void)
Definition at line 30 of file RTC_DS3234.cpp.
References CONTROL_STATUS_W, CONTROL_W, and cs().
Referenced by RTC_DS3234().
void RTC_DS3234::cs (int _value) [protected]
Definition at line 57 of file RTC_DS3234.cpp.
Referenced by adjust(), begin(), isrunning(), now(), and RTC_DS3234().
uint8_t RTC_DS3234::isrunning (void)
Definition at line 63 of file RTC_DS3234.cpp.
References CONTROL_R, cs(), and OSF.
Referenced by RTC_DS3234().
DateTime RTC_DS3234::now ()
Definition at line 87 of file RTC_DS3234.cpp.
References bcd2bin(), cs(), and SECONDS_R.
Referenced by RTC_DS3234().
The documentation for this class was generated from the following files:
Weather_Balloon/library/RTClib-master/RTC_DS3234.h
Weather_Balloon/library/RTClib-master/RTC_DS3234.cpp