WiFiStream Class Reference
#include <WiFiStream.h>
Public Member Functions
WiFiStream (uint16_t server_port)
WiFiStream (IPAddress server_ip, uint16_t server_port)
void attach (hostConnectionCallbackFunction newFunction)
void config (IPAddress local_ip)
void config (IPAddress local_ip, IPAddress gateway, IPAddress subnet)
IPAddress getLocalIP ()
virtual bool maintain ()=0
virtual void stop ()=0
int begin (char *ssid)
int begin (char *ssid, uint8_t key_idx, const char *key)
int begin (char *ssid, const char *passphrase)
int available ()
void flush ()
int peek ()
int read ()
size_t write (uint8_t byte)
Protected Member Functions
virtual bool connect_client ()=0
Protected Attributes
WiFiClient _client
bool _connected = false
hostConnectionCallbackFunction _currentHostConnectionCallback
IPAddress _local_ip
IPAddress _subnet
IPAddress _gateway
IPAddress _remote_ip
uint16_t _port
uint8_t _key_idx
const char * _key = nullptr
const char * _passphrase = nullptr
char * _ssid = nullptr
Detailed Description
Definition at line 35 of file WiFiStream.h.
Constructor & Destructor Documentation
WiFiStream::WiFiStream (uint16_t server_port) [inline]
constructor for TCP server
Definition at line 61 of file WiFiStream.h.
WiFiStream::WiFiStream (IPAddress server_ip, uint16_t server_port) [inline]
constructor for TCP client
Definition at line 64 of file WiFiStream.h.
Member Function Documentation
void WiFiStream::attach (hostConnectionCallbackFunction newFunction) [inline]
Definition at line 66 of file WiFiStream.h.
int WiFiStream::available (void) [inline]
Definition at line 199 of file WiFiStream.h.
References connect_client().
int WiFiStream::begin (char * ssid) [inline]
initialize WiFi without security (open) and initiate client connection if WiFi connection is already established
Returns
WL_CONNECTED if WiFi connection is established
Definition at line 154 of file WiFiStream.h.
References ssid.
int WiFiStream::begin (char * ssid, uint8_t key_idx, const char * key) [inline]
initialize WiFi with WEP security and initiate client connection if WiFi connection is already established
Returns
WL_CONNECTED if WiFi connection is established
Definition at line 169 of file WiFiStream.h.
References ssid.
int WiFiStream::begin (char * ssid, const char * passphrase) [inline]
initialize WiFi with WPA-PSK security and initiate client connection if WiFi connection is already established
Returns
WL_CONNECTED if WiFi connection is established
Definition at line 185 of file WiFiStream.h.
References ssid.
void WiFiStream::config (IPAddress local_ip) [inline]
configure a static local IP address without defining the local network DHCP will be used as long as local IP address is not defined
Definition at line 77 of file WiFiStream.h.
References local_ip.
void WiFiStream::config (IPAddress local_ip, IPAddress gateway, IPAddress subnet) [inline]
configure a static local IP address DHCP will be used as long as local IP address is not defined
Definition at line 88 of file WiFiStream.h.
References local_ip.
virtual bool WiFiStream::connect_client () [protected], [pure virtual]
check if TCP client is connected
Returns
true if connected
Implemented in WiFiClientStream, and WiFiServerStream.
Referenced by available(), peek(), read(), and write().
void WiFiStream::flush (void) [inline]
Definition at line 204 of file WiFiStream.h.
IPAddress WiFiStream::getLocalIP () [inline]
Returns
local IP address
Definition at line 103 of file WiFiStream.h.
References maintain(), and stop().
virtual bool WiFiStream::maintain () [pure virtual]
maintain WiFi and TCP connection
Returns
true if WiFi and TCP connection are established
Implemented in WiFiClientStream, and WiFiServerStream.
Referenced by getLocalIP().
int WiFiStream::peek (void) [inline]
Definition at line 209 of file WiFiStream.h.
References connect_client().
int WiFiStream::read (void) [inline]
Definition at line 214 of file WiFiStream.h.
References connect_client().
virtual void WiFiStream::stop () [pure virtual]
close TCP client connection
Implemented in WiFiServerStream, and WiFiClientStream.
Referenced by getLocalIP().
size_t WiFiStream::write (uint8_t byte) [inline]
Definition at line 219 of file WiFiStream.h.
References connect_client().
Member Data Documentation
WiFiClient WiFiStream::_client [protected]
Definition at line 38 of file WiFiStream.h.
Referenced by WiFiServerStream::connect_client(), WiFiClientStream::connect_client(), WiFiClientStream::stop(), and WiFiServerStream::stop().
bool WiFiStream::_connected = false [protected]
Definition at line 39 of file WiFiStream.h.
Referenced by WiFiServerStream::connect_client(), WiFiClientStream::connect_client(), WiFiClientStream::stop(), and WiFiServerStream::stop().
hostConnectionCallbackFunction WiFiStream::_currentHostConnectionCallback [protected]
Definition at line 40 of file WiFiStream.h.
Referenced by WiFiServerStream::connect_client(), WiFiClientStream::connect_client(), WiFiClientStream::stop(), and WiFiServerStream::stop().
IPAddress WiFiStream::_gateway [protected]
Definition at line 45 of file WiFiStream.h.
const char* WiFiStream::_key = nullptr [protected]
Definition at line 49 of file WiFiStream.h.
uint8_t WiFiStream::_key_idx [protected]
Definition at line 48 of file WiFiStream.h.
IPAddress WiFiStream::_local_ip [protected]
Definition at line 43 of file WiFiStream.h.
const char* WiFiStream::_passphrase = nullptr [protected]
Definition at line 50 of file WiFiStream.h.
uint16_t WiFiStream::_port [protected]
Definition at line 47 of file WiFiStream.h.
Referenced by WiFiClientStream::connect_client(), and WiFiServerStream::maintain().
IPAddress WiFiStream::_remote_ip [protected]
Definition at line 46 of file WiFiStream.h.
Referenced by WiFiClientStream::connect_client().
char* WiFiStream::_ssid = nullptr [protected]
Definition at line 51 of file WiFiStream.h.
IPAddress WiFiStream::_subnet [protected]
Definition at line 44 of file WiFiStream.h.
The documentation for this class was generated from the following file:
Weather_Balloon/library/Firmata/utility/WiFiStream.h