SerialFirmata Class Reference
#include <SerialFirmata.h>
Public Member Functions
SerialFirmata ()
boolean handlePinMode (byte pin, int mode)
void handleCapability (byte pin)
boolean handleSysex (byte command, byte argc, byte *argv)
void update ()
void reset ()
void checkSerial ()
Detailed Description
Definition at line 142 of file SerialFirmata.h.
Constructor & Destructor Documentation
SerialFirmata::SerialFirmata ()
Definition at line 22 of file SerialFirmata.cpp.
Member Function Documentation
void SerialFirmata::checkSerial ()
Definition at line 284 of file SerialFirmata.cpp.
References END_SYSEX, Firmata, i, SERIAL_MESSAGE, SERIAL_REPLY, START_SYSEX, and FirmataClass::write().
Referenced by update().
void SerialFirmata::handleCapability (byte pin) [virtual]
Implements FirmataFeature.
Definition at line 44 of file SerialFirmata.cpp.
References Firmata, IS_PIN_SERIAL, PIN_MODE_SERIAL, and FirmataClass::write().
boolean SerialFirmata::handlePinMode (byte pin, int mode) [virtual]
Implements FirmataFeature.
Definition at line 34 of file SerialFirmata.cpp.
References Firmata, PIN_MODE_SERIAL, and FirmataClass::setPinMode().
boolean SerialFirmata::handleSysex (byte command, byte argc, byte * argv) [virtual]
Implements FirmataFeature.
Definition at line 52 of file SerialFirmata.cpp.
References Firmata, i, MAX_SERIAL_PORTS, PIN_MODE_SERIAL, FirmataClass::sendString(), SERIAL_CLOSE, SERIAL_CONFIG, SERIAL_FLUSH, SERIAL_LISTEN, SERIAL_MESSAGE, SERIAL_MODE_MASK, SERIAL_PORT_ID_MASK, SERIAL_READ, SERIAL_READ_CONTINUOUSLY, SERIAL_STOP_READING, SERIAL_WRITE, FirmataClass::setPinMode(), SW_SERIAL0, SW_SERIAL1, SW_SERIAL2, and SW_SERIAL3.
void SerialFirmata::reset (void) [virtual]
Implements FirmataFeature.
Definition at line 215 of file SerialFirmata.cpp.
References HW_SERIAL0, HW_SERIAL1, HW_SERIAL2, HW_SERIAL3, i, SERIAL_READ_ARR_LEN, SW_SERIAL0, SW_SERIAL1, SW_SERIAL2, and SW_SERIAL3.
void SerialFirmata::update ()
Definition at line 210 of file SerialFirmata.cpp.
References checkSerial().
The documentation for this class was generated from the following files:
Weather_Balloon/library/Firmata/utility/SerialFirmata.h
Weather_Balloon/library/Firmata/utility/SerialFirmata.cpp