Adafruit_Sensor Class Reference
#include <Adafruit_Sensor.h>
Public Member Functions
Adafruit_Sensor ()
virtual ~Adafruit_Sensor ()
virtual void enableAutoRange (bool enabled)
virtual bool getEvent (sensors_event_t *)=0
virtual void getSensor (sensor_t *)=0
Detailed Description
Definition at line 139 of file Adafruit_Sensor.h.
Constructor & Destructor Documentation
Adafruit_Sensor::Adafruit_Sensor () [inline]
Definition at line 142 of file Adafruit_Sensor.h.
virtual Adafruit_Sensor::~Adafruit_Sensor () [inline], [virtual]
Definition at line 143 of file Adafruit_Sensor.h.
Member Function Documentation
virtual void Adafruit_Sensor::enableAutoRange (bool enabled) [inline], [virtual]
Reimplemented in Adafruit_TSL2561_Unified.
Definition at line 146 of file Adafruit_Sensor.h.
References getEvent(), and getSensor().
virtual bool Adafruit_Sensor::getEvent (sensors_event_t *) [pure virtual]
Implemented in Adafruit_TSL2561_Unified, and Adafruit_ADXL345_Unified.
Referenced by enableAutoRange().
virtual void Adafruit_Sensor::getSensor (sensor_t *) [pure virtual]
Implemented in Adafruit_TSL2561_Unified, and Adafruit_ADXL345_Unified.
Referenced by enableAutoRange().
The documentation for this class was generated from the following file:
Weather_Balloon/library/Adafruit_Sensor-master/Adafruit_Sensor.h