LedControl Class Reference
#include <LedControl.h>
Public Member Functions
LedControl (int dataPin, int clkPin, int csPin, int numDevices=1)
int getDeviceCount ()
void shutdown (int addr, bool status)
void setScanLimit (int addr, int limit)
void setIntensity (int addr, int intensity)
void clearDisplay (int addr)
void setLed (int addr, int row, int col, boolean state)
void setRow (int addr, int row, byte value)
void setColumn (int addr, int col, byte value)
void setDigit (int addr, int digit, byte value, boolean dp)
void setChar (int addr, int digit, char value, boolean dp)
Detailed Description
Definition at line 199 of file LedControl.h.
Constructor & Destructor Documentation
LedControl::LedControl (int dataPin, int clkPin, int csPin, int numDevices = 1)
Definition at line 46 of file LedControl.cpp.
References clearDisplay(), i, OP_DECODEMODE, OP_DISPLAYTEST, setScanLimit(), and shutdown().
Member Function Documentation
void LedControl::clearDisplay (int addr)
Definition at line 99 of file LedControl.cpp.
References i.
Referenced by LedControl().
int LedControl::getDeviceCount (void)
Definition at line 72 of file LedControl.cpp.
void LedControl::setChar (int addr, int digit, char value, boolean dp)
Definition at line 171 of file LedControl.cpp.
References i, and pgm_read_byte_near.
void LedControl::setColumn (int addr, int col, byte value)
Definition at line 141 of file LedControl.cpp.
References setLed().
void LedControl::setDigit (int addr, int digit, byte value, boolean dp)
Definition at line 155 of file LedControl.cpp.
References pgm_read_byte_near.
void LedControl::setIntensity (int addr, int intensity)
Definition at line 92 of file LedControl.cpp.
References OP_INTENSITY.
void LedControl::setLed (int addr, int row, int col, boolean state)
Definition at line 111 of file LedControl.cpp.
Referenced by setColumn().
void LedControl::setRow (int addr, int row, byte value)
Definition at line 130 of file LedControl.cpp.
void LedControl::setScanLimit (int addr, int limit)
Definition at line 85 of file LedControl.cpp.
References OP_SCANLIMIT.
Referenced by LedControl().
void LedControl::shutdown (int addr, bool status)
Definition at line 76 of file LedControl.cpp.
References OP_SHUTDOWN.
Referenced by LedControl().
The documentation for this class was generated from the following files:
Weather_Balloon/library/LedControl-master/src/LedControl.h
Weather_Balloon/library/LedControl-master/src/LedControl.cpp