DS3231 Class Reference
#include <DS3231.h>
Public Member Functions
bool begin (void)
void setDateTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
void setDateTime (uint32_t t)
void setDateTime (const char *date, const char *time)
RTCDateTime getDateTime (void)
uint8_t isReady (void)
DS3231_sqw_t getOutput (void)
void setOutput (DS3231_sqw_t mode)
void enableOutput (bool enabled)
bool isOutput (void)
void enable32kHz (bool enabled)
bool is32kHz (void)
void forceConversion (void)
float readTemperature (void)
void setAlarm1 (uint8_t dydw, uint8_t hour, uint8_t minute, uint8_t second, DS3231_alarm1_t mode, bool armed=true)
RTCAlarmTime getAlarm1 (void)
DS3231_alarm1_t getAlarmType1 (void)
bool isAlarm1 (bool clear=true)
void armAlarm1 (bool armed)
bool isArmed1 (void)
void clearAlarm1 (void)
void setAlarm2 (uint8_t dydw, uint8_t hour, uint8_t minute, DS3231_alarm2_t mode, bool armed=true)
RTCAlarmTime getAlarm2 (void)
DS3231_alarm2_t getAlarmType2 (void)
bool isAlarm2 (bool clear=true)
void armAlarm2 (bool armed)
bool isArmed2 (void)
void clearAlarm2 (void)
void setBattery (bool timeBattery, bool squareBattery)
char * dateFormat (const char *dateFormat, RTCDateTime dt)
char * dateFormat (const char *dateFormat, RTCAlarmTime dt)
Detailed Description
Definition at line 89 of file DS3231.h.
Member Function Documentation
void DS3231::armAlarm1 (bool armed)
Definition at line 728 of file DS3231.cpp.
References DS3231_REG_CONTROL.
Referenced by setAlarm1().
void DS3231::armAlarm2 (bool armed)
Definition at line 894 of file DS3231.cpp.
References DS3231_REG_CONTROL.
Referenced by setAlarm2().
bool DS3231::begin (void)
Definition at line 33 of file DS3231.cpp.
References RTCDateTime::day, RTCDateTime::dayOfWeek, RTCDateTime::hour, RTCDateTime::minute, RTCDateTime::month, RTCDateTime::second, setBattery(), RTCDateTime::unixtime, Wire, and RTCDateTime::year.
Referenced by setup().
void DS3231::clearAlarm1 (void)
Definition at line 752 of file DS3231.cpp.
References DS3231_REG_STATUS.
Referenced by isAlarm1(), and setAlarm1().
void DS3231::clearAlarm2 (void)
Definition at line 920 of file DS3231.cpp.
References DS3231_REG_STATUS.
Referenced by isAlarm2(), and setAlarm2().
char * DS3231::dateFormat (const char * dateFormat, RTCDateTime dt)
Definition at line 171 of file DS3231.cpp.
References RTCDateTime::day, RTCDateTime::dayOfWeek, RTCDateTime::hour, RTCDateTime::minute, RTCDateTime::month, RTCDateTime::second, RTCDateTime::unixtime, and RTCDateTime::year.
char * DS3231::dateFormat (const char * dateFormat, RTCAlarmTime dt)
Definition at line 299 of file DS3231.cpp.
References RTCAlarmTime::day, RTCAlarmTime::hour, RTCAlarmTime::minute, and RTCAlarmTime::second.
void DS3231::enable32kHz (bool enabled)
Definition at line 501 of file DS3231.cpp.
References DS3231_REG_STATUS.
void DS3231::enableOutput (bool enabled)
Definition at line 428 of file DS3231.cpp.
References DS3231_REG_CONTROL.
void DS3231::forceConversion (void)
Definition at line 525 of file DS3231.cpp.
References DS3231_REG_CONTROL.
Referenced by readSensors().
RTCAlarmTime DS3231::getAlarm1 (void)
Definition at line 565 of file DS3231.cpp.
References RTCAlarmTime::day, DS3231_ADDRESS, DS3231_REG_ALARM_1, RTCAlarmTime::hour, i, RTCAlarmTime::minute, RTCAlarmTime::second, and Wire.
RTCAlarmTime DS3231::getAlarm2 (void)
Definition at line 762 of file DS3231.cpp.
References RTCAlarmTime::day, DS3231_ADDRESS, DS3231_REG_ALARM_2, RTCAlarmTime::hour, i, RTCAlarmTime::minute, RTCAlarmTime::second, and Wire.
DS3231_alarm1_t DS3231::getAlarmType1 (void)
Definition at line 601 of file DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_ALARM_1, i, and Wire.
DS3231_alarm2_t DS3231::getAlarmType2 (void)
Definition at line 798 of file DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_ALARM_2, i, and Wire.
RTCDateTime DS3231::getDateTime (void)
Definition at line 384 of file DS3231.cpp.
References RTCDateTime::day, RTCDateTime::dayOfWeek, DS3231_ADDRESS, DS3231_REG_TIME, RTCDateTime::hour, i, RTCDateTime::minute, RTCDateTime::month, RTCDateTime::second, RTCDateTime::unixtime, Wire, and RTCDateTime::year.
Referenced by readSensors().
DS3231_sqw_t DS3231::getOutput (void)
Definition at line 489 of file DS3231.cpp.
References DS3231_REG_CONTROL.
bool DS3231::is32kHz (void)
Definition at line 513 of file DS3231.cpp.
References DS3231_REG_STATUS.
bool DS3231::isAlarm1 (bool clear = true)
Definition at line 713 of file DS3231.cpp.
References clearAlarm1(), and DS3231_REG_STATUS.
bool DS3231::isAlarm2 (bool clear = true)
Definition at line 931 of file DS3231.cpp.
References clearAlarm2(), RTCDateTime::day, day(), DS3231_ADDRESS, DS3231_REG_STATUS, RTCDateTime::hour, hour(), i, RTCDateTime::minute, RTCDateTime::month, month(), pgm_read_byte, RTCDateTime::second, Wire, RTCDateTime::year, and year().
bool DS3231::isArmed1 (void)
Definition at line 744 of file DS3231.cpp.
References DS3231_REG_CONTROL.
bool DS3231::isArmed2 (void)
Definition at line 910 of file DS3231.cpp.
References DS3231_REG_CONTROL.
bool DS3231::isOutput (void)
Definition at line 465 of file DS3231.cpp.
References DS3231_REG_CONTROL.
uint8_t DS3231::isReady (void)
Definition at line 423 of file DS3231.cpp.
float DS3231::readTemperature (void)
Definition at line 538 of file DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_TEMPERATURE, and Wire.
Referenced by readSensors().
void DS3231::setAlarm1 (uint8_t dydw, uint8_t hour, uint8_t minute, uint8_t second, DS3231_alarm1_t mode, bool armed = true)
Definition at line 638 of file DS3231.cpp.
References armAlarm1(), clearAlarm1(), DS3231_ADDRESS, DS3231_EVERY_SECOND, DS3231_MATCH_DT_H_M_S, DS3231_MATCH_DY_H_M_S, DS3231_MATCH_H_M_S, DS3231_MATCH_M_S, DS3231_MATCH_S, DS3231_REG_ALARM_1, and Wire.
void DS3231::setAlarm2 (uint8_t dydw, uint8_t hour, uint8_t minute, DS3231_alarm2_t mode, bool armed = true)
Definition at line 834 of file DS3231.cpp.
References armAlarm2(), clearAlarm2(), DS3231_ADDRESS, DS3231_EVERY_MINUTE, DS3231_MATCH_DT_H_M, DS3231_MATCH_DY_H_M, DS3231_MATCH_H_M, DS3231_MATCH_M, DS3231_REG_ALARM_2, and Wire.
void DS3231::setBattery (bool timeBattery, bool squareBattery)
Definition at line 440 of file DS3231.cpp.
References DS3231_REG_CONTROL.
Referenced by begin().
void DS3231::setDateTime (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
Definition at line 51 of file DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_TIME, and Wire.
Referenced by read_GPS(), and setDateTime().
void DS3231::setDateTime (uint32_t t)
Definition at line 88 of file DS3231.cpp.
References day(), hour(), minute(), month(), pgm_read_byte, second(), setDateTime(), and year().
void DS3231::setDateTime (const char * date, const char * time)
Definition at line 140 of file DS3231.cpp.
References day(), hour(), minute(), month(), second(), setDateTime(), and year().
void DS3231::setOutput (DS3231_sqw_t mode)
Definition at line 477 of file DS3231.cpp.
References DS3231_REG_CONTROL.
The documentation for this class was generated from the following files:
Weather_Balloon/library/Arduino-DS3231-master/DS3231.h
Weather_Balloon/library/Arduino-DS3231-master/DS3231.cpp