DallasTemperature Class Reference
#include <DallasTemperature.h>
Public Member Functions
DallasTemperature ()
DallasTemperature (OneWire *)
void setOneWire (OneWire *)
void begin (void)
uint8_t getDeviceCount (void)
bool validAddress (const uint8_t *)
bool validFamily (const uint8_t *deviceAddress)
bool getAddress (uint8_t *, uint8_t)
bool isConnected (const uint8_t *)
bool isConnected (const uint8_t *, uint8_t *)
bool readScratchPad (const uint8_t *, uint8_t *)
void writeScratchPad (const uint8_t *, const uint8_t *)
bool readPowerSupply (const uint8_t *)
uint8_t getResolution ()
void setResolution (uint8_t)
uint8_t getResolution (const uint8_t *)
bool setResolution (const uint8_t *, uint8_t, bool skipGlobalBitResolutionCalculation=false)
void setWaitForConversion (bool)
bool getWaitForConversion (void)
void setCheckForConversion (bool)
bool getCheckForConversion (void)
void requestTemperatures (void)
bool requestTemperaturesByAddress (const uint8_t *)
bool requestTemperaturesByIndex (uint8_t)
int16_t getTemp (const uint8_t *)
float getTempC (const uint8_t *)
float getTempF (const uint8_t *)
float getTempCByIndex (uint8_t)
float getTempFByIndex (uint8_t)
bool isParasitePowerMode (void)
bool isConversionAvailable (const uint8_t *)
bool isConversionComplete (void)
void setUserData (const uint8_t *, int16_t)
void setUserDataByIndex (uint8_t, int16_t)
int16_t getUserData (const uint8_t *)
int16_t getUserDataByIndex (uint8_t)
Static Public Member Functions
static float toFahrenheit (float)
static float toCelsius (float)
static float rawToCelsius (int16_t)
static float rawToFahrenheit (int16_t)
Detailed Description
Definition at line 63 of file DallasTemperature.h.
Constructor & Destructor Documentation
DallasTemperature::DallasTemperature ()
Definition at line 17 of file DallasTemperature.cpp.
DallasTemperature::DallasTemperature (OneWire * _oneWire)
Definition at line 18 of file DallasTemperature.cpp.
References setOneWire().
Member Function Documentation
void DallasTemperature::begin (void)
Definition at line 51 of file DallasTemperature.cpp.
References getResolution(), readPowerSupply(), OneWire::reset_search(), OneWire::search(), and validAddress().
bool DallasTemperature::getAddress (uint8_t * deviceAddress, uint8_t index)
Definition at line 84 of file DallasTemperature.cpp.
References OneWire::reset_search(), and validAddress().
Referenced by getTempCByIndex(), getTempFByIndex(), getUserDataByIndex(), requestTemperaturesByIndex(), setResolution(), and setUserDataByIndex().
bool DallasTemperature::getCheckForConversion (void)
Definition at line 307 of file DallasTemperature.cpp.
uint8_t DallasTemperature::getDeviceCount (void)
Definition at line 73 of file DallasTemperature.cpp.
uint8_t DallasTemperature::getResolution ()
Definition at line 250 of file DallasTemperature.cpp.
Referenced by begin(), requestTemperaturesByAddress(), and setResolution().
uint8_t DallasTemperature::getResolution (const uint8_t * deviceAddress)
Definition at line 256 of file DallasTemperature.cpp.
References CONFIGURATION, DS18S20MODEL, isConnected(), TEMP_10_BIT, TEMP_11_BIT, TEMP_12_BIT, and TEMP_9_BIT.
int16_t DallasTemperature::getTemp (const uint8_t * deviceAddress)
Definition at line 481 of file DallasTemperature.cpp.
References DEVICE_DISCONNECTED_RAW, and isConnected().
Referenced by getTempC(), and getTempF().
float DallasTemperature::getTempC (const uint8_t * deviceAddress)
Definition at line 494 of file DallasTemperature.cpp.
References getTemp(), and rawToCelsius().
Referenced by getTempCByIndex().
float DallasTemperature::getTempCByIndex (uint8_t deviceIndex)
Definition at line 408 of file DallasTemperature.cpp.
References DEVICE_DISCONNECTED_C, getAddress(), and getTempC().
float DallasTemperature::getTempF (const uint8_t * deviceAddress)
Definition at line 503 of file DallasTemperature.cpp.
References getTemp(), and rawToFahrenheit().
Referenced by getTempFByIndex().
float DallasTemperature::getTempFByIndex (uint8_t deviceIndex)
Definition at line 420 of file DallasTemperature.cpp.
References COUNT_PER_C, COUNT_REMAIN, DEVICE_DISCONNECTED_F, DS18S20MODEL, getAddress(), getTempF(), TEMP_LSB, and TEMP_MSB.
int16_t DallasTemperature::getUserData (const uint8_t * deviceAddress)
Definition at line 532 of file DallasTemperature.cpp.
References HIGH_ALARM_TEMP, isConnected(), and LOW_ALARM_TEMP.
Referenced by getUserDataByIndex(), and setUserData().
int16_t DallasTemperature::getUserDataByIndex (uint8_t deviceIndex)
Definition at line 545 of file DallasTemperature.cpp.
References getAddress(), and getUserData().
bool DallasTemperature::getWaitForConversion (void)
Definition at line 294 of file DallasTemperature.cpp.
bool DallasTemperature::isConnected (const uint8_t * deviceAddress)
Definition at line 100 of file DallasTemperature.cpp.
Referenced by getResolution(), getTemp(), getUserData(), rawToFahrenheit(), setResolution(), and setUserData().
bool DallasTemperature::isConnected (const uint8_t * deviceAddress, uint8_t * scratchPad)
Definition at line 109 of file DallasTemperature.cpp.
References OneWire::crc8(), readScratchPad(), and SCRATCHPAD_CRC.
bool DallasTemperature::isConversionAvailable (const uint8_t * deviceAddress)
Definition at line 311 of file DallasTemperature.cpp.
References readScratchPad().
Referenced by requestTemperaturesByAddress().
bool DallasTemperature::isConversionComplete (void)
Definition at line 320 of file DallasTemperature.cpp.
References OneWire::read_bit().
bool DallasTemperature::isParasitePowerMode (void)
Definition at line 508 of file DallasTemperature.cpp.
float DallasTemperature::rawToCelsius (int16_t raw) [static]
Definition at line 571 of file DallasTemperature.cpp.
References DEVICE_DISCONNECTED_C, and DEVICE_DISCONNECTED_RAW.
Referenced by getTempC().
float DallasTemperature::rawToFahrenheit (int16_t raw) [static]
Definition at line 581 of file DallasTemperature.cpp.
References DEVICE_DISCONNECTED_C, DEVICE_DISCONNECTED_F, DEVICE_DISCONNECTED_RAW, HIGH_ALARM_TEMP, i, isConnected(), LOW_ALARM_TEMP, OneWire::read_bit(), OneWire::reset(), validAddress(), OneWire::write(), OneWire::write_bit(), and writeScratchPad().
Referenced by getTempF().
bool DallasTemperature::readPowerSupply (const uint8_t * deviceAddress)
Definition at line 169 of file DallasTemperature.cpp.
References OneWire::read_bit(), READPOWERSUPPLY, OneWire::reset(), OneWire::select(), and OneWire::write().
Referenced by begin().
bool DallasTemperature::readScratchPad (const uint8_t * deviceAddress, uint8_t * scratchPad)
Definition at line 115 of file DallasTemperature.cpp.
References i, OneWire::read(), READSCRATCH, OneWire::reset(), OneWire::select(), and OneWire::write().
Referenced by isConnected(), and isConversionAvailable().
void DallasTemperature::requestTemperatures (void)
Definition at line 327 of file DallasTemperature.cpp.
References OneWire::reset(), OneWire::skip(), STARTCONVO, and OneWire::write().
bool DallasTemperature::requestTemperaturesByAddress (const uint8_t * deviceAddress)
Definition at line 342 of file DallasTemperature.cpp.
References getResolution(), isConversionAvailable(), now(), OneWire::reset(), OneWire::select(), STARTCONVO, and OneWire::write().
Referenced by requestTemperaturesByIndex().
bool DallasTemperature::requestTemperaturesByIndex (uint8_t deviceIndex)
Definition at line 398 of file DallasTemperature.cpp.
References getAddress(), and requestTemperaturesByAddress().
void DallasTemperature::setCheckForConversion (bool flag)
Definition at line 302 of file DallasTemperature.cpp.
void DallasTemperature::setOneWire (OneWire * _oneWire)
Definition at line 39 of file DallasTemperature.cpp.
Referenced by DallasTemperature().
void DallasTemperature::setResolution (uint8_t newResolution)
Definition at line 184 of file DallasTemperature.cpp.
References getAddress(), and i.
bool DallasTemperature::setResolution (const uint8_t * deviceAddress, uint8_t newResolution, bool skipGlobalBitResolutionCalculation = false)
Definition at line 198 of file DallasTemperature.cpp.
References CONFIGURATION, DS18S20MODEL, getAddress(), getResolution(), i, isConnected(), TEMP_10_BIT, TEMP_11_BIT, TEMP_12_BIT, TEMP_9_BIT, and writeScratchPad().
void DallasTemperature::setUserData (const uint8_t * deviceAddress, int16_t data)
Definition at line 518 of file DallasTemperature.cpp.
References getUserData(), HIGH_ALARM_TEMP, isConnected(), LOW_ALARM_TEMP, and writeScratchPad().
Referenced by setUserDataByIndex().
void DallasTemperature::setUserDataByIndex (uint8_t deviceIndex, int16_t data)
Definition at line 552 of file DallasTemperature.cpp.
References getAddress(), and setUserData().
void DallasTemperature::setWaitForConversion (bool flag)
Definition at line 289 of file DallasTemperature.cpp.
float DallasTemperature::toCelsius (float fahrenheit) [static]
Definition at line 566 of file DallasTemperature.cpp.
float DallasTemperature::toFahrenheit (float celsius) [static]
Definition at line 561 of file DallasTemperature.cpp.
bool DallasTemperature::validAddress (const uint8_t * deviceAddress)
Definition at line 78 of file DallasTemperature.cpp.
References OneWire::crc8().
Referenced by begin(), getAddress(), and rawToFahrenheit().
bool DallasTemperature::validFamily (const uint8_t * deviceAddress)
Definition at line 27 of file DallasTemperature.cpp.
References DS1822MODEL, DS1825MODEL, DS18B20MODEL, and DS18S20MODEL.
void DallasTemperature::writeScratchPad (const uint8_t * deviceAddress, const uint8_t * scratchPad)
Definition at line 146 of file DallasTemperature.cpp.
References CONFIGURATION, COPYSCRATCH, DS18S20MODEL, HIGH_ALARM_TEMP, LOW_ALARM_TEMP, OneWire::reset(), OneWire::select(), OneWire::write(), and WRITESCRATCH.
Referenced by rawToFahrenheit(), setResolution(), and setUserData().
The documentation for this class was generated from the following files:
Weather_Balloon/library/Arduino-Temperature-Control-Library/DallasTemperature.h
Weather_Balloon/library/Arduino-Temperature-Control-Library/DallasTemperature.cpp