MAX17043 Class Reference
#include <SparkFunMAX17043.h>
Public Member Functions
MAX17043 ()
uint8_t begin (void)
uint8_t quickStart ()
float getVoltage ()
float getSOC ()
uint16_t getVersion ()
uint8_t getThreshold ()
uint8_t setThreshold (uint8_t percent)
uint8_t getAlert (bool clear=false)
uint8_t clearAlert ()
uint8_t sleep ()
uint8_t wake ()
uint8_t reset ()
uint16_t getConfigRegister ()
uint8_t getCompensation ()
uint8_t setCompensation (uint8_t newCompensation)
Detailed Description
Definition at line 28 of file SparkFunMAX17043.h.
Constructor & Destructor Documentation
MAX17043::MAX17043 ()
Definition at line 56 of file SparkFunMAX17043.cpp.
Member Function Documentation
uint8_t MAX17043::begin (void)
Definition at line 61 of file SparkFunMAX17043.cpp.
References Wire.
Referenced by setup().
uint8_t MAX17043::clearAlert ()
Definition at line 135 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
uint8_t MAX17043::getAlert (bool clear = false)
Definition at line 144 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
Referenced by loop().
uint8_t MAX17043::getCompensation ()
Definition at line 188 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
uint16_t MAX17043::getConfigRegister ()
Definition at line 195 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
float MAX17043::getSOC ()
Definition at line 88 of file SparkFunMAX17043.cpp.
References MAX17043_SOC, and soc.
Referenced by loop(), and readSensors().
uint8_t MAX17043::getThreshold ()
Definition at line 104 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
uint16_t MAX17043::getVersion ()
Definition at line 99 of file SparkFunMAX17043.cpp.
References MAX17043_VERSION.
float MAX17043::getVoltage ()
Definition at line 78 of file SparkFunMAX17043.cpp.
References MAX17043_VCELL.
Referenced by loop(), and readSensors().
uint8_t MAX17043::quickStart ()
Definition at line 67 of file SparkFunMAX17043.cpp.
References MAX17043_MODE, and MAX17043_MODE_QUICKSTART.
Referenced by setup().
uint8_t MAX17043::reset (void)
Definition at line 183 of file SparkFunMAX17043.cpp.
References MAX17043_COMMAND, and MAX17043_COMMAND_POR.
uint8_t MAX17043::setCompensation (uint8_t newCompensation)
Definition at line 200 of file SparkFunMAX17043.cpp.
References MAX17043_ADDRESS, MAX17043_CONFIG, and Wire.
uint8_t MAX17043::setThreshold (uint8_t percent)
Definition at line 116 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
Referenced by setup().
uint8_t MAX17043::sleep ()
Definition at line 161 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
uint8_t MAX17043::wake ()
Definition at line 172 of file SparkFunMAX17043.cpp.
References MAX17043_CONFIG.
The documentation for this class was generated from the following files:
Weather_Balloon/library/SparkFun_MAX17043/SparkFunMAX17043.h
Weather_Balloon/library/SparkFun_MAX17043/SparkFunMAX17043.cpp