RTC_DS1307 Class Reference
#include <RTC_DS1307.h>
Public Member Functions
uint8_t isrunning (void)
Static Public Member Functions
static uint8_t begin (void)
static void adjust (const DateTime &dt)
static DateTime now ()
Detailed Description
Definition at line 10 of file RTC_DS1307.h.
Member Function Documentation
void RTC_DS1307::adjust (const DateTime & dt) [static]
Definition at line 44 of file RTC_DS1307.cpp.
References bin2bcd(), DateTime::day(), DS1307_ADDRESS, DateTime::hour(), DateTime::minute(), DateTime::month(), DateTime::second(), Wire, and DateTime::year().
uint8_t RTC_DS1307::begin (void) [static]
Definition at line 28 of file RTC_DS1307.cpp.
uint8_t RTC_DS1307::isrunning (void)
Definition at line 33 of file RTC_DS1307.cpp.
References DS1307_ADDRESS, and Wire.
DateTime RTC_DS1307::now () [static]
Definition at line 59 of file RTC_DS1307.cpp.
References bcd2bin(), DS1307_ADDRESS, and Wire.
The documentation for this class was generated from the following files:
Weather_Balloon/library/RTClib-master/RTC_DS1307.h
Weather_Balloon/library/RTClib-master/RTC_DS1307.cpp