OneWire Class Reference
#include <OneWire.h>
Public Member Functions
OneWire (uint8_t pin)
uint8_t reset (void)
void select (const uint8_t rom[8])
void skip (void)
void write (uint8_t v, uint8_t power=0)
void write_bytes (const uint8_t *buf, uint16_t count, bool power=0)
uint8_t read (void)
void read_bytes (uint8_t *buf, uint16_t count)
void write_bit (uint8_t v)
uint8_t read_bit (void)
void depower (void)
void reset_search ()
void target_search (uint8_t family_code)
uint8_t search (uint8_t *newAddr, bool search_mode=true)
Static Public Member Functions
static uint8_t crc8 (const uint8_t *addr, uint8_t len)
static bool check_crc16 (const uint8_t *input, uint16_t len, const uint8_t *inverted_crc, uint16_t crc=0)
static uint16_t crc16 (const uint8_t *input, uint16_t len, uint16_t crc=0)
Detailed Description
Definition at line 254 of file OneWire.h.
Constructor & Destructor Documentation
OneWire::OneWire (uint8_t pin)
Definition at line 125 of file OneWire.cpp.
References PIN_TO_BASEREG, PIN_TO_BITMASK, and reset_search().
Member Function Documentation
bool OneWire::check_crc16 (const uint8_t * input, uint16_t len, const uint8_t * inverted_crc, uint16_t crc = 0) [static]
Definition at line 541 of file OneWire.cpp.
References crc16().
uint16_t OneWire::crc16 (const uint8_t * input, uint16_t len, uint16_t crc = 0) [static]
Definition at line 547 of file OneWire.cpp.
References i.
Referenced by check_crc16().
uint8_t OneWire::crc8 (const uint8_t * addr, uint8_t len) [static]
Definition at line 505 of file OneWire.cpp.
References i, and pgm_read_byte.
Referenced by DallasTemperature::isConnected(), and DallasTemperature::validAddress().
void OneWire::depower (void)
Definition at line 292 of file OneWire.cpp.
References DIRECT_MODE_INPUT.
uint8_t OneWire::read (void)
Definition at line 257 of file OneWire.cpp.
References read_bit().
Referenced by read_bytes(), and DallasTemperature::readScratchPad().
uint8_t OneWire::read_bit (void)
Definition at line 204 of file OneWire.cpp.
References DIRECT_MODE_INPUT, DIRECT_MODE_OUTPUT, DIRECT_READ, DIRECT_WRITE_LOW, IO_REG_ASM, and IO_REG_TYPE.
Referenced by DallasTemperature::isConversionComplete(), DallasTemperature::rawToFahrenheit(), read(), DallasTemperature::readPowerSupply(), and search().
void OneWire::read_bytes (uint8_t * buf, uint16_t count)
Definition at line 267 of file OneWire.cpp.
References i, and read().
uint8_t OneWire::reset (void)
Definition at line 142 of file OneWire.cpp.
References DIRECT_MODE_INPUT, DIRECT_MODE_OUTPUT, DIRECT_READ, DIRECT_WRITE_LOW, IO_REG_ASM, and IO_REG_TYPE.
Referenced by DallasTemperature::rawToFahrenheit(), DallasTemperature::readPowerSupply(), DallasTemperature::readScratchPad(), DallasTemperature::requestTemperatures(), DallasTemperature::requestTemperaturesByAddress(), search(), and DallasTemperature::writeScratchPad().
void OneWire::reset_search ()
Definition at line 305 of file OneWire.cpp.
References FALSE, and i.
Referenced by DallasTemperature::begin(), DallasTemperature::getAddress(), and OneWire().
uint8_t OneWire::search (uint8_t * newAddr, bool search_mode = true)
Definition at line 347 of file OneWire.cpp.
References FALSE, i, PROGMEM, read_bit(), reset(), TRUE, write(), and write_bit().
Referenced by DallasTemperature::begin().
void OneWire::select (const uint8_t rom[8])
Definition at line 275 of file OneWire.cpp.
References i, and write().
Referenced by DallasTemperature::readPowerSupply(), DallasTemperature::readScratchPad(), DallasTemperature::requestTemperaturesByAddress(), and DallasTemperature::writeScratchPad().
void OneWire::skip (void)
Definition at line 287 of file OneWire.cpp.
References write().
Referenced by DallasTemperature::requestTemperatures().
void OneWire::target_search (uint8_t family_code)
Definition at line 320 of file OneWire.cpp.
References FALSE, and i.
void OneWire::write (uint8_t v, uint8_t power = 0)
Definition at line 229 of file OneWire.cpp.
References DIRECT_MODE_INPUT, DIRECT_WRITE_LOW, and write_bit().
Referenced by DallasTemperature::rawToFahrenheit(), DallasTemperature::readPowerSupply(), DallasTemperature::readScratchPad(), DallasTemperature::requestTemperatures(), DallasTemperature::requestTemperaturesByAddress(), search(), select(), skip(), write_bytes(), and DallasTemperature::writeScratchPad().
void OneWire::write_bit (uint8_t v)
Definition at line 176 of file OneWire.cpp.
References DIRECT_MODE_OUTPUT, DIRECT_WRITE_HIGH, DIRECT_WRITE_LOW, IO_REG_ASM, and IO_REG_TYPE.
Referenced by DallasTemperature::rawToFahrenheit(), search(), and write().
void OneWire::write_bytes (const uint8_t * buf, uint16_t count, bool power = 0)
Definition at line 243 of file OneWire.cpp.
References DIRECT_MODE_INPUT, DIRECT_WRITE_LOW, i, and write().
The documentation for this class was generated from the following files:
Weather_Balloon/library/OneWire2/OneWire.h
Weather_Balloon/library/OneWire2/OneWire.cpp