RTC_Millis Class Reference
#include <RTClib.h>
Public Member Functions
void begin (const DateTime &dt)
void adjust (const DateTime &dt)
DateTime now ()
RTC_Millis (void)
Protected Attributes
long offset
Detailed Description
Definition at line 60 of file RTClib.h.
Constructor & Destructor Documentation
RTC_Millis::RTC_Millis (void) [inline]
Definition at line 69 of file RTClib.h.
References DateTime::DateTime().
Member Function Documentation
void RTC_Millis::adjust (const DateTime & dt)
Definition at line 192 of file RTClib.cpp.
References DateTime::unixtime().
void RTC_Millis::begin (const DateTime & dt) [inline]
Definition at line 63 of file RTClib.h.
References now().
DateTime RTC_Millis::now ()
Definition at line 197 of file RTClib.cpp.
Member Data Documentation
long RTC_Millis::offset [protected]
Definition at line 75 of file RTClib.h.
The documentation for this class was generated from the following files:
Weather_Balloon/library/RTClib-master/RTClib.h
Weather_Balloon/library/RTClib-master/RTClib.cpp