Adafruit_TSL2561_Unified Class Reference
#include <Adafruit_TSL2561_U.h>
Public Member Functions
Adafruit_TSL2561_Unified (uint8_t addr, int32_t sensorID=-1)
boolean begin (void)
void enableAutoRange (bool enable)
Enables or disables the auto-gain settings when reading data from the sensor.
void setIntegrationTime (tsl2561IntegrationTime_t time)
void setGain (tsl2561Gain_t gain)
void getLuminosity (uint16_t *broadband, uint16_t *ir)
Gets the broadband (mixed lighting) and IR only values from the TSL2561, adjusting gain if auto-gain is enabled.
uint32_t calculateLux (uint16_t broadband, uint16_t ir)
bool getEvent (sensors_event_t *)
Gets the most recent sensor event returns true if sensor reading is between 0 and 65535 lux returns false if sensor is saturated.
void getSensor (sensor_t *)
Gets the sensor_t data.
Detailed Description
Definition at line 178 of file Adafruit_TSL2561_U.h.
Constructor & Destructor Documentation
Adafruit_TSL2561_Unified::Adafruit_TSL2561_Unified (uint8_t addr, int32_t sensorID = -1)
Constructor
Definition at line 176 of file Adafruit_TSL2561_U.cpp.
References TSL2561_GAIN_1X, and TSL2561_INTEGRATIONTIME_13MS.
Member Function Documentation
boolean Adafruit_TSL2561_Unified::begin (void)
Initializes I2C and configures the sensor (call this function before doing anything else)
Definition at line 196 of file Adafruit_TSL2561_U.cpp.
References setGain(), setIntegrationTime(), TSL2561_REGISTER_ID, and Wire.
Referenced by configure_TSL2561(), getLuminosity(), setGain(), and setIntegrationTime().
uint32_t Adafruit_TSL2561_Unified::calculateLux (uint16_t broadband, uint16_t ir)
Converts the raw sensor values to the standard SI lux equivalent. Returns 0 if the sensor is saturated and the values are unreliable.
Definition at line 367 of file Adafruit_TSL2561_U.cpp.
References TSL2561_CLIPPING_101MS, TSL2561_CLIPPING_13MS, TSL2561_CLIPPING_402MS, TSL2561_INTEGRATIONTIME_101MS, TSL2561_INTEGRATIONTIME_13MS, TSL2561_LUX_B1C, TSL2561_LUX_B1T, TSL2561_LUX_B2C, TSL2561_LUX_B2T, TSL2561_LUX_B3C, TSL2561_LUX_B3T, TSL2561_LUX_B4C, TSL2561_LUX_B4T, TSL2561_LUX_B5C, TSL2561_LUX_B5T, TSL2561_LUX_B6C, TSL2561_LUX_B6T, TSL2561_LUX_B7C, TSL2561_LUX_B7T, TSL2561_LUX_B8C, TSL2561_LUX_B8T, TSL2561_LUX_CHSCALE, TSL2561_LUX_CHSCALE_TINT0, TSL2561_LUX_CHSCALE_TINT1, TSL2561_LUX_K1C, TSL2561_LUX_K1T, TSL2561_LUX_K2C, TSL2561_LUX_K2T, TSL2561_LUX_K3C, TSL2561_LUX_K3T, TSL2561_LUX_K4C, TSL2561_LUX_K4T, TSL2561_LUX_K5C, TSL2561_LUX_K5T, TSL2561_LUX_K6C, TSL2561_LUX_K6T, TSL2561_LUX_K7C, TSL2561_LUX_K7T, TSL2561_LUX_K8C, TSL2561_LUX_K8T, TSL2561_LUX_LUXSCALE, TSL2561_LUX_M1C, TSL2561_LUX_M1T, TSL2561_LUX_M2C, TSL2561_LUX_M2T, TSL2561_LUX_M3C, TSL2561_LUX_M3T, TSL2561_LUX_M4C, TSL2561_LUX_M4T, TSL2561_LUX_M5C, TSL2561_LUX_M5T, TSL2561_LUX_M6C, TSL2561_LUX_M6T, TSL2561_LUX_M7C, TSL2561_LUX_M7T, TSL2561_LUX_M8C, TSL2561_LUX_M8T, and TSL2561_LUX_RATIOSCALE.
Referenced by getEvent(), and readSensors().
void Adafruit_TSL2561_Unified::enableAutoRange (bool enable) [virtual]
Enables or disables the auto-gain settings when reading data from the sensor.
Reimplemented from Adafruit_Sensor.
Definition at line 224 of file Adafruit_TSL2561_U.cpp.
Referenced by configure_TSL2561().
bool Adafruit_TSL2561_Unified::getEvent (sensors_event_t * event) [virtual]
Gets the most recent sensor event returns true if sensor reading is between 0 and 65535 lux returns false if sensor is saturated.
Implements Adafruit_Sensor.
Definition at line 483 of file Adafruit_TSL2561_U.cpp.
References calculateLux(), getLuminosity(), and SENSOR_TYPE_LIGHT.
void Adafruit_TSL2561_Unified::getLuminosity (uint16_t * broadband, uint16_t * ir)
Gets the broadband (mixed lighting) and IR only values from the TSL2561, adjusting gain if auto-gain is enabled.
Definition at line 279 of file Adafruit_TSL2561_U.cpp.
References begin(), setGain(), TSL2561_AGC_THI_101MS, TSL2561_AGC_THI_13MS, TSL2561_AGC_THI_402MS, TSL2561_AGC_TLO_101MS, TSL2561_AGC_TLO_13MS, TSL2561_AGC_TLO_402MS, TSL2561_GAIN_16X, TSL2561_GAIN_1X, TSL2561_INTEGRATIONTIME_101MS, and TSL2561_INTEGRATIONTIME_13MS.
Referenced by getEvent(), and readSensors().
void Adafruit_TSL2561_Unified::getSensor (sensor_t * sensor) [virtual]
Gets the sensor_t data.
Implements Adafruit_Sensor.
Definition at line 511 of file Adafruit_TSL2561_U.cpp.
References sensor_t::max_value, sensor_t::min_delay, sensor_t::min_value, sensor_t::name, sensor_t::resolution, sensor_t::sensor_id, SENSOR_TYPE_LIGHT, sensor_t::type, and sensor_t::version.
void Adafruit_TSL2561_Unified::setGain (tsl2561Gain_t gain)
Adjusts the gain on the TSL2561 (adjusts the sensitivity to light)
Definition at line 256 of file Adafruit_TSL2561_U.cpp.
References begin(), TSL2561_COMMAND_BIT, and TSL2561_REGISTER_TIMING.
Referenced by begin(), and getLuminosity().
void Adafruit_TSL2561_Unified::setIntegrationTime (tsl2561IntegrationTime_t time)
Sets the integration time for the TSL2561
Definition at line 234 of file Adafruit_TSL2561_U.cpp.
References begin(), TSL2561_COMMAND_BIT, and TSL2561_REGISTER_TIMING.
Referenced by begin(), and configure_TSL2561().
The documentation for this class was generated from the following files:
Weather_Balloon/library/Adafruit_TSL2561-master/Adafruit_TSL2561_U.h
Weather_Balloon/library/Adafruit_TSL2561-master/Adafruit_TSL2561_U.cpp