Sd2Card Class Reference
Raw access to SD and SDHC flash memory cards.
#include <Sd2Card.h>
Public Member Functions
Sd2Card (void)
uint32_t cardSize (void)
uint8_t erase (uint32_t firstBlock, uint32_t lastBlock)
uint8_t eraseSingleBlockEnable (void)
uint8_t errorCode (void) const
uint8_t errorData (void) const
uint8_t init (void)
uint8_t init (uint8_t sckRateID)
uint8_t init (uint8_t sckRateID, uint8_t chipSelectPin, int8_t mosiPin=-1, int8_t misoPin=-1, int8_t clockPin=-1)
void partialBlockRead (uint8_t value)
uint8_t partialBlockRead (void) const
uint8_t readBlock (uint32_t block, uint8_t *dst)
uint8_t readData (uint32_t block, uint16_t offset, uint16_t count, uint8_t *dst)
uint8_t readCID (cid_t *cid)
uint8_t readCSD (csd_t *csd)
void readEnd (void)
uint8_t setSckRate (uint8_t sckRateID)
uint8_t type (void) const
uint8_t writeBlock (uint32_t blockNumber, const uint8_t *src)
uint8_t writeData (const uint8_t *src)
uint8_t writeStart (uint32_t blockNumber, uint32_t eraseCount)
uint8_t writeStop (void)
void enableCRC (uint8_t mode)
Detailed Description
Raw access to SD and SDHC flash memory cards.
Definition at line 159 of file Sd2Card.h.
Constructor & Destructor Documentation
Sd2Card::Sd2Card (void) [inline]
Construct an instance of Sd2Card.
Definition at line 162 of file Sd2Card.h.
References cardSize(), erase(), and eraseSingleBlockEnable().
Member Function Documentation
uint32_t Sd2Card::cardSize (void)
Determine the size of an SD flash memory card.
Returns
The number of 512 byte data blocks in the card or zero if an error occurs.
Definition at line 195 of file Sd2Card.cpp.
References csd1_t::c_size_high, csd2_t::c_size_high, csd1_t::c_size_low, csd2_t::c_size_low, csd1_t::c_size_mid, csd2_t::c_size_mid, csd1_t::c_size_mult_high, csd1_t::c_size_mult_low, csd1_t::csd_ver, csd2_t::csd_ver, csd1_t::read_bl_len, readCSD(), SD_CARD_ERROR_BAD_CSD, csd_t::v1, and csd_t::v2.
Referenced by configure_sdcard(), and Sd2Card().
void Sd2Card::enableCRC (uint8_t mode)
Definition at line 785 of file Sd2Card.cpp.
Referenced by type().
uint8_t Sd2Card::erase (uint32_t firstBlock, uint32_t lastBlock)
Erase a range of blocks.
Parameters
in firstBlock The address of the first block in the range.
in lastBlock The address of the last block in the range.
Note
This function requests the SD card to do a flash erase for a range of blocks. The data on the card after an erase operation is either 0 or 1, depends on the card vendor. The card must support single block erase.
Returns
The value one, true, is returned for success and the value zero, false, is returned for failure.
Definition at line 236 of file Sd2Card.cpp.
References CMD32, CMD33, CMD38, eraseSingleBlockEnable(), SD_CARD_ERROR_ERASE, SD_CARD_ERROR_ERASE_SINGLE_BLOCK, SD_CARD_ERROR_ERASE_TIMEOUT, SD_CARD_TYPE_SDHC, and SD_ERASE_TIMEOUT.
Referenced by Sd2Card().
uint8_t Sd2Card::eraseSingleBlockEnable (void)
Determine if card supports single block erase.
Returns
The value one, true, is returned if single block erase is supported. The value zero, false, is returned if single block erase is not supported.
Definition at line 268 of file Sd2Card.cpp.
References csd1_t::erase_blk_en, readCSD(), and csd_t::v1.
Referenced by erase(), and Sd2Card().
uint8_t Sd2Card::errorCode (void) const [inline]
Returns
error code for last error. See Sd2Card.h for a list of error codes.
Definition at line 169 of file Sd2Card.h.
Referenced by configure_sdcard(), and log_data().
uint8_t Sd2Card::errorData (void) const [inline]
Returns
error data for last error.
Definition at line 171 of file Sd2Card.h.
Referenced by log_data().
uint8_t Sd2Card::init (void) [inline]
Initialize an SD flash memory card with default clock rate and chip select pin. See sd2Card::init(uint8_t sckRateID, uint8_t chipSelectPin).
Definition at line 176 of file Sd2Card.h.
References SD_CHIP_SELECT_PIN, and SPI_FULL_SPEED.
Referenced by configure_sdcard(), and init().
uint8_t Sd2Card::init (uint8_t sckRateID) [inline]
Initialize an SD flash memory card with the selected SPI clock rate and the default SD chip select pin. See sd2Card::init(uint8_t sckRateID, uint8_t chipSelectPin).
Definition at line 184 of file Sd2Card.h.
References init(), partialBlockRead(), and SD_CHIP_SELECT_PIN.
uint8_t Sd2Card::init (uint8_t sckRateID, uint8_t chipSelectPin, int8_t mosiPin = -1, int8_t misoPin = -1, int8_t clockPin = -1)
Initialize an SD flash memory card.
Parameters
in sckRateID SPI clock rate selector. See setSckRate().
in chipSelectPin SD chip select pin number.
Returns
The value one, true, is returned for success and the value zero, false, is returned for failure. The reason for failure can be determined by calling errorCode() and errorData().
Definition at line 283 of file Sd2Card.cpp.
References ACMD41, CMD0, CMD58, CMD8, i, R1_IDLE_STATE, R1_ILLEGAL_COMMAND, R1_READY_STATE, SD_CARD_ERROR_ACMD41, SD_CARD_ERROR_CMD0, SD_CARD_ERROR_CMD58, SD_CARD_ERROR_CMD8, SD_CARD_TYPE_SD1, SD_CARD_TYPE_SD2, SD_CARD_TYPE_SDHC, SD_INIT_TIMEOUT, setSckRate(), SPI_MISO_PIN, SPI_MOSI_PIN, SPI_SCK_PIN, and type().
void Sd2Card::partialBlockRead (uint8_t value)
Enable or disable partial block reads.
Enabling partial block reads improves performance by allowing a block to be read over the SPI bus as several sub-blocks. Errors may occur if the time between reads is too long since the SD card may timeout. The SPI SS line will be held low until the entire block is read or readEnd() is called.
Use this for applications like the Adafruit Wave Shield.
Parameters
in value The value TRUE (non-zero) or FALSE (zero).)
Definition at line 408 of file Sd2Card.cpp.
References readEnd().
uint8_t Sd2Card::partialBlockRead (void) const [inline]
Returns the current value, true or false, for partial block read.
Definition at line 190 of file Sd2Card.h.
References readBlock(), and readData().
Referenced by init().
uint8_t Sd2Card::readBlock (uint32_t block, uint8_t * dst)
Read a 512 byte block from an SD card device.
Parameters
in block Logical block to be read.
out dst Pointer to the location that will receive the data.
Returns
The value one, true, is returned for success and the value zero, false, is returned for failure.
Definition at line 422 of file Sd2Card.cpp.
References readData().
Referenced by log_data(), partialBlockRead(), and read_sdcard().
uint8_t Sd2Card::readCID (cid_t * cid) [inline]
Read a cards CID register. The CID contains card identification information such as Manufacturer ID, Product name, Product serial number and Manufacturing date.
Definition at line 198 of file Sd2Card.h.
References CMD10.
uint8_t Sd2Card::readCSD (csd_t * csd) [inline]
Read a cards CSD register. The CSD contains Card-Specific Data that provides information regarding access to the card's contents.
Definition at line 204 of file Sd2Card.h.
References CMD9, readEnd(), and setSckRate().
Referenced by cardSize(), and eraseSingleBlockEnable().
uint8_t Sd2Card::readData (uint32_t block, uint16_t offset, uint16_t count, uint8_t * dst)
Read part of a 512 byte block from an SD card.
Parameters
in block Logical block to be read.
in offset Number of bytes to skip at start of block
out dst Pointer to the location that will receive the data.
in count Number of bytes to read
Returns
The value one, true, is returned for success and the value zero, false, is returned for failure.
Definition at line 436 of file Sd2Card.cpp.
References CMD17, i, readEnd(), SD_CARD_ERROR_CMD17, SD_CARD_TYPE_SDHC, and type().
Referenced by find_sdcard_tail(), partialBlockRead(), and readBlock().
void Sd2Card::readEnd (void)
Skip remaining data in a block when in partial block read mode.
Definition at line 503 of file Sd2Card.cpp.
References i, and SD_CARD_ERROR_READ_REG.
Referenced by partialBlockRead(), readCSD(), and readData().
uint8_t Sd2Card::setSckRate (uint8_t sckRateID)
Set the SPI clock rate.
Parameters
in sckRateID A value in the range [0, 6].
The SPI clock will be set to F_CPU/pow(2, 1 + sckRateID). The maximum SPI rate is F_CPU/2 for sckRateID = 0 and the minimum rate is F_CPU/128 for scsRateID = 6.
Returns
The value one, true, is returned for success and the value zero, false, is returned for an invalid value of sckRateID.
Definition at line 555 of file Sd2Card.cpp.
References DATA_START_BLOCK, SD_CARD_ERROR_READ, SD_CARD_ERROR_READ_TIMEOUT, SD_CARD_ERROR_SCK_RATE, and SD_READ_TIMEOUT.
Referenced by init(), and readCSD().
uint8_t Sd2Card::type (void) const [inline]
Return the card type: SD V1, SD V2 or SDHC
Definition at line 210 of file Sd2Card.h.
References CMD55, enableCRC(), writeBlock(), writeData(), writeStart(), and writeStop().
Referenced by init(), readData(), writeBlock(), and writeStart().
uint8_t Sd2Card::writeBlock (uint32_t blockNumber, const uint8_t * src)
Writes a 512 byte block to an SD card.
Parameters
in blockNumber Logical block to be written.
in src Pointer to the location of the data to be written.
Returns
The value one, true, is returned for success and the value zero, false, is returned for failure.
Definition at line 628 of file Sd2Card.cpp.
References CMD13, CMD24, DATA_START_BLOCK, SD_CARD_ERROR_CMD24, SD_CARD_ERROR_WRITE_BLOCK_ZERO, SD_CARD_ERROR_WRITE_PROGRAMMING, SD_CARD_ERROR_WRITE_TIMEOUT, SD_CARD_TYPE_SDHC, SD_WRITE_TIMEOUT, type(), and writeData().
Referenced by log_data(), and type().
uint8_t Sd2Card::writeData (const uint8_t * src)
Write one data block in a multiple block write sequence
Definition at line 664 of file Sd2Card.cpp.
References DATA_RES_ACCEPTED, DATA_RES_MASK, i, SD_CARD_ERROR_WRITE, SD_CARD_ERROR_WRITE_MULTIPLE, SD_WRITE_TIMEOUT, and WRITE_MULTIPLE_TOKEN.
Referenced by type(), and writeBlock().
uint8_t Sd2Card::writeStart (uint32_t blockNumber, uint32_t eraseCount)
Start a write multiple blocks sequence.
Parameters
in blockNumber Address of first block in sequence.
in eraseCount The number of blocks to be pre-erased.
Note
This function is used with writeData() and writeStop() for optimized multiple block writes.
Returns
The value one, true, is returned for success and the value zero, false, is returned for failure.
Definition at line 741 of file Sd2Card.cpp.
References ACMD23, CMD25, SD_CARD_ERROR_ACMD23, SD_CARD_ERROR_CMD25, SD_CARD_ERROR_WRITE_BLOCK_ZERO, SD_CARD_TYPE_SDHC, and type().
Referenced by type().
uint8_t Sd2Card::writeStop (void)
End a write multiple blocks sequence.
Returns
The value one, true, is returned for success and the value zero, false, is returned for failure.
Definition at line 772 of file Sd2Card.cpp.
References SD_CARD_ERROR_STOP_TRAN, SD_WRITE_TIMEOUT, and STOP_TRAN_TOKEN.
Referenced by type().
The documentation for this class was generated from the following files:
Weather_Balloon/library/SD-master/Sd2Card.h
Weather_Balloon/library/SD-master/Sd2Card.cpp