LSM9DS1 Class Reference
#include <SparkFunLSM9DS1.h>
Public Member Functions
LSM9DS1 (interface_mode interface, uint8_t xgAddr, uint8_t mAddr)
LSM9DS1 ()
uint16_t begin ()
void calibrate (bool autoCalc=true)
void calibrateMag (bool loadIn=true)
void magOffset (uint8_t axis, int16_t offset)
uint8_t accelAvailable ()
uint8_t gyroAvailable ()
uint8_t tempAvailable ()
uint8_t magAvailable (lsm9ds1_axis axis=ALL_AXIS)
void readGyro ()
int16_t readGyro (lsm9ds1_axis axis)
void readAccel ()
int16_t readAccel (lsm9ds1_axis axis)
void readMag ()
int16_t readMag (lsm9ds1_axis axis)
void readTemp ()
float calcGyro (int16_t gyro)
float calcAccel (int16_t accel)
float calcMag (int16_t mag)
void setGyroScale (uint16_t gScl)
void setAccelScale (uint8_t aScl)
void setMagScale (uint8_t mScl)
void setGyroODR (uint8_t gRate)
void setAccelODR (uint8_t aRate)
void setMagODR (uint8_t mRate)
void configInactivity (uint8_t duration, uint8_t threshold, bool sleepOn)
void configAccelInt (uint8_t generator, bool andInterrupts=false)
void configAccelThs (uint8_t threshold, lsm9ds1_axis axis, uint8_t duration=0, bool wait=0)
void configGyroInt (uint8_t generator, bool aoi, bool latch)
void configGyroThs (int16_t threshold, lsm9ds1_axis axis, uint8_t duration, bool wait)
void configInt (interrupt_select interupt, uint8_t generator, h_lactive activeLow=INT_ACTIVE_LOW, pp_od pushPull=INT_PUSH_PULL)
void configMagInt (uint8_t generator, h_lactive activeLow, bool latch=true)
void configMagThs (uint16_t threshold)
uint8_t getGyroIntSrc ()
uint8_t getAccelIntSrc ()
uint8_t getMagIntSrc ()
uint8_t getInactivity ()
void sleepGyro (bool enable=true)
void enableFIFO (bool enable=true)
void setFIFO (fifoMode_type fifoMode, uint8_t fifoThs)
uint8_t getFIFOSamples ()
Public Attributes
IMUSettings settings
int16_t gx
int16_t gy
int16_t gz
int16_t ax
int16_t ay
int16_t az
int16_t mx
int16_t my
int16_t mz
int16_t temperature
float gBias [3]
float aBias [3]
float mBias [3]
int16_t gBiasRaw [3]
int16_t aBiasRaw [3]
int16_t mBiasRaw [3]
Protected Member Functions
void init (interface_mode interface, uint8_t xgAddr, uint8_t mAddr)
void initGyro ()
void initAccel ()
void initMag ()
uint8_t mReadByte (uint8_t subAddress)
void mReadBytes (uint8_t subAddress, uint8_t *dest, uint8_t count)
void mWriteByte (uint8_t subAddress, uint8_t data)
uint8_t xgReadByte (uint8_t subAddress)
void xgReadBytes (uint8_t subAddress, uint8_t *dest, uint8_t count)
void xgWriteByte (uint8_t subAddress, uint8_t data)
void calcgRes ()
void calcmRes ()
void calcaRes ()
void constrainScales ()
void initSPI ()
void SPIwriteByte (uint8_t csPin, uint8_t subAddress, uint8_t data)
uint8_t SPIreadByte (uint8_t csPin, uint8_t subAddress)
void SPIreadBytes (uint8_t csPin, uint8_t subAddress, uint8_t *dest, uint8_t count)
void initI2C ()
void I2CwriteByte (uint8_t address, uint8_t subAddress, uint8_t data)
uint8_t I2CreadByte (uint8_t address, uint8_t subAddress)
uint8_t I2CreadBytes (uint8_t address, uint8_t subAddress, uint8_t *dest, uint8_t count)
Protected Attributes
uint8_t _mAddress
uint8_t _xgAddress
float gRes
float aRes
float mRes
bool _autoCalc
Detailed Description
Definition at line 45 of file SparkFunLSM9DS1.h.
Constructor & Destructor Documentation
LSM9DS1::LSM9DS1 (interface_mode interface, uint8_t xgAddr, uint8_t mAddr)
Definition at line 45 of file SparkFunLSM9DS1.cpp.
References init().
LSM9DS1::LSM9DS1 ()
Definition at line 40 of file SparkFunLSM9DS1.cpp.
References IMU_MODE_I2C, init(), LSM9DS1_AG_ADDR, and LSM9DS1_M_ADDR.
Member Function Documentation
uint8_t LSM9DS1::accelAvailable ()
Definition at line 476 of file SparkFunLSM9DS1.cpp.
References STATUS_REG_1, and xgReadByte().
uint16_t LSM9DS1::begin (void)
Todo: don't use _xgAddress or _mAddress, duplicating memory
Definition at line 142 of file SparkFunLSM9DS1.cpp.
References _mAddress, _xgAddress, deviceSettings::agAddress, calcaRes(), calcgRes(), calcmRes(), deviceSettings::commInterface, constrainScales(), IMUSettings::device, IMU_MODE_I2C, IMU_MODE_SPI, initAccel(), initGyro(), initI2C(), initMag(), initSPI(), deviceSettings::mAddress, mReadByte(), settings, WHO_AM_I_AG_RSP, WHO_AM_I_M, WHO_AM_I_M_RSP, WHO_AM_I_XG, and xgReadByte().
Referenced by configure_LSM9DS1().
float LSM9DS1::calcAccel (int16_t accel)
Definition at line 592 of file SparkFunLSM9DS1.cpp.
References aRes.
Referenced by calibrate(), and readSensors().
void LSM9DS1::calcaRes () [protected]
Definition at line 748 of file SparkFunLSM9DS1.cpp.
References IMUSettings::accel, aRes, accelSettings::scale, and settings.
Referenced by begin(), and setAccelScale().
void LSM9DS1::calcgRes () [protected]
Definition at line 743 of file SparkFunLSM9DS1.cpp.
References gRes, IMUSettings::gyro, gyroSettings::scale, and settings.
Referenced by begin(), and setGyroScale().
float LSM9DS1::calcGyro (int16_t gyro)
Definition at line 586 of file SparkFunLSM9DS1.cpp.
References gRes.
Referenced by calibrate(), and readSensors().
float LSM9DS1::calcMag (int16_t mag)
Definition at line 598 of file SparkFunLSM9DS1.cpp.
References mRes.
Referenced by calibrateMag(), and readSensors().
void LSM9DS1::calcmRes () [protected]
Definition at line 753 of file SparkFunLSM9DS1.cpp.
References IMUSettings::mag, magSensitivity, mRes, magSettings::scale, and settings.
Referenced by begin(), and setMagScale().
void LSM9DS1::calibrate (bool autoCalc = true)
Definition at line 326 of file SparkFunLSM9DS1.cpp.
References _autoCalc, aBias, aBiasRaw, aRes, ax, ay, az, calcAccel(), calcGyro(), enableFIFO(), FIFO_OFF, FIFO_SRC, FIFO_THS, gBias, gBiasRaw, gx, gy, gz, readAccel(), readGyro(), setFIFO(), and xgReadByte().
Referenced by configure_LSM9DS1().
void LSM9DS1::calibrateMag (bool loadIn = true)
Definition at line 366 of file SparkFunLSM9DS1.cpp.
References calcMag(), i, magAvailable(), magOffset(), mBias, mBiasRaw, mx, my, mz, and readMag().
Referenced by configure_LSM9DS1().
void LSM9DS1::configAccelInt (uint8_t generator, bool andInterrupts = false)
Definition at line 813 of file SparkFunLSM9DS1.cpp.
References INT_GEN_CFG_XL, and xgWriteByte().
void LSM9DS1::configAccelThs (uint8_t threshold, lsm9ds1_axis axis, uint8_t duration = 0, bool wait = 0)
Definition at line 822 of file SparkFunLSM9DS1.cpp.
References INT_GEN_DUR_XL, INT_GEN_THS_X_XL, and xgWriteByte().
void LSM9DS1::configGyroInt (uint8_t generator, bool aoi, bool latch)
Definition at line 848 of file SparkFunLSM9DS1.cpp.
References INT_GEN_CFG_G, and xgWriteByte().
void LSM9DS1::configGyroThs (int16_t threshold, lsm9ds1_axis axis, uint8_t duration, bool wait)
Definition at line 858 of file SparkFunLSM9DS1.cpp.
References INT_GEN_DUR_G, INT_GEN_THS_XH_G, and xgWriteByte().
void LSM9DS1::configInactivity (uint8_t duration, uint8_t threshold, bool sleepOn)
Definition at line 795 of file SparkFunLSM9DS1.cpp.
References ACT_DUR, ACT_THS, and xgWriteByte().
void LSM9DS1::configInt (interrupt_select interupt, uint8_t generator, h_lactive activeLow = INT_ACTIVE_LOW, pp_od pushPull = INT_PUSH_PULL)
Definition at line 774 of file SparkFunLSM9DS1.cpp.
References CTRL_REG8, xgReadByte(), and xgWriteByte().
void LSM9DS1::configMagInt (uint8_t generator, h_lactive activeLow, bool latch = true)
Definition at line 888 of file SparkFunLSM9DS1.cpp.
References INT_ACTIVE_HIGH, INT_CFG_M, and mWriteByte().
void LSM9DS1::configMagThs (uint16_t threshold)
Definition at line 902 of file SparkFunLSM9DS1.cpp.
References INT_THS_H_M, INT_THS_L_M, and mWriteByte().
void LSM9DS1::constrainScales () [protected]
Definition at line 952 of file SparkFunLSM9DS1.cpp.
References IMUSettings::accel, IMUSettings::gyro, IMUSettings::mag, gyroSettings::scale, accelSettings::scale, magSettings::scale, and settings.
Referenced by begin().
void LSM9DS1::enableFIFO (bool enable = true)
Definition at line 931 of file SparkFunLSM9DS1.cpp.
References CTRL_REG9, xgReadByte(), and xgWriteByte().
Referenced by calibrate().
uint8_t LSM9DS1::getAccelIntSrc ()
Definition at line 835 of file SparkFunLSM9DS1.cpp.
References INT_GEN_SRC_XL, and xgReadByte().
uint8_t LSM9DS1::getFIFOSamples ()
Definition at line 947 of file SparkFunLSM9DS1.cpp.
References FIFO_SRC, and xgReadByte().
uint8_t LSM9DS1::getGyroIntSrc ()
Definition at line 875 of file SparkFunLSM9DS1.cpp.
References INT_GEN_SRC_G, and xgReadByte().
uint8_t LSM9DS1::getInactivity ()
Definition at line 806 of file SparkFunLSM9DS1.cpp.
References STATUS_REG_0, and xgReadByte().
uint8_t LSM9DS1::getMagIntSrc ()
Definition at line 910 of file SparkFunLSM9DS1.cpp.
References INT_SRC_M, and mReadByte().
uint8_t LSM9DS1::gyroAvailable ()
Definition at line 483 of file SparkFunLSM9DS1.cpp.
References STATUS_REG_1, and xgReadByte().
uint8_t LSM9DS1::I2CreadByte (uint8_t address, uint8_t subAddress) [protected]
Bad! 255 will be misinterpreted as a good value.
Definition at line 1104 of file SparkFunLSM9DS1.cpp.
References LSM9DS1_COMMUNICATION_TIMEOUT, and Wire.
Referenced by mReadByte(), and xgReadByte().
uint8_t LSM9DS1::I2CreadBytes (uint8_t address, uint8_t subAddress, uint8_t * dest, uint8_t count) [protected]
Definition at line 1123 of file SparkFunLSM9DS1.cpp.
References i, LSM9DS1_COMMUNICATION_TIMEOUT, and Wire.
Referenced by mReadBytes(), and xgReadBytes().
void LSM9DS1::I2CwriteByte (uint8_t address, uint8_t subAddress, uint8_t data) [protected]
Definition at line 1096 of file SparkFunLSM9DS1.cpp.
References Wire.
Referenced by mWriteByte(), and xgWriteByte().
void LSM9DS1::init (interface_mode interface, uint8_t xgAddr, uint8_t mAddr) [protected]
Definition at line 50 of file SparkFunLSM9DS1.cpp.
References _autoCalc, aBias, aBiasRaw, IMUSettings::accel, deviceSettings::agAddress, gyroSettings::bandwidth, accelSettings::bandwidth, deviceSettings::commInterface, IMUSettings::device, gyroSettings::enabled, accelSettings::enabled, magSettings::enabled, temperatureSettings::enabled, gyroSettings::enableX, accelSettings::enableX, gyroSettings::enableY, accelSettings::enableY, gyroSettings::enableZ, accelSettings::enableZ, gyroSettings::flipX, gyroSettings::flipY, gyroSettings::flipZ, gBias, gBiasRaw, IMUSettings::gyro, accelSettings::highResBandwidth, accelSettings::highResEnable, gyroSettings::HPFCutoff, gyroSettings::HPFEnable, i, gyroSettings::latchInterrupt, gyroSettings::lowPowerEnable, magSettings::lowPowerEnable, deviceSettings::mAddress, IMUSettings::mag, mBias, mBiasRaw, magSettings::operatingMode, gyroSettings::orientation, gyroSettings::sampleRate, accelSettings::sampleRate, magSettings::sampleRate, gyroSettings::scale, accelSettings::scale, magSettings::scale, settings, IMUSettings::temp, magSettings::tempCompensationEnable, magSettings::XYPerformance, and magSettings::ZPerformance.
Referenced by LSM9DS1().
void LSM9DS1::initAccel () [protected]
Definition at line 255 of file SparkFunLSM9DS1.cpp.
References IMUSettings::accel, accelSettings::bandwidth, CTRL_REG5_XL, CTRL_REG6_XL, CTRL_REG7_XL, accelSettings::enabled, accelSettings::enableX, accelSettings::enableY, accelSettings::enableZ, accelSettings::highResBandwidth, accelSettings::highResEnable, accelSettings::sampleRate, accelSettings::scale, settings, and xgWriteByte().
Referenced by begin().
void LSM9DS1::initGyro () [protected]
Definition at line 183 of file SparkFunLSM9DS1.cpp.
References gyroSettings::bandwidth, CTRL_REG1_G, CTRL_REG2_G, CTRL_REG3_G, CTRL_REG4, gyroSettings::enabled, gyroSettings::enableX, gyroSettings::enableY, gyroSettings::enableZ, gyroSettings::flipX, gyroSettings::flipY, gyroSettings::flipZ, IMUSettings::gyro, gyroSettings::HPFCutoff, gyroSettings::HPFEnable, gyroSettings::latchInterrupt, gyroSettings::lowPowerEnable, ORIENT_CFG_G, gyroSettings::sampleRate, gyroSettings::scale, settings, and xgWriteByte().
Referenced by begin().
void LSM9DS1::initI2C () [protected]
Definition at line 1090 of file SparkFunLSM9DS1.cpp.
References Wire.
Referenced by begin().
void LSM9DS1::initMag () [protected]
Definition at line 407 of file SparkFunLSM9DS1.cpp.
References CTRL_REG1_M, CTRL_REG2_M, CTRL_REG3_M, CTRL_REG4_M, CTRL_REG5_M, magSettings::lowPowerEnable, IMUSettings::mag, mWriteByte(), magSettings::operatingMode, magSettings::sampleRate, magSettings::scale, settings, magSettings::tempCompensationEnable, magSettings::XYPerformance, and magSettings::ZPerformance.
Referenced by begin().
void LSM9DS1::initSPI () [protected]
Definition at line 1033 of file SparkFunLSM9DS1.cpp.
References _mAddress, and _xgAddress.
Referenced by begin().
uint8_t LSM9DS1::magAvailable (lsm9ds1_axis axis = ALL_AXIS)
Definition at line 497 of file SparkFunLSM9DS1.cpp.
References mReadByte(), and STATUS_REG_M.
Referenced by calibrateMag().
void LSM9DS1::magOffset (uint8_t axis, int16_t offset)
Definition at line 396 of file SparkFunLSM9DS1.cpp.
References mWriteByte(), OFFSET_X_REG_H_M, and OFFSET_X_REG_L_M.
Referenced by calibrateMag().
uint8_t LSM9DS1::mReadByte (uint8_t subAddress) [protected]
Definition at line 1013 of file SparkFunLSM9DS1.cpp.
References _mAddress, deviceSettings::commInterface, IMUSettings::device, I2CreadByte(), IMU_MODE_I2C, IMU_MODE_SPI, settings, and SPIreadByte().
Referenced by begin(), getMagIntSrc(), magAvailable(), setMagODR(), and setMagScale().
void LSM9DS1::mReadBytes (uint8_t subAddress, uint8_t * dest, uint8_t count) [protected]
Definition at line 1023 of file SparkFunLSM9DS1.cpp.
References _mAddress, deviceSettings::commInterface, IMUSettings::device, I2CreadBytes(), IMU_MODE_I2C, IMU_MODE_SPI, settings, and SPIreadBytes().
Referenced by readMag().
void LSM9DS1::mWriteByte (uint8_t subAddress, uint8_t data) [protected]
Definition at line 983 of file SparkFunLSM9DS1.cpp.
References _mAddress, deviceSettings::commInterface, IMUSettings::device, I2CwriteByte(), IMU_MODE_I2C, IMU_MODE_SPI, settings, and SPIwriteByte().
Referenced by configMagInt(), configMagThs(), initMag(), magOffset(), setMagODR(), and setMagScale().
void LSM9DS1::readAccel ()
Definition at line 505 of file SparkFunLSM9DS1.cpp.
References _autoCalc, aBiasRaw, ax, ay, az, OUT_X_L_XL, X_AXIS, xgReadBytes(), Y_AXIS, and Z_AXIS.
Referenced by calibrate(), and readSensors().
int16_t LSM9DS1::readAccel (lsm9ds1_axis axis)
Definition at line 520 of file SparkFunLSM9DS1.cpp.
References _autoCalc, aBiasRaw, OUT_X_L_XL, and xgReadBytes().
void LSM9DS1::readGyro ()
Definition at line 556 of file SparkFunLSM9DS1.cpp.
References _autoCalc, gBiasRaw, gx, gy, gz, OUT_X_L_G, X_AXIS, xgReadBytes(), Y_AXIS, and Z_AXIS.
Referenced by calibrate(), and readSensors().
int16_t LSM9DS1::readGyro (lsm9ds1_axis axis)
Definition at line 571 of file SparkFunLSM9DS1.cpp.
References _autoCalc, gBiasRaw, OUT_X_L_G, and xgReadBytes().
void LSM9DS1::readMag ()
Definition at line 533 of file SparkFunLSM9DS1.cpp.
References mReadBytes(), mx, my, mz, and OUT_X_L_M.
Referenced by calibrateMag(), and readSensors().
int16_t LSM9DS1::readMag (lsm9ds1_axis axis)
Definition at line 542 of file SparkFunLSM9DS1.cpp.
References mReadBytes(), and OUT_X_L_M.
void LSM9DS1::readTemp ()
Definition at line 549 of file SparkFunLSM9DS1.cpp.
References OUT_TEMP_L, temperature, and xgReadBytes().
void LSM9DS1::setAccelODR (uint8_t aRate)
Definition at line 713 of file SparkFunLSM9DS1.cpp.
References IMUSettings::accel, CTRL_REG6_XL, accelSettings::sampleRate, settings, xgReadByte(), and xgWriteByte().
void LSM9DS1::setAccelScale (uint8_t aScl)
Definition at line 629 of file SparkFunLSM9DS1.cpp.
References IMUSettings::accel, calcaRes(), CTRL_REG6_XL, accelSettings::scale, settings, xgReadByte(), and xgWriteByte().
void LSM9DS1::setFIFO (fifoMode_type fifoMode, uint8_t fifoThs)
Definition at line 939 of file SparkFunLSM9DS1.cpp.
References FIFO_CTRL, and xgWriteByte().
Referenced by calibrate().
void LSM9DS1::setGyroODR (uint8_t gRate)
Definition at line 696 of file SparkFunLSM9DS1.cpp.
References CTRL_REG1_G, IMUSettings::gyro, gyroSettings::sampleRate, settings, xgReadByte(), and xgWriteByte().
void LSM9DS1::setGyroScale (uint16_t gScl)
Definition at line 604 of file SparkFunLSM9DS1.cpp.
References calcgRes(), CTRL_REG1_G, IMUSettings::gyro, gyroSettings::scale, settings, xgReadByte(), and xgWriteByte().
void LSM9DS1::setMagODR (uint8_t mRate)
Definition at line 730 of file SparkFunLSM9DS1.cpp.
References CTRL_REG1_M, IMUSettings::mag, mReadByte(), mWriteByte(), magSettings::sampleRate, and settings.
void LSM9DS1::setMagScale (uint8_t mScl)
Definition at line 660 of file SparkFunLSM9DS1.cpp.
References calcmRes(), CTRL_REG2_M, IMUSettings::mag, mReadByte(), mWriteByte(), magSettings::scale, and settings.
void LSM9DS1::sleepGyro (bool enable = true)
Definition at line 923 of file SparkFunLSM9DS1.cpp.
References CTRL_REG9, xgReadByte(), and xgWriteByte().
uint8_t LSM9DS1::SPIreadByte (uint8_t csPin, uint8_t subAddress) [protected]
Definition at line 1062 of file SparkFunLSM9DS1.cpp.
References SPIreadBytes().
Referenced by mReadByte(), and xgReadByte().
void LSM9DS1::SPIreadBytes (uint8_t csPin, uint8_t subAddress, uint8_t * dest, uint8_t count) [protected]
Definition at line 1071 of file SparkFunLSM9DS1.cpp.
References _mAddress, and i.
Referenced by mReadBytes(), SPIreadByte(), and xgReadBytes().
void LSM9DS1::SPIwriteByte (uint8_t csPin, uint8_t subAddress, uint8_t data) [protected]
Definition at line 1050 of file SparkFunLSM9DS1.cpp.
Referenced by mWriteByte(), and xgWriteByte().
uint8_t LSM9DS1::tempAvailable ()
Definition at line 490 of file SparkFunLSM9DS1.cpp.
References STATUS_REG_1, and xgReadByte().
uint8_t LSM9DS1::xgReadByte (uint8_t subAddress) [protected]
Definition at line 993 of file SparkFunLSM9DS1.cpp.
References _xgAddress, deviceSettings::commInterface, IMUSettings::device, I2CreadByte(), IMU_MODE_I2C, IMU_MODE_SPI, settings, and SPIreadByte().
Referenced by accelAvailable(), begin(), calibrate(), configInt(), enableFIFO(), getAccelIntSrc(), getFIFOSamples(), getGyroIntSrc(), getInactivity(), gyroAvailable(), setAccelODR(), setAccelScale(), setGyroODR(), setGyroScale(), sleepGyro(), and tempAvailable().
void LSM9DS1::xgReadBytes (uint8_t subAddress, uint8_t * dest, uint8_t count) [protected]
Definition at line 1003 of file SparkFunLSM9DS1.cpp.
References _xgAddress, deviceSettings::commInterface, IMUSettings::device, I2CreadBytes(), IMU_MODE_I2C, IMU_MODE_SPI, settings, and SPIreadBytes().
Referenced by readAccel(), readGyro(), and readTemp().
void LSM9DS1::xgWriteByte (uint8_t subAddress, uint8_t data) [protected]
Definition at line 973 of file SparkFunLSM9DS1.cpp.
References _xgAddress, deviceSettings::commInterface, IMUSettings::device, I2CwriteByte(), IMU_MODE_I2C, IMU_MODE_SPI, settings, and SPIwriteByte().
Referenced by configAccelInt(), configAccelThs(), configGyroInt(), configGyroThs(), configInactivity(), configInt(), enableFIFO(), initAccel(), initGyro(), setAccelODR(), setAccelScale(), setFIFO(), setGyroODR(), setGyroScale(), and sleepGyro().
Member Data Documentation
bool LSM9DS1::_autoCalc [protected]
Definition at line 345 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), init(), readAccel(), and readGyro().
uint8_t LSM9DS1::_mAddress [protected]
Definition at line 336 of file SparkFunLSM9DS1.h.
Referenced by begin(), initSPI(), mReadByte(), mReadBytes(), mWriteByte(), and SPIreadBytes().
uint8_t LSM9DS1::_xgAddress [protected]
Definition at line 336 of file SparkFunLSM9DS1.h.
Referenced by begin(), initSPI(), xgReadByte(), xgReadBytes(), and xgWriteByte().
float LSM9DS1::aBias[3]
Definition at line 59 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), and init().
int16_t LSM9DS1::aBiasRaw[3]
Definition at line 60 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), init(), and readAccel().
float LSM9DS1::aRes [protected]
Definition at line 341 of file SparkFunLSM9DS1.h.
Referenced by calcAccel(), calcaRes(), and calibrate().
int16_t LSM9DS1::ax
Definition at line 56 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), readAccel(), and readSensors().
int16_t LSM9DS1::ay
Definition at line 56 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), readAccel(), and readSensors().
int16_t LSM9DS1::az
Definition at line 56 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), readAccel(), and readSensors().
float LSM9DS1::gBias[3]
Definition at line 59 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), and init().
int16_t LSM9DS1::gBiasRaw[3]
Definition at line 60 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), init(), and readGyro().
float LSM9DS1::gRes [protected]
Definition at line 341 of file SparkFunLSM9DS1.h.
Referenced by calcgRes(), and calcGyro().
int16_t LSM9DS1::gx
Definition at line 55 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), readGyro(), and readSensors().
int16_t LSM9DS1::gy
Definition at line 55 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), readGyro(), and readSensors().
int16_t LSM9DS1::gz
Definition at line 55 of file SparkFunLSM9DS1.h.
Referenced by calibrate(), readGyro(), and readSensors().
float LSM9DS1::mBias[3]
Definition at line 59 of file SparkFunLSM9DS1.h.
Referenced by calibrateMag(), and init().
int16_t LSM9DS1::mBiasRaw[3]
Definition at line 60 of file SparkFunLSM9DS1.h.
Referenced by calibrateMag(), and init().
float LSM9DS1::mRes [protected]
Definition at line 341 of file SparkFunLSM9DS1.h.
Referenced by calcMag(), and calcmRes().
int16_t LSM9DS1::mx
Definition at line 57 of file SparkFunLSM9DS1.h.
Referenced by calibrateMag(), readMag(), and readSensors().
int16_t LSM9DS1::my
Definition at line 57 of file SparkFunLSM9DS1.h.
Referenced by calibrateMag(), readMag(), and readSensors().
int16_t LSM9DS1::mz
Definition at line 57 of file SparkFunLSM9DS1.h.
Referenced by calibrateMag(), readMag(), and readSensors().
IMUSettings LSM9DS1::settings
Definition at line 48 of file SparkFunLSM9DS1.h.
Referenced by begin(), calcaRes(), calcgRes(), calcmRes(), configure_LSM9DS1(), constrainScales(), init(), initAccel(), initGyro(), initMag(), mReadByte(), mReadBytes(), mWriteByte(), setAccelODR(), setAccelScale(), setGyroODR(), setGyroScale(), setMagODR(), setMagScale(), xgReadByte(), xgReadBytes(), and xgWriteByte().
int16_t LSM9DS1::temperature
Definition at line 58 of file SparkFunLSM9DS1.h.
Referenced by readTemp().
The documentation for this class was generated from the following files:
Weather_Balloon/library/SparkFun_LSM9DS1/src/SparkFunLSM9DS1.h
Weather_Balloon/library/SparkFun_LSM9DS1/src/SparkFunLSM9DS1.cpp