MS5xxx Class Reference
#include <MS5xxx.h>
Public Member Functions
MS5xxx (TwoWire *aWire)
void setI2Caddr (char aAddr)
byte connect ()
void ReadProm ()
void Readout ()
unsigned int Calc_CRC4 (unsigned char poly=0x30)
unsigned int Read_CRC4 ()
unsigned char CRCcodeTest ()
unsigned int Read_C (unsigned int index)
double GetTemp ()
double GetPres ()
Protected Member Functions
unsigned char send_cmd (unsigned char aCMD)
unsigned long read_adc (unsigned char aCMD)
Protected Attributes
unsigned int C [8]
double P
double TEMP
char i2caddr
TwoWire * _Wire
Detailed Description
Definition at line 45 of file MS5xxx.h.
Constructor & Destructor Documentation
MS5xxx::MS5xxx (TwoWire * aWire)
Definition at line 24 of file MS5xxx.cpp.
References _Wire.
Member Function Documentation
unsigned int MS5xxx::Calc_CRC4 (unsigned char poly = 0x30)
Definition at line 66 of file MS5xxx.cpp.
References C.
Referenced by CRCcodeTest().
uint8_t MS5xxx::connect ()
Definition at line 40 of file MS5xxx.cpp.
References _Wire, and i2caddr.
unsigned char MS5xxx::CRCcodeTest ()
Definition at line 191 of file MS5xxx.cpp.
References C, Calc_CRC4(), i, and ReadProm().
double MS5xxx::GetPres ()
Definition at line 187 of file MS5xxx.cpp.
References P.
double MS5xxx::GetTemp ()
Definition at line 183 of file MS5xxx.cpp.
References TEMP.
unsigned long MS5xxx::read_adc (unsigned char aCMD) [protected]
Definition at line 116 of file MS5xxx.cpp.
References _Wire, i2caddr, MS5xxx_CMD_ADC_1024, MS5xxx_CMD_ADC_2048, MS5xxx_CMD_ADC_256, MS5xxx_CMD_ADC_4096, MS5xxx_CMD_ADC_512, MS5xxx_CMD_ADC_CONV, MS5xxx_CMD_ADC_READ, and send_cmd().
Referenced by MS5611::Readout(), and Readout().
unsigned int MS5xxx::Read_C (unsigned int index)
Definition at line 108 of file MS5xxx.cpp.
References C.
unsigned int MS5xxx::Read_CRC4 ()
Definition at line 101 of file MS5xxx.cpp.
References C.
void MS5xxx::Readout ()
Definition at line 148 of file MS5xxx.cpp.
References C, MS5xxx_CMD_ADC_4096, MS5xxx_CMD_ADC_D1, MS5xxx_CMD_ADC_D2, P, read_adc(), and TEMP.
void MS5xxx::ReadProm ()
Definition at line 47 of file MS5xxx.cpp.
References _Wire, C, i, i2caddr, MS5xxx_CMD_PROM_RD, MS5xxx_CMD_RESET, and send_cmd().
Referenced by CRCcodeTest().
byte MS5xxx::send_cmd (unsigned char aCMD) [protected]
Definition at line 32 of file MS5xxx.cpp.
References _Wire, and i2caddr.
Referenced by read_adc(), and ReadProm().
void MS5xxx::setI2Caddr (char aAddr)
Definition at line 28 of file MS5xxx.cpp.
References i2caddr.
Referenced by MS5611::MS5611().
Member Data Documentation
TwoWire* MS5xxx::_Wire [protected]
Definition at line 52 of file MS5xxx.h.
Referenced by connect(), MS5xxx(), read_adc(), ReadProm(), and send_cmd().
unsigned int MS5xxx::C[8] [protected]
Definition at line 48 of file MS5xxx.h.
Referenced by Calc_CRC4(), CRCcodeTest(), Read_C(), Read_CRC4(), MS5611::Readout(), Readout(), and ReadProm().
char MS5xxx::i2caddr [protected]
Definition at line 51 of file MS5xxx.h.
Referenced by connect(), read_adc(), ReadProm(), send_cmd(), and setI2Caddr().
double MS5xxx::P [protected]
Definition at line 49 of file MS5xxx.h.
Referenced by GetPres(), MS5611::Readout(), and Readout().
double MS5xxx::TEMP [protected]
Definition at line 50 of file MS5xxx.h.
Referenced by GetTemp(), MS5611::Readout(), and Readout().
The documentation for this class was generated from the following files:
Weather_Balloon/library/arduino-ms5xxx-master/src/MS5xxx.h
Weather_Balloon/library/arduino-ms5xxx-master/src/MS5xxx.cpp