FirmataClass Class Reference
#include <Firmata.h>
Public Member Functions
FirmataClass ()
void begin ()
void begin (long)
void begin (Stream &s)
void printVersion (void)
void blinkVersion (void)
void printFirmwareVersion (void)
void setFirmwareNameAndVersion (const char *name, byte major, byte minor)
void disableBlinkVersion ()
int available (void)
void processInput (void)
void parse (unsigned char value)
boolean isParsingMessage (void)
void sendAnalog (byte pin, int value)
void sendDigital (byte pin, int value)
void sendDigitalPort (byte portNumber, int portData)
void sendString (const char *string)
void sendString (byte command, const char *string)
void sendSysex (byte command, byte bytec, byte *bytev)
void write (byte c)
void attach (byte command, callbackFunction newFunction)
void attach (byte command, systemResetCallbackFunction newFunction)
void attach (byte command, stringCallbackFunction newFunction)
void attach (byte command, sysexCallbackFunction newFunction)
void detach (byte command)
byte getPinMode (byte pin)
void setPinMode (byte pin, byte config)
int getPinState (byte pin)
void setPinState (byte pin, int state)
void sendValueAsTwo7bitBytes (int value)
void startSysex (void)
void endSysex (void)
Detailed Description
Definition at line 129 of file Firmata.h.
Constructor & Destructor Documentation
FirmataClass::FirmataClass ()
The Firmata class. An instance named `Firmata` is created automatically for the user.
Definition at line 64 of file Firmata.cpp.
Member Function Documentation
void FirmataClass::attach (byte command, callbackFunction newFunction)
Attach a generic sysex callback function to a command (options are: ANALOG_MESSAGE, DIGITAL_MESSAGE, REPORT_ANALOG, REPORT DIGITAL, SET_PIN_MODE and SET_DIGITAL_PIN_VALUE).
Parameters
command The ID of the command to attach a callback function to.
newFunction A reference to the callback function to attach.
Definition at line 498 of file Firmata.cpp.
References ANALOG_MESSAGE, DIGITAL_MESSAGE, REPORT_ANALOG, REPORT_DIGITAL, SET_DIGITAL_PIN_VALUE, and SET_PIN_MODE.
Referenced by detach().
void FirmataClass::attach (byte command, systemResetCallbackFunction newFunction)
Attach a callback function for the SYSTEM_RESET command.
Parameters
command Must be set to SYSTEM_RESET or it will be ignored.
newFunction A reference to the system reset callback function to attach.
Definition at line 515 of file Firmata.cpp.
References SYSTEM_RESET.
void FirmataClass::attach (byte command, stringCallbackFunction newFunction)
Attach a callback function for the STRING_DATA command.
Parameters
command Must be set to STRING_DATA or it will be ignored.
newFunction A reference to the string callback function to attach.
Definition at line 527 of file Firmata.cpp.
References STRING_DATA.
void FirmataClass::attach (byte command, sysexCallbackFunction newFunction)
Attach a generic sysex callback function to sysex command.
Parameters
command The ID of the command to attach a callback function to.
newFunction A reference to the sysex callback function to attach.
Definition at line 539 of file Firmata.cpp.
int FirmataClass::available (void)
A wrapper for Stream::available()
Returns
The number of bytes remaining in the input stream buffer.
Definition at line 226 of file Firmata.cpp.
References i, printFirmwareVersion(), REPORT_FIRMWARE, and STRING_DATA.
void FirmataClass::begin (void)
Initialize the default Serial transport at the default baud of 57600.
Definition at line 79 of file Firmata.cpp.
void FirmataClass::begin (long speed)
Initialize the default Serial transport and override the default baud. Sends the protocol version to the host application followed by the firmware version and name. blinkVersion is also called. To skip the call to blinkVersion, call Firmata.disableBlinkVersion() before calling Firmata.begin(baud).
Parameters
speed The baud to use. 57600 baud is the default value.
Definition at line 91 of file Firmata.cpp.
References blinkVersion(), printFirmwareVersion(), and printVersion().
void FirmataClass::begin (Stream & s)
Reassign the Firmata stream transport.
Parameters
s A reference to the Stream transport object. This can be any type of transport that implements the Stream interface. Some examples include Ethernet, WiFi and other UARTs on the board (Serial1, Serial2, etc).
Definition at line 106 of file Firmata.cpp.
References printFirmwareVersion(), and printVersion().
void FirmataClass::blinkVersion (void)
Blink the Firmata protocol version to the onboard LEDs (if the board has an onboard LED). If VERSION_BLINK_PIN is not defined in Boards.h for a particular board, then this method does nothing. The first series of flashes indicates the firmware major version (2 flashes = 2). The second series of flashes indicates the firmware minor version (5 flashes = 5).
Definition at line 132 of file Firmata.cpp.
References FIRMATA_FIRMWARE_MAJOR_VERSION, and FIRMATA_FIRMWARE_MINOR_VERSION.
Referenced by begin().
void FirmataClass::detach (byte command)
Detach a callback function for a specified command (such as SYSTEM_RESET, STRING_DATA, ANALOG_MESSAGE, DIGITAL_MESSAGE, etc).
Parameters
command The ID of the command to detatch the callback function from.
Definition at line 549 of file Firmata.cpp.
References attach(), START_SYSEX, STRING_DATA, and SYSTEM_RESET.
void FirmataClass::disableBlinkVersion ()
Provides a means to disable the version blink sequence on the onboard LED, trimming startup time by a couple of seconds. Call this before Firmata.begin(). It only applies when using the default Serial transport.
Definition at line 150 of file Firmata.cpp.
void FirmataClass::endSysex (void)
A helper method to write the end of a Sysex message transmission.
Definition at line 51 of file Firmata.cpp.
References END_SYSEX.
Referenced by printFirmwareVersion(), and sendSysex().
byte FirmataClass::getPinMode (byte pin)
Parameters
pin The pin to get the configuration of.
Returns
The configuration of the specified pin.
Definition at line 564 of file Firmata.cpp.
int FirmataClass::getPinState (byte pin)
Parameters
pin The pin to get the state of.
Returns
The state of the specified pin.
Definition at line 588 of file Firmata.cpp.
boolean FirmataClass::isParsingMessage (void)
Returns
Returns true if the parser is actively parsing data.
Definition at line 378 of file Firmata.cpp.
void FirmataClass::parse (unsigned char value)
Parse data from the input stream.
Parameters
inputData A single byte to be added to the parser.
Definition at line 286 of file Firmata.cpp.
References ANALOG_MESSAGE, DIGITAL_MESSAGE, END_SYSEX, Firmata, printVersion(), REPORT_ANALOG, REPORT_DIGITAL, REPORT_VERSION, SET_DIGITAL_PIN_VALUE, SET_PIN_MODE, START_SYSEX, and SYSTEM_RESET.
Referenced by processInput().
void FirmataClass::printFirmwareVersion (void)
Sends the firmware name and version to the Firmata host application. The major and minor version numbers are the first 2 bytes in the message. The following bytes are the characters of the firmware name.
Definition at line 160 of file Firmata.cpp.
References endSysex(), i, REPORT_FIRMWARE, sendValueAsTwo7bitBytes(), and startSysex().
Referenced by available(), and begin().
void FirmataClass::printVersion (void)
Send the Firmata protocol version to the Firmata host application.
Definition at line 118 of file Firmata.cpp.
References FIRMATA_PROTOCOL_MAJOR_VERSION, FIRMATA_PROTOCOL_MINOR_VERSION, and REPORT_VERSION.
Referenced by begin(), and parse().
void FirmataClass::processInput (void)
Read a single int from the input stream. If the value is not = -1, pass it on to parse(byte)
Definition at line 274 of file Firmata.cpp.
References parse().
void FirmataClass::sendAnalog (byte pin, int value)
Send an analog message to the Firmata host application. The range of pins is limited to [0..15] when using the ANALOG_MESSAGE. The maximum value of the ANALOG_MESSAGE is limited to 14 bits (16384). To increase the pin range or value, see the documentation for the EXTENDED_ANALOG message.
Parameters
pin The analog pin to send the value of (limited to pins 0 - 15).
value The value of the analog pin (0 - 1024 for 10-bit analog, 0 - 4096 for 12-bit, etc). The maximum value is 14-bits (16384).
Definition at line 395 of file Firmata.cpp.
References ANALOG_MESSAGE, and sendValueAsTwo7bitBytes().
void FirmataClass::sendDigital (byte pin, int value)
Definition at line 408 of file Firmata.cpp.
void FirmataClass::sendDigitalPort (byte portNumber, int portData)
Send an 8-bit port in a single digital message (protocol v2 and later). Send 14-bits in a single digital message (protocol v1).
Parameters
portNumber The port number to send. Note that this is not the same as a `port` on the physical microcontroller. Ports are defined in order per every 8 pins in ascending order of the Arduino digital pin numbering scheme. Port 0 = pins D0 - D7, port 1 = pins D8 - D15, etc.
portData The value of the port. The value of each pin in the port is represented by a bit.
Definition at line 436 of file Firmata.cpp.
References DIGITAL_MESSAGE.
void FirmataClass::sendString (const char * string)
Send a string to the Firmata host application.
Parameters
string A pointer to the char string
Definition at line 477 of file Firmata.cpp.
References STRING_DATA.
Referenced by SerialFirmata::handleSysex().
void FirmataClass::sendString (byte command, const char * string)
Send a string to the Firmata host application.
Parameters
command Must be STRING_DATA
string A pointer to the char string
Definition at line 466 of file Firmata.cpp.
References sendSysex(), and STRING_DATA.
void FirmataClass::sendSysex (byte command, byte bytec, byte * bytev)
Send a sysex message where all values after the command byte are packet as 2 7-bit bytes (this is not always the case so this function is not always used to send sysex messages).
Parameters
command The sysex command byte.
bytec The number of data bytes in the message (excludes start, command and end bytes).
bytev A pointer to the array of data bytes to send in the message.
Definition at line 450 of file Firmata.cpp.
References endSysex(), i, sendValueAsTwo7bitBytes(), and startSysex().
Referenced by sendString().
void FirmataClass::sendValueAsTwo7bitBytes (int value)
Split a 16-bit byte into two 7-bit values and write each value.
Parameters
value The 16-bit value to be split and written separately.
Definition at line 34 of file Firmata.cpp.
Referenced by printFirmwareVersion(), sendAnalog(), and sendSysex().
void FirmataClass::setFirmwareNameAndVersion (const char * name, byte major, byte minor)
Sets the name and version of the firmware. This is not the same version as the Firmata protocol (although at times the firmware version and protocol version may be the same number).
Parameters
name A pointer to the name char array
major The major version number
minor The minor version number
Definition at line 183 of file Firmata.cpp.
void FirmataClass::setPinMode (byte pin, byte config)
Set the pin mode/configuration. The pin configuration (or mode) in Firmata represents the current function of the pin. Examples are digital input or output, analog input, pwm, i2c, serial (uart), etc.
Parameters
pin The pin to configure.
config The configuration value for the specified pin.
Definition at line 576 of file Firmata.cpp.
References PIN_MODE_IGNORE.
Referenced by SerialFirmata::handlePinMode(), and SerialFirmata::handleSysex().
void FirmataClass::setPinState (byte pin, int state)
Set the pin state. The pin state of an output pin is the pin value. The state of an input pin is 0, unless the pin has it's internal pull up resistor enabled, then the value is 1.
Parameters
pin The pin to set the state of
state Set the state of the specified pin
Definition at line 599 of file Firmata.cpp.
References i, and MAX_DATA_BYTES.
void FirmataClass::startSysex (void)
A helper method to write the beginning of a Sysex message transmission.
Definition at line 43 of file Firmata.cpp.
References START_SYSEX.
Referenced by printFirmwareVersion(), and sendSysex().
void FirmataClass::write (byte c)
A wrapper for Stream::available(). Write a single byte to the output stream.
Parameters
c The byte to be written.
Definition at line 487 of file Firmata.cpp.
Referenced by SerialFirmata::checkSerial(), and SerialFirmata::handleCapability().
The documentation for this class was generated from the following files:
Weather_Balloon/library/Firmata/Firmata.h
Weather_Balloon/library/Firmata/Firmata.cpp