PID Class Reference
#include <PID_v1.h>
Public Member Functions
PID (double *, double *, double *, double, double, double, int)
void SetMode (int Mode)
bool Compute ()
void SetOutputLimits (double, double)
void SetTunings (double, double, double)
void SetControllerDirection (int)
void SetSampleTime (int)
double GetKp ()
double GetKi ()
double GetKd ()
int GetMode ()
int GetDirection ()
Detailed Description
Definition at line 5 of file PID_v1.h.
Constructor & Destructor Documentation
PID::PID (double * Input, double * Output, double * Setpoint, double Kp, double Ki, double Kd, int ControllerDirection)
Definition at line 20 of file PID_v1.cpp.
References SetControllerDirection(), SetOutputLimits(), and SetTunings().
Member Function Documentation
bool PID::Compute ()
Definition at line 47 of file PID_v1.cpp.
References now().
int PID::GetDirection ()
Definition at line 194 of file PID_v1.cpp.
double PID::GetKd ()
Definition at line 192 of file PID_v1.cpp.
double PID::GetKi ()
Definition at line 191 of file PID_v1.cpp.
double PID::GetKp ()
Definition at line 190 of file PID_v1.cpp.
int PID::GetMode ()
Definition at line 193 of file PID_v1.cpp.
References AUTOMATIC, and MANUAL.
void PID::SetControllerDirection (int Direction)
Definition at line 174 of file PID_v1.cpp.
Referenced by PID().
void PID::SetMode (int Mode)
Definition at line 146 of file PID_v1.cpp.
References AUTOMATIC.
void PID::SetOutputLimits (double Min, double Max)
Definition at line 125 of file PID_v1.cpp.
Referenced by PID().
void PID::SetSampleTime (int NewSampleTime)
Definition at line 105 of file PID_v1.cpp.
void PID::SetTunings (double Kp, double Ki, double Kd)
Definition at line 83 of file PID_v1.cpp.
References REVERSE.
Referenced by PID().
The documentation for this class was generated from the following files:
Weather_Balloon/library/Arduino-PID-Library/PID_v1.h
Weather_Balloon/library/Arduino-PID-Library/PID_v1.cpp