Adafruit_ADXL345_Unified Class Reference
#include <Adafruit_ADXL345_U.h>
Public Member Functions
Adafruit_ADXL345_Unified (int32_t sensorID=-1)
Instantiates a new ADXL345 class.
Adafruit_ADXL345_Unified (uint8_t clock, uint8_t miso, uint8_t mosi, uint8_t cs, int32_t sensorID=-1)
Instantiates a new ADXL345 class in SPI mode.
bool begin (void)
Setups the HW (reads coefficients values, etc.)
void setRange (range_t range)
Sets the g range for the accelerometer.
range_t getRange (void)
Sets the g range for the accelerometer.
void setDataRate (dataRate_t dataRate)
Sets the data rate for the ADXL345 (controls power consumption)
dataRate_t getDataRate (void)
Gets the data rate for the ADXL345 (controls power consumption)
bool getEvent (sensors_event_t *)
Gets the most recent sensor event.
void getSensor (sensor_t *)
Gets the sensor_t data.
uint8_t getDeviceID (void)
Read the device ID (can be used to check connection)
void writeRegister (uint8_t reg, uint8_t value)
Writes 8-bits to the specified destination register.
uint8_t readRegister (uint8_t reg)
Reads 8-bits from the specified register.
int16_t read16 (uint8_t reg)
Reads 16-bits from the specified register.
int16_t getX (void)
Gets the most recent X axis value.
int16_t getY (void)
Gets the most recent Y axis value.
int16_t getZ (void)
Gets the most recent Z axis value.
void setCorrection (double)
Detailed Description
Definition at line 106 of file Adafruit_ADXL345_U.h.
Constructor & Destructor Documentation
Adafruit_ADXL345_Unified::Adafruit_ADXL345_Unified (int32_t sensorID = -1)
Instantiates a new ADXL345 class.
Definition at line 183 of file Adafruit_ADXL345_U.cpp.
References ADXL345_RANGE_2_G.
Adafruit_ADXL345_Unified::Adafruit_ADXL345_Unified (uint8_t clock, uint8_t miso, uint8_t mosi, uint8_t cs, int32_t sensorID = -1)
Instantiates a new ADXL345 class in SPI mode.
Definition at line 195 of file Adafruit_ADXL345_U.cpp.
References ADXL345_RANGE_2_G, and clock.
Member Function Documentation
bool Adafruit_ADXL345_Unified::begin (void)
Setups the HW (reads coefficients values, etc.)
Definition at line 210 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_POWER_CTL, getDeviceID(), Wire, and writeRegister().
dataRate_t Adafruit_ADXL345_Unified::getDataRate (void)
Gets the data rate for the ADXL345 (controls power consumption)
Definition at line 289 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_BW_RATE, and readRegister().
uint8_t Adafruit_ADXL345_Unified::getDeviceID (void)
Read the device ID (can be used to check connection)
Definition at line 146 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_DEVID, and readRegister().
Referenced by begin().
bool Adafruit_ADXL345_Unified::getEvent (sensors_event_t * event) [virtual]
Gets the most recent sensor event.
Implements Adafruit_Sensor.
Definition at line 299 of file Adafruit_ADXL345_U.cpp.
References ADXL345_MG2G_MULTIPLIER, getX(), getY(), getZ(), SENSOR_TYPE_ACCELEROMETER, and SENSORS_GRAVITY_STANDARD.
range_t Adafruit_ADXL345_Unified::getRange (void)
Sets the g range for the accelerometer.
Definition at line 266 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_DATA_FORMAT, and readRegister().
void Adafruit_ADXL345_Unified::getSensor (sensor_t * sensor) [virtual]
Gets the sensor_t data.
Implements Adafruit_Sensor.
Definition at line 319 of file Adafruit_ADXL345_U.cpp.
References sensor_t::max_value, sensor_t::min_delay, sensor_t::min_value, sensor_t::name, sensor_t::resolution, sensor_t::sensor_id, SENSOR_TYPE_PRESSURE, sensor_t::type, and sensor_t::version.
int16_t Adafruit_ADXL345_Unified::getX (void)
Gets the most recent X axis value.
Definition at line 156 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_DATAX0, and read16().
Referenced by getEvent().
int16_t Adafruit_ADXL345_Unified::getY (void)
Gets the most recent Y axis value.
Definition at line 165 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_DATAY0, and read16().
Referenced by getEvent().
int16_t Adafruit_ADXL345_Unified::getZ (void)
Gets the most recent Z axis value.
Definition at line 174 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_DATAZ0, and read16().
Referenced by getEvent().
int16_t Adafruit_ADXL345_Unified::read16 (uint8_t reg)
Reads 16-bits from the specified register.
Definition at line 124 of file Adafruit_ADXL345_U.cpp.
References ADXL345_ADDRESS, and Wire.
Referenced by getX(), getY(), and getZ().
uint8_t Adafruit_ADXL345_Unified::readRegister (uint8_t reg)
Reads 8-bits from the specified register.
Definition at line 102 of file Adafruit_ADXL345_U.cpp.
References ADXL345_ADDRESS, and Wire.
Referenced by getDataRate(), getDeviceID(), getRange(), and setRange().
void Adafruit_ADXL345_Unified::setCorrection (double correction_value)
Definition at line 335 of file Adafruit_ADXL345_U.cpp.
void Adafruit_ADXL345_Unified::setDataRate (dataRate_t dataRate)
Sets the data rate for the ADXL345 (controls power consumption)
Definition at line 277 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_BW_RATE, and writeRegister().
void Adafruit_ADXL345_Unified::setRange (range_t range)
Sets the g range for the accelerometer.
Definition at line 242 of file Adafruit_ADXL345_U.cpp.
References ADXL345_REG_DATA_FORMAT, readRegister(), and writeRegister().
void Adafruit_ADXL345_Unified::writeRegister (uint8_t reg, uint8_t value)
Writes 8-bits to the specified destination register.
Definition at line 83 of file Adafruit_ADXL345_U.cpp.
References ADXL345_ADDRESS, and Wire.
Referenced by begin(), setDataRate(), and setRange().
The documentation for this class was generated from the following files:
Weather_Balloon/library/Adafruit_ADXL345-master/Adafruit_ADXL345_U.h
Weather_Balloon/library/Adafruit_ADXL345-master/Adafruit_ADXL345_U.cpp