RTC_DS3231 Class Reference
#include <RTC_DS3231.h>
Public Member Functions
uint8_t isrunning (void)
Static Public Member Functions
static uint8_t begin (void)
static void adjust (const DateTime &dt)
static DateTime now ()
static float getTempAsFloat ()
static int16_t getTempAsWord ()
static void enable32kHz (uint8_t enable)
static void forceTempConv (uint8_t block)
static void SQWEnable (uint8_t enable)
static void BBSQWEnable (uint8_t enable)
static void SQWFrequency (uint8_t freq)
static void getControlRegisterData (char &datastr)
Detailed Description
Definition at line 19 of file RTC_DS3231.h.
Member Function Documentation
void RTC_DS3231::adjust (const DateTime & dt) [static]
Set the datetime of the RTC
Definition at line 51 of file RTC_DS3231.cpp.
References bin2bcd(), DateTime::day(), DS3231_ADDRESS, DS3231_REG_SECONDS, DateTime::hour(), DateTime::minute(), DateTime::month(), DateTime::second(), Wire, and DateTime::year().
void RTC_DS3231::BBSQWEnable (uint8_t enable) [static]
Enable or disable the output to the SQW pin. Send 1 or true to enable. This method enables BOTH the square wave and the battery backed output.
Definition at line 266 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_CONTROL, and Wire.
uint8_t RTC_DS3231::begin (void) [static]
Definition at line 32 of file RTC_DS3231.cpp.
void RTC_DS3231::enable32kHz (uint8_t enable) [static]
Enable or disable the 32kHz pin. When 1 it will output 32768kHz.
Definition at line 164 of file RTC_DS3231.cpp.
References bcd2bin(), DS3231_ADDRESS, DS3231_REG_STATUS_CTL, and Wire.
void RTC_DS3231::forceTempConv (uint8_t block) [static]
Force the temp sensor to convert the temp into digital code and execute the TCXO algorithm. The DS3231 normally does this every 64 seconds anyway.
NOTE: This is a BLOCKING method. You have been warned.
This method has not been fully debugged.
Definition at line 198 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_CONTROL, and Wire.
void RTC_DS3231::getControlRegisterData (char & datastr) [static]
Definition at line 318 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_CONTROL, i, and Wire.
float RTC_DS3231::getTempAsFloat () [static]
Return temperature as a float in degrees C Data is 10bits provided in 2 bytes (11h and and 2bits in 12h) Resolution of 0.25C e.g. 00011001 01 = 25.25C 00011001 = 25 01 = 0.25 * 1 = .25
This function has not been tested
Definition at line 101 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_TEMP_MSB, and Wire.
int16_t RTC_DS3231::getTempAsWord () [static]
Return temperature as a 2 bytes in degrees C MSB is the significant 00011001 = 25 LSB is the mantissa 00011001 = .25 Display by writing them out to the display MSB . LSB
Data from the 3231 10bits provided in 2 bytes (11h and and 2bits in 12h) Resolution of 0.25C e.g. 00011001 01 = 25.25C 00011001 = 25 01 = 0.25 * 1 = .25
This function has not been tested
Definition at line 136 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_TEMP_MSB, and Wire.
uint8_t RTC_DS3231::isrunning (void)
Definition at line 37 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_STATUS_CTL, and Wire.
DateTime RTC_DS3231::now () [static]
Get the datetime from the RTC
Definition at line 71 of file RTC_DS3231.cpp.
References bcd2bin(), DS3231_ADDRESS, DS3231_REG_SECONDS, and Wire.
void RTC_DS3231::SQWEnable (uint8_t enable) [static]
Enable or disable the output to the SQW pin. Send 1 or true to enable. This function does not enable battery backed output which helps conserve battery life.
Definition at line 234 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_CONTROL, and Wire.
void RTC_DS3231::SQWFrequency (uint8_t freq) [static]
Set the output frequence of the squarewave SQW pin
HINT: Use the defined frequencies in the .h file
Definition at line 298 of file RTC_DS3231.cpp.
References DS3231_ADDRESS, DS3231_REG_CONTROL, and Wire.
The documentation for this class was generated from the following files:
Weather_Balloon/library/RTClib-master/RTC_DS3231.h
Weather_Balloon/library/RTClib-master/RTC_DS3231.cpp