Adafruit_SHT31 Class Reference
#include <Adafruit_SHT31.h>
Public Member Functions
Adafruit_SHT31 ()
boolean begin (uint8_t i2caddr=SHT31_DEFAULT_ADDR)
float readTemperature (void)
float readHumidity (void)
uint16_t readStatus (void)
void reset (void)
void heater (boolean)
uint8_t crc8 (const uint8_t *data, int len)
Detailed Description
Definition at line 37 of file Adafruit_SHT31.h.
Constructor & Destructor Documentation
Adafruit_SHT31::Adafruit_SHT31 ()
Definition at line 20 of file Adafruit_SHT31.cpp.
Member Function Documentation
boolean Adafruit_SHT31::begin (uint8_t i2caddr = SHT31_DEFAULT_ADDR)
Definition at line 24 of file Adafruit_SHT31.cpp.
References reset(), and Wire.
Referenced by configure_sht31().
uint8_t Adafruit_SHT31::crc8 (const uint8_t * data, int len)
Definition at line 119 of file Adafruit_SHT31.cpp.
References i.
Referenced by readHumidity().
void Adafruit_SHT31::heater (boolean h)
Definition at line 47 of file Adafruit_SHT31.cpp.
References SHT31_HEATERDIS, and SHT31_HEATEREN.
float Adafruit_SHT31::readHumidity (void)
Definition at line 62 of file Adafruit_SHT31.cpp.
References crc8(), i, SHT31_MEAS_HIGHREP, and Wire.
Referenced by readSensors().
uint16_t Adafruit_SHT31::readStatus (void)
Definition at line 32 of file Adafruit_SHT31.cpp.
References SHT31_READSTATUS, and Wire.
float Adafruit_SHT31::readTemperature (void)
Definition at line 55 of file Adafruit_SHT31.cpp.
Referenced by readSensors().
void Adafruit_SHT31::reset (void)
Definition at line 42 of file Adafruit_SHT31.cpp.
References SHT31_SOFTRESET.
Referenced by begin().
The documentation for this class was generated from the following files:
Weather_Balloon/library/Adafruit_SHT31-master/Adafruit_SHT31.h
Weather_Balloon/library/Adafruit_SHT31-master/Adafruit_SHT31.cpp