TinyGPSLocation Struct Reference
#include <TinyGPS++.h>
Public Member Functions
bool isValid () const
bool isUpdated () const
uint32_t age () const
const RawDegrees & rawLat ()
const RawDegrees & rawLng ()
double lat ()
double lng ()
TinyGPSLocation ()
Friends
class TinyGPSPlus
Detailed Description
Definition at line 53 of file TinyGPS++.h.
Constructor & Destructor Documentation
TinyGPSLocation::TinyGPSLocation () [inline]
Definition at line 65 of file TinyGPS++.h.
Member Function Documentation
uint32_t TinyGPSLocation::age () const [inline]
Definition at line 59 of file TinyGPS++.h.
bool TinyGPSLocation::isUpdated () const [inline]
Definition at line 58 of file TinyGPS++.h.
bool TinyGPSLocation::isValid () const [inline]
Definition at line 57 of file TinyGPS++.h.
Referenced by read_GPS().
double TinyGPSLocation::lat ()
Definition at line 353 of file TinyGPS++.cpp.
Referenced by read_GPS().
double TinyGPSLocation::lng ()
Definition at line 360 of file TinyGPS++.cpp.
References TinyGPSPlus::date, TinyGPSPlus::parseDecimal(), and TinyGPSPlus::time.
Referenced by read_GPS().
const RawDegrees& TinyGPSLocation::rawLat () [inline]
Definition at line 60 of file TinyGPS++.h.
const RawDegrees& TinyGPSLocation::rawLng () [inline]
Definition at line 61 of file TinyGPS++.h.
Friends And Related Function Documentation
friend class TinyGPSPlus [friend]
Definition at line 55 of file TinyGPS++.h.
The documentation for this struct was generated from the following files:
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.h
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.cpp