FilterDerivative Struct Reference
#include <FilterDerivative.h>
Public Member Functions
float input (float inVal)
float output ()
Public Attributes
long LastUS
float LastInput
float Derivative
Detailed Description
Definition at line 5 of file FilterDerivative.h.
Member Function Documentation
float FilterDerivative::input (float inVal)
Definition at line 4 of file FilterDerivative.cpp.
References Derivative, LastInput, LastUS, and output().
Referenced by testFilterDerivative().
float FilterDerivative::output ()
Definition at line 15 of file FilterDerivative.cpp.
References Derivative.
Referenced by input(), and testFilterDerivative().
Member Data Documentation
float FilterDerivative::Derivative
Definition at line 9 of file FilterDerivative.h.
Referenced by input(), and output().
float FilterDerivative::LastInput
Definition at line 7 of file FilterDerivative.h.
Referenced by input().
long FilterDerivative::LastUS
Definition at line 6 of file FilterDerivative.h.
Referenced by input().
The documentation for this struct was generated from the following files:
Weather_Balloon/library/Filters/FilterDerivative.h
Weather_Balloon/library/Filters/FilterDerivative.cpp