FilterOnePoleCascade Struct Reference
#include <FilterOnePole.h>
Public Member Functions
FilterOnePoleCascade (float riseTime=1.0, float initialValue=0)
void setRiseTime (float riseTime)
void setToNewValue (float newVal)
float input (float inVal)
float output ()
void test ()
Public Attributes
FilterOnePole Pole1
FilterOnePole Pole2
Detailed Description
Definition at line 55 of file FilterOnePole.h.
Constructor & Destructor Documentation
FilterOnePoleCascade::FilterOnePoleCascade (float riseTime = 1.0, float initialValue = 0)
Definition at line 128 of file FilterOnePole.cpp.
References FilterOnePole::setToNewValue().
Member Function Documentation
float FilterOnePoleCascade::input (float inVal)
Definition at line 140 of file FilterOnePole.cpp.
References FilterOnePole::output().
Referenced by RunningStatistics::input(), and test().
float FilterOnePoleCascade::output ()
Definition at line 151 of file FilterOnePole.cpp.
Referenced by RunningStatistics::mean(), test(), and RunningStatistics::variance().
void FilterOnePoleCascade::setRiseTime (float riseTime)
Definition at line 133 of file FilterOnePole.cpp.
Referenced by RunningStatistics::setWindowSecs().
void FilterOnePoleCascade::setToNewValue (float newVal)
Definition at line 146 of file FilterOnePole.cpp.
Referenced by RunningStatistics::setInitialValue(), and test().
void FilterOnePoleCascade::test ()
Definition at line 155 of file FilterOnePole.cpp.
References i, input(), now(), output(), and setToNewValue().
Member Data Documentation
FilterOnePole FilterOnePoleCascade::Pole1
Definition at line 57 of file FilterOnePole.h.
FilterOnePole FilterOnePoleCascade::Pole2
Definition at line 58 of file FilterOnePole.h.
The documentation for this struct was generated from the following files:
Weather_Balloon/library/Filters/FilterOnePole.h
Weather_Balloon/library/Filters/FilterOnePole.cpp