FilterOnePole Struct Reference
#include <FilterOnePole.h>
Public Member Functions
FilterOnePole (FILTER_TYPE ft=LOWPASS, float fc=1.0, float initialValue=0)
void setFilter (FILTER_TYPE ft, float tauS, float initialValue)
void setFrequency (float newFrequency)
void setTau (float newTau)
float input (float inVal)
float output ()
void print ()
void test ()
void setToNewValue (float newVal)
Public Attributes
FILTER_TYPE FT
float TauUS
float TauSamps
float Y
float Ylast
float X
float ElapsedUS
long LastUS
Detailed Description
Definition at line 17 of file FilterOnePole.h.
Constructor & Destructor Documentation
FilterOnePole::FilterOnePole (FILTER_TYPE ft = LOWPASS, float fc = 1.0, float initialValue = 0)
Definition at line 4 of file FilterOnePole.cpp.
References setFilter().
Member Function Documentation
float FilterOnePole::input (float inVal)
Definition at line 19 of file FilterOnePole.cpp.
References ElapsedUS, LastUS, output(), TauSamps, TauUS, X, Y, and Ylast.
Referenced by test().
float FilterOnePole::output ()
Definition at line 52 of file FilterOnePole.cpp.
References DIFFERENTIATOR, FT, HIGHPASS, INTEGRATOR, LOWPASS, TauUS, X, and Y.
Referenced by input(), FilterOnePoleCascade::input(), and test().
void FilterOnePole::print ()
Definition at line 77 of file FilterOnePole.cpp.
References ElapsedUS, TauSamps, TauUS, X, Y, and Ylast.
void FilterOnePole::setFilter (FILTER_TYPE ft, float tauS, float initialValue)
Definition at line 8 of file FilterOnePole.cpp.
References FT, LastUS, setFrequency(), X, Y, and Ylast.
Referenced by FilterOnePole().
void FilterOnePole::setFrequency (float newFrequency)
Definition at line 44 of file FilterOnePole.cpp.
References setTau().
Referenced by setFilter().
void FilterOnePole::setTau (float newTau)
Definition at line 48 of file FilterOnePole.cpp.
References TauUS.
Referenced by setFrequency().
void FilterOnePole::setToNewValue (float newVal)
Definition at line 121 of file FilterOnePole.cpp.
References X, Y, and Ylast.
Referenced by FilterOnePoleCascade::FilterOnePoleCascade().
void FilterOnePole::test ()
Definition at line 89 of file FilterOnePole.cpp.
References HIGHPASS, input(), LOWPASS, now(), and output().
Member Data Documentation
float FilterOnePole::ElapsedUS
Definition at line 31 of file FilterOnePole.h.
Referenced by input(), and print().
FILTER_TYPE FilterOnePole::FT
Definition at line 18 of file FilterOnePole.h.
Referenced by output(), and setFilter().
long FilterOnePole::LastUS
Definition at line 32 of file FilterOnePole.h.
Referenced by input(), and setFilter().
float FilterOnePole::TauSamps
Definition at line 20 of file FilterOnePole.h.
Referenced by input(), and print().
float FilterOnePole::TauUS
Definition at line 19 of file FilterOnePole.h.
Referenced by input(), output(), print(), and setTau().
float FilterOnePole::X
Definition at line 26 of file FilterOnePole.h.
Referenced by input(), output(), print(), setFilter(), and setToNewValue().
float FilterOnePole::Y
Definition at line 23 of file FilterOnePole.h.
Referenced by input(), output(), print(), setFilter(), and setToNewValue().
float FilterOnePole::Ylast
Definition at line 24 of file FilterOnePole.h.
Referenced by input(), print(), setFilter(), and setToNewValue().
The documentation for this struct was generated from the following files:
Weather_Balloon/library/Filters/FilterOnePole.h
Weather_Balloon/library/Filters/FilterOnePole.cpp