TinyGPSTime Struct Reference
#include <TinyGPS++.h>
Public Member Functions
bool isValid () const
bool isUpdated () const
uint32_t age () const
uint32_t value ()
uint8_t hour ()
uint8_t minute ()
uint8_t second ()
uint8_t centisecond ()
TinyGPSTime ()
Friends
class TinyGPSPlus
Detailed Description
Definition at line 101 of file TinyGPS++.h.
Constructor & Destructor Documentation
TinyGPSTime::TinyGPSTime () [inline]
Definition at line 115 of file TinyGPS++.h.
References setTime(), and TinyGPSPlus::time.
Member Function Documentation
uint32_t TinyGPSTime::age () const [inline]
Definition at line 107 of file TinyGPS++.h.
Referenced by read_GPS().
uint8_t TinyGPSTime::centisecond ()
Definition at line 428 of file TinyGPS++.cpp.
References TinyGPSPlus::parseDecimal(), and TinyGPSPlus::time.
uint8_t TinyGPSTime::hour ()
Definition at line 410 of file TinyGPS++.cpp.
References TinyGPSPlus::time.
Referenced by read_GPS().
bool TinyGPSTime::isUpdated () const [inline]
Definition at line 106 of file TinyGPS++.h.
bool TinyGPSTime::isValid () const [inline]
Definition at line 105 of file TinyGPS++.h.
Referenced by read_GPS().
uint8_t TinyGPSTime::minute ()
Definition at line 416 of file TinyGPS++.cpp.
References TinyGPSPlus::time.
Referenced by read_GPS().
uint8_t TinyGPSTime::second ()
Definition at line 422 of file TinyGPS++.cpp.
References TinyGPSPlus::time.
Referenced by read_GPS().
uint32_t TinyGPSTime::value () [inline]
Definition at line 109 of file TinyGPS++.h.
References hour(), minute(), second(), and TinyGPSPlus::time.
Referenced by read_GPS().
Friends And Related Function Documentation
friend class TinyGPSPlus [friend]
Definition at line 103 of file TinyGPS++.h.
The documentation for this struct was generated from the following files:
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.h
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.cpp