TinyGPSDecimal Struct Reference
#include <TinyGPS++.h>
Public Member Functions
bool isValid () const
bool isUpdated () const
uint32_t age () const
int32_t value ()
TinyGPSDecimal ()
Friends
class TinyGPSPlus
Detailed Description
Definition at line 126 of file TinyGPS++.h.
Constructor & Destructor Documentation
TinyGPSDecimal::TinyGPSDecimal () [inline]
Definition at line 135 of file TinyGPS++.h.
Member Function Documentation
uint32_t TinyGPSDecimal::age () const [inline]
Definition at line 132 of file TinyGPS++.h.
Referenced by read_GPS().
bool TinyGPSDecimal::isUpdated () const [inline]
Definition at line 131 of file TinyGPS++.h.
bool TinyGPSDecimal::isValid () const [inline]
Definition at line 130 of file TinyGPS++.h.
Referenced by read_GPS().
int32_t TinyGPSDecimal::value () [inline]
Definition at line 133 of file TinyGPS++.h.
Referenced by read_GPS().
Friends And Related Function Documentation
friend class TinyGPSPlus [friend]
Definition at line 128 of file TinyGPS++.h.
The documentation for this struct was generated from the following files:
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.h
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.cpp