FilterTwoPole Struct Reference
#include <FilterTwoPole.h>
Public Member Functions
FilterTwoPole (float frequency0=1, float qualityFactor=1, float xInit=0)
void setQ (float qualityFactor)
void setFrequency0 (float f)
void setAsFilter (OSCILLATOR_TYPE ft, float frequency3db, float initialValue=0)
float input (float drive=0)
float output ()
float getMaxAmp ()
void print ()
void test ()
Public Attributes
float X
float Vprev
float Vavg
float Fprev
float Q
float W0
bool IsHighpass
long LastTimeUS
Detailed Description
Definition at line 31 of file FilterTwoPole.h.
Constructor & Destructor Documentation
FilterTwoPole::FilterTwoPole (float frequency0 = 1, float qualityFactor = 1, float xInit = 0)
Definition at line 64 of file FilterTwoPole.cpp.
References IsHighpass, LastTimeUS, setFrequency0(), setQ(), Vprev, and X.
Member Function Documentation
float FilterTwoPole::getMaxAmp ()
Definition at line 158 of file FilterTwoPole.cpp.
References Vprev, W0, and X.
float FilterTwoPole::input (float drive = 0)
Definition at line 120 of file FilterTwoPole.cpp.
References Fprev, LastTimeUS, now(), output(), Q, Vavg, Vprev, W0, and X.
Referenced by test().
float FilterTwoPole::output ()
Definition at line 150 of file FilterTwoPole.cpp.
References X.
Referenced by input(), and test().
void FilterTwoPole::print ()
Definition at line 174 of file FilterTwoPole.cpp.
References Vprev, and X.
void FilterTwoPole::setAsFilter (OSCILLATOR_TYPE ft, float frequency3db, float initialValue = 0)
Definition at line 86 of file FilterTwoPole.cpp.
References IsHighpass, LOWPASS_BESSEL, LOWPASS_BUTTERWORTH, setFrequency0(), setQ(), and X.
void FilterTwoPole::setFrequency0 (float f)
Definition at line 82 of file FilterTwoPole.cpp.
References W0.
Referenced by FilterTwoPole(), and setAsFilter().
void FilterTwoPole::setQ (float qualityFactor)
Definition at line 75 of file FilterTwoPole.cpp.
References Q.
Referenced by FilterTwoPole(), and setAsFilter().
void FilterTwoPole::test ()
Definition at line 180 of file FilterTwoPole.cpp.
References input(), now(), and output().
Member Data Documentation
float FilterTwoPole::Fprev
Definition at line 37 of file FilterTwoPole.h.
Referenced by input().
bool FilterTwoPole::IsHighpass
Definition at line 42 of file FilterTwoPole.h.
Referenced by FilterTwoPole(), and setAsFilter().
long FilterTwoPole::LastTimeUS
Definition at line 44 of file FilterTwoPole.h.
Referenced by FilterTwoPole(), and input().
float FilterTwoPole::Q
Definition at line 39 of file FilterTwoPole.h.
Referenced by input(), and setQ().
float FilterTwoPole::Vavg
Definition at line 36 of file FilterTwoPole.h.
Referenced by input().
float FilterTwoPole::Vprev
Definition at line 35 of file FilterTwoPole.h.
Referenced by FilterTwoPole(), getMaxAmp(), input(), and print().
float FilterTwoPole::W0
Definition at line 40 of file FilterTwoPole.h.
Referenced by getMaxAmp(), input(), and setFrequency0().
float FilterTwoPole::X
Definition at line 34 of file FilterTwoPole.h.
Referenced by FilterTwoPole(), getMaxAmp(), input(), output(), print(), and setAsFilter().
The documentation for this struct was generated from the following files:
Weather_Balloon/library/Filters/FilterTwoPole.h
Weather_Balloon/library/Filters/FilterTwoPole.cpp