RunningStatistics Struct Reference
#include <RunningStatistics.h>
Public Member Functions
void input (float inVal)
RunningStatistics ()
void setWindowSecs (float windowSecs)
void setInitialValue (float initialMean, float initialSigma=0)
float mean ()
float variance ()
float sigma ()
float CV ()
Public Attributes
float AverageSecs
FilterOnePoleCascade averageValue
FilterOnePoleCascade averageSquareValue
Detailed Description
Definition at line 6 of file RunningStatistics.h.
Constructor & Destructor Documentation
RunningStatistics::RunningStatistics ()
Definition at line 4 of file RunningStatistics.cpp.
References setInitialValue(), and setWindowSecs().
Member Function Documentation
float RunningStatistics::CV ()
Definition at line 49 of file RunningStatistics.cpp.
References mean(), and sigma().
void RunningStatistics::input (float inVal)
Definition at line 21 of file RunningStatistics.cpp.
References averageSquareValue, averageValue, and FilterOnePoleCascade::input().
Referenced by testRunningStatistics().
float RunningStatistics::mean ()
Definition at line 26 of file RunningStatistics.cpp.
References averageValue, and FilterOnePoleCascade::output().
Referenced by CV(), and testRunningStatistics().
void RunningStatistics::setInitialValue (float initialMean, float initialSigma = 0)
Definition at line 16 of file RunningStatistics.cpp.
References averageSquareValue, averageValue, and FilterOnePoleCascade::setToNewValue().
Referenced by RunningStatistics(), and testRunningStatistics().
void RunningStatistics::setWindowSecs (float windowSecs)
Definition at line 9 of file RunningStatistics.cpp.
References AverageSecs, averageSquareValue, averageValue, and FilterOnePoleCascade::setRiseTime().
Referenced by RunningStatistics().
float RunningStatistics::sigma ()
Definition at line 39 of file RunningStatistics.cpp.
References variance().
Referenced by CV(), and testRunningStatistics().
float RunningStatistics::variance ()
Definition at line 30 of file RunningStatistics.cpp.
References averageSquareValue, averageValue, and FilterOnePoleCascade::output().
Referenced by sigma().
Member Data Documentation
float RunningStatistics::AverageSecs
Definition at line 11 of file RunningStatistics.h.
Referenced by setWindowSecs().
FilterOnePoleCascade RunningStatistics::averageSquareValue
Definition at line 14 of file RunningStatistics.h.
Referenced by input(), setInitialValue(), setWindowSecs(), and variance().
FilterOnePoleCascade RunningStatistics::averageValue
Definition at line 13 of file RunningStatistics.h.
Referenced by input(), mean(), setInitialValue(), setWindowSecs(), and variance().
The documentation for this struct was generated from the following files:
Weather_Balloon/library/Filters/RunningStatistics.h
Weather_Balloon/library/Filters/RunningStatistics.cpp