TinyGPSDate Struct Reference
#include <TinyGPS++.h>
Public Member Functions
bool isValid () const
bool isUpdated () const
uint32_t age () const
uint32_t value ()
uint16_t year ()
uint8_t month ()
uint8_t day ()
TinyGPSDate ()
Friends
class TinyGPSPlus
Detailed Description
Definition at line 77 of file TinyGPS++.h.
Constructor & Destructor Documentation
TinyGPSDate::TinyGPSDate () [inline]
Definition at line 90 of file TinyGPS++.h.
References TinyGPSPlus::date.
Member Function Documentation
uint32_t TinyGPSDate::age () const [inline]
Definition at line 83 of file TinyGPS++.h.
Referenced by read_GPS().
uint8_t TinyGPSDate::day ()
Definition at line 404 of file TinyGPS++.cpp.
References TinyGPSPlus::date.
Referenced by read_GPS().
bool TinyGPSDate::isUpdated () const [inline]
Definition at line 82 of file TinyGPS++.h.
bool TinyGPSDate::isValid () const [inline]
Definition at line 81 of file TinyGPS++.h.
Referenced by read_GPS().
uint8_t TinyGPSDate::month ()
Definition at line 398 of file TinyGPS++.cpp.
References TinyGPSPlus::date.
Referenced by read_GPS().
uint32_t TinyGPSDate::value () [inline]
Definition at line 85 of file TinyGPS++.h.
References TinyGPSPlus::date, day(), month(), and year().
Referenced by read_GPS().
uint16_t TinyGPSDate::year ()
Definition at line 391 of file TinyGPS++.cpp.
References TinyGPSPlus::date, and year().
Referenced by read_GPS().
Friends And Related Function Documentation
friend class TinyGPSPlus [friend]
Definition at line 79 of file TinyGPS++.h.
The documentation for this struct was generated from the following files:
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.h
Weather_Balloon/library/TinyGPSPlus-0.94b/TinyGPS++.cpp